-- Run the entire idempotent install (tables, data, constraints,
-- indexes, foreign keys, functions and views).
-- Usage:  psql -d dbanalytics -f sql_scripts/00_install_all_tables.sql

\ir 00_prereqs.sql

\ir install_tables/action.action_types.sql
\ir install_tables/alerts.alert_log.sql
\ir install_tables/alerts.blocker_log.sql
\ir install_tables/alerts.blocks.sql
\ir install_tables/alerts.mail_alert_log.sql
\ir install_tables/config.access_review_cycles.sql
\ir install_tables/config.action_types.sql
\ir install_tables/config.alerts.sql
\ir install_tables/config.alerts_issue_root_causes.sql
\ir install_tables/config.alerts_reports.sql
\ir install_tables/config.alerts_thresholds.sql
\ir install_tables/config.attestation_controls.sql
\ir install_tables/config.attestation_periods.sql
\ir install_tables/config.blocked_ips.sql
\ir install_tables/config.compliance_report_schedules.sql
\ir install_tables/config.data_regions.sql
\ir install_tables/config.dump_metrics.sql
\ir install_tables/config.dumps.sql
\ir install_tables/config.firewall_policies.sql
\ir install_tables/config.global_params.sql
\ir install_tables/config.mail_alerts.sql
\ir install_tables/config.mail_alerts_schedule.sql
\ir install_tables/config.mail_config.sql
\ir install_tables/config.mail_groups.sql
\ir install_tables/config.mail_jobs.sql
\ir install_tables/config.masking_rules.sql
\ir install_tables/config.masking_tokens.sql
\ir install_tables/config.regulation_profiles.sql
\ir install_tables/config.reports.sql
\ir install_tables/config.reports_jobs.sql
\ir install_tables/config.retention_policy.sql
\ir install_tables/config.risk_register.sql
\ir install_tables/config.siem.sql
\ir install_tables/config.sime_interface.sql
\ir install_tables/config.sod_rules.sql
\ir install_tables/config.sqli_signatures.sql
\ir install_tables/config.suspended_users.sql
\ir install_tables/config.threat_response_playbooks.sql
\ir install_tables/config.thresholds.sql
\ir install_tables/config.transfer_agreements.sql
\ir install_tables/config.webook_alerts.sql
\ir install_tables/flowchart.visual_objects.sql
\ir install_tables/jobs.job_schedules.sql
\ir install_tables/jobs.jobs.sql
\ir install_tables/jobs.monitoring_job_history.sql
\ir install_tables/jobs.monitoring_jobs.sql
\ir install_tables/jobs.monitoring_jobschdules.sql
\ir install_tables/log.access_review_decisions.sql
\ir install_tables/log.access_review_instances.sql
\ir install_tables/log.attestations.sql
\ir install_tables/log.cross_border_transfers.sql
\ir install_tables/log.ddl_audit_log.sql
\ir install_tables/log.firewall_audit_log.sql
\ir install_tables/log.hash_chain_checkpoints.sql
\ir install_tables/log.incident_capa.sql
\ir install_tables/log.incident_timeline.sql
\ir install_tables/log.incidents.sql
\ir install_tables/log.operation_log.sql
\ir install_tables/log.security_incidents.sql
\ir install_tables/log.sod_violations.sql
\ir install_tables/log.threat_response_log.sql
\ir install_tables/meta.schema_migrations.sql
\ir install_tables/metrics.categories.sql
\ir install_tables/metrics.custom_metrics.sql
\ir install_tables/metrics.encryption_log.sql
\ir install_tables/metrics.encryption_preview.sql
\ir install_tables/metrics.mask_preview.sql
\ir install_tables/metrics.masking_log.sql
\ir install_tables/metrics.metric_relation.sql
\ir install_tables/metrics.metric_types.sql
\ir install_tables/metrics.metrics.sql
\ir install_tables/metrics.metrics_columns.sql
\ir install_tables/metrics.metrics_thresholds.sql
\ir install_tables/metrics.registered_processes.sql
\ir install_tables/metrics.routines.sql
\ir install_tables/metrics.routines_thresholds.sql
\ir install_tables/metrics.sensitive_columns.sql
\ir install_tables/metrics.server_log.sql
\ir install_tables/metrics.server_metrics_thresholds.sql
\ir install_tables/metrics.servers.sql
\ir install_tables/metrics.servers_routines.sql
\ir install_tables/metrics.servers_routines_thresholds.sql
\ir install_tables/metrics.servers_thresholds.sql
\ir install_tables/metrics.sql_injection_patterns.sql
\ir install_tables/metrics.thresaholds.sql
\ir install_tables/metrics.thresholds.sql
\ir install_tables/monitoring.actions.sql
\ir install_tables/monitoring.active_sessions.sql
\ir install_tables/monitoring.active_transactions.sql
\ir install_tables/monitoring.active_transactions_locks.sql
\ir install_tables/monitoring.active_transactions_long_queries.sql
\ir install_tables/monitoring.ad_hoc_cpu_consuming_queries.sql
\ir install_tables/monitoring.alert_actions.sql
\ir install_tables/monitoring.alert_case.sql
\ir install_tables/monitoring.alert_instances.sql
\ir install_tables/monitoring.alerts.sql
\ir install_tables/monitoring.alerts_open.sql
\ir install_tables/monitoring.audit_trails_databaselogs.sql
\ir install_tables/monitoring.autoencoder_sql_anomalies.sql
\ir install_tables/monitoring.autoencoder_v1_sql_anomalies.sql
\ir install_tables/monitoring.connection_network_io.sql
\ir install_tables/monitoring.database_performance.sql
\ir install_tables/monitoring.database_unmasked_users.sql
\ir install_tables/monitoring.general_metric_metadata_results.sql
\ir install_tables/monitoring.general_metric_metadata_results_active_transactions.sql
\ir install_tables/monitoring.general_metric_metadata_results_old.sql
\ir install_tables/monitoring.gmmr_2025_06.sql
\ir install_tables/monitoring.gmmr_2025_07.sql
\ir install_tables/monitoring.gmmr_2025_08.sql
\ir install_tables/monitoring.gmmr_2025_09.sql
\ir install_tables/monitoring.gmmr_2025_10.sql
\ir install_tables/monitoring.gmmr_2025_11.sql
\ir install_tables/monitoring.gmmr_2025_12.sql
\ir install_tables/monitoring.gmmr_2026_01.sql
\ir install_tables/monitoring.gmmr_2026_02.sql
\ir install_tables/monitoring.gmmr_2026_03.sql
\ir install_tables/monitoring.gmmr_2026_04.sql
\ir install_tables/monitoring.gmmr_2026_05.sql
\ir install_tables/monitoring.gmmr_2026_06.sql
\ir install_tables/monitoring.gmmr_2026_07.sql
\ir install_tables/monitoring.gmmr_2026_08.sql
\ir install_tables/monitoring.gmmr_2026_09.sql
\ir install_tables/monitoring.gmmr_2026_10.sql
\ir install_tables/monitoring.gmmr_2026_11.sql
\ir install_tables/monitoring.gmmr_2026_12.sql
\ir install_tables/monitoring.gmmr_2027_01.sql
\ir install_tables/monitoring.gmmr_2027_02.sql
\ir install_tables/monitoring.gmmr_2027_03.sql
\ir install_tables/monitoring.gmmr_2027_04.sql
\ir install_tables/monitoring.gmmr_2027_05.sql
\ir install_tables/monitoring.gmmr_2027_06.sql
\ir install_tables/monitoring.gmmr_default.sql
\ir install_tables/monitoring.injection_requests.sql
\ir install_tables/monitoring.latency.sql
\ir install_tables/monitoring.metric_latest_result.sql
\ir install_tables/monitoring.metric_query_parsing.sql
\ir install_tables/monitoring.metric_results.sql
\ir install_tables/monitoring.metric_results_active_transactions.sql
\ir install_tables/monitoring.metric_results_expensive_transactions.sql
\ir install_tables/monitoring.os_memory.sql
\ir install_tables/monitoring.privileged_logins.sql
\ir install_tables/monitoring.query_anomality.sql
\ir install_tables/monitoring.query_embeddings_json.sql
\ir install_tables/monitoring.schema.sql
\ir install_tables/monitoring.sensitive_schema.sql
\ir install_tables/monitoring.server_hardening_unused_inactive_sql_server_logins.sql
\ir install_tables/monitoring.service_account_permissions.sql
\ir install_tables/monitoring.siem_active_session_monitoring.sql
\ir install_tables/monitoring.siem_login_failures.sql
\ir install_tables/monitoring.sql_feature_predictions.sql
\ir install_tables/monitoring.sql_injection_suspicious_activity.sql
\ir install_tables/monitoring.sql_predictions.sql
\ir install_tables/monitoring.sql_suspicious.sql
\ir install_tables/monitoring.table_usage.sql
\ir install_tables/monitoring.tcp_connections.sql
\ir install_tables/monitoring.transaction_requests.sql
\ir install_tables/monitoring.user_risk_events.sql
\ir install_tables/monitoring.user_risk_profiles.sql
\ir install_tables/monitoring.weak_passwords.sql
\ir install_tables/monitoring_history.metric_results.sql
\ir install_tables/processes.executions.sql
\ir install_tables/processes.organization.sql
\ir install_tables/processes.organizations_servers.sql
\ir install_tables/processes.process.sql
\ir install_tables/processes.steps.sql
\ir install_tables/public.areas.sql
\ir install_tables/public.clientdetails.sql
\ir install_tables/public.database_types.sql
\ir install_tables/public.detection_events.sql
\ir install_tables/public.detection_path_steps.sql
\ir install_tables/public.detection_paths.sql
\ir install_tables/public.detection_steps.sql
\ir install_tables/public.domains.sql
\ir install_tables/public.issues.sql
\ir install_tables/public.knowledge_provenance.sql
\ir install_tables/public.report_items_indicators_detailfiles.sql
\ir install_tables/public.resolution_actions.sql
\ir install_tables/public.resolution_path_steps.sql
\ir install_tables/public.resolution_paths.sql
\ir install_tables/public.resolution_steps.sql
\ir install_tables/public.root_causes.sql
\ir install_tables/public.vendors.sql
\ir install_tables/reports.html_reports.sql
\ir install_tables/reports.pdf_reports.sql
\ir install_tables/rootcause.areas.sql
\ir install_tables/rootcause.database_types.sql
\ir install_tables/rootcause.detection_path_steps.sql
\ir install_tables/rootcause.detection_paths.sql
\ir install_tables/rootcause.detection_steps.sql
\ir install_tables/rootcause.domains.sql
\ir install_tables/rootcause.issue_decision_tree_nodes.sql
\ir install_tables/rootcause.issue_decision_trees.sql
\ir install_tables/rootcause.issue_root_causes_vendor_query.sql
\ir install_tables/rootcause.issues.sql
\ir install_tables/rootcause.resolution_path_steps.sql
\ir install_tables/rootcause.resolution_paths.sql
\ir install_tables/rootcause.resolution_steps.sql
\ir install_tables/rootcause.risk_level.sql
\ir install_tables/rootcause.root_causes.sql
\ir install_tables/rootcause.root_causes_purges.sql
\ir install_tables/rootcause.rootcause_alert_query.sql
\ir install_tables/rootcause.rootcause_alert_query_result_server.sql
\ir install_tables/rootcause.severity.sql
\ir install_tables/rootcause.vendors.sql
\ir install_tables/siem.fortianalyzer_ips_events.sql
\ir install_tables/siem_config.sime_interface.sql
\ir install_tables/threats.login_threats.sql
\ir install_tables/threats.login_threats_history.sql
\ir install_tables/threats.metric_results.sql
\ir install_tables/threats.metric_results_history.sql
\ir install_tables/threats.object_threats.sql
\ir install_tables/threats.object_threats_history.sql
\ir install_tables/threats.session_threats.sql
\ir install_tables/threats.session_threats_history.sql
\ir install_tables/users.temp_login_result.sql
\ir install_tables/users.user_panel.sql
\ir install_tables/web.audit_log.sql
\ir install_tables/web.chat_messages.sql
\ir install_tables/web.refresh_tokens.sql
\ir install_tables/web.users.sql
\ir install_tables/widget.areas.sql
\ir install_tables/widget.categories.sql
\ir install_tables/widget.categories_queries.sql
\ir install_tables/widget.categories_queries_columns.sql
\ir install_tables/widget.category_detailfiles.sql
\ir install_tables/widget.chart_template.sql
\ir install_tables/widget.domains.sql
\ir install_tables/widget.indicators.sql
\ir install_tables/widget.indicators_datafiles.sql
\ir install_tables/widget.main_form.sql
\ir install_tables/widget.report.sql
\ir install_tables/widget.report_items.sql
\ir install_tables/widget.report_items_indicators.sql
\ir install_tables/widget.report_items_indicators_detailfiles.sql
\ir install_tables/widget.report_items_indicators_risk.sql
\ir install_tables/widget.reports.sql
\ir install_tables/widget.sql_injection_patterns.sql
\ir install_tables/widget.treeview.sql
\ir install_tables/widget.widget.sql
\ir install_tables/widget.widget_chart_object.sql

\ir 90_foreign_keys.sql
\ir 95_views_and_functions.sql
