-- Idempotent install for metrics.metrics
-- Auto-generated from dbanalytics_install.backup. Safe to re-run (psql -f).

CREATE SCHEMA IF NOT EXISTS metrics;

CREATE SEQUENCE IF NOT EXISTS metrics.metrics_row_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE IF NOT EXISTS metrics.metrics (
    row_id integer NOT NULL,
    metric_name character varying(50) NOT NULL,
    query text NOT NULL,
    metric_type character varying(50),
    metric_description text,
    category_id integer,
    entry_date timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE metrics.metrics ALTER COLUMN row_id SET DEFAULT nextval('metrics.metrics_row_id_seq'::regclass);
ALTER SEQUENCE metrics.metrics_row_id_seq OWNED BY metrics.metrics.row_id;

-- data: load only into a freshly-created (empty) table
DROP TABLE IF EXISTS _stg_load;
CREATE TEMP TABLE _stg_load (LIKE metrics.metrics);
COPY _stg_load (row_id, metric_name, query, metric_type, metric_description, category_id, entry_date) FROM stdin;
17	total_io	  select\ntotal_io,\nINSTANCE,\nDatabase Name,\nentry_date\nFROM monitoring.database_performance	dbexpert	High total i/o	1	2025-04-21 18:55:57.627382
19	Available_Size	select  \nAvailable Size (GB) ,\nSERVER,\nlogical_volume_name ,\nentry_date\nFROM monitoring.disk_volums	dbexpert	Size available	1	2025-04-21 18:57:55.117998
20	disk_space	SELECT\nFreespace\n,INSTANCE_NAME\n,DRIVE\n,VALIDFROM\n FROM BSDUPTIME.monitoring.diskspace	dbexpert	Left disk space	1	2025-04-21 18:58:30.917977
21	Read Latency	SELECT Read Latency\n      ,INSTANCE\n      ,Drive\n      ,entry_date\n  FROM BSDUPTIME.monitoring.drive_latency	dbexpert	Read latency	1	2025-04-21 19:00:04.336687
10	avg_read_stall_ms	select\navg_read_stall_ms,\nFROM monitoring.database_performance where server = $server	dbexpert		1	2024-06-21 07:40:11.223
49	scheduler_tasks	select Avg Runnable Task Count , SERVER , ''description  , System Time FROM monitoring.scheduler_tasks	dbexpert	Average  Runnable Tasks	1	2025-04-21 20:14:08.51687
50	indexes	select replace(ExtPctOperatorCost ,'%',''),  SERVER , query description    , entry_date FROM monitoring.Execution_Plans where physicalop like '%Index Scan%'	dbexpert	Indexes	1	2025-04-21 20:14:08.51687
55	Missing indexes execution Plan	SELECT TotalImpact\n,server\n,Database.Schema.Table + ' ' + equality_columns + ' ' + query\n      ,last_request_end_time\n  FROM BSDUPTIME.monitoring.Execution_plan_missing_index\n	dbexpert	Missing indexes execution Plan	1	2025-04-21 20:14:08.51687
56	Locked sessions	SELECT session_id\n        ,SERVER , wait_type ,\n        entry_date\n  FROM BSDUPTIME.monitoring.Active_Sessions\n  where WAIT_TYPE LIKE '%_LCK'\n  AND entry_date >DATEADD(minute , -1 , getdate())	dbexpert	Locked sessions	1	2025-04-21 20:14:08.51687
58	Blocks	SELECT session_id ,      SERVER,  query  , last_request_end_time\n  FROM BSDUPTIME.monitoring.active_transactions\n  where last_request_end_time > DATEADD(minute, -1 , GETDATE())\n  and SESSION_ID = blocking_session_id	dbexpert	Blocks	1	2025-04-21 20:14:08.51687
59	Long duration transactions	SELECT duration_secs\n      ,SERVER  , Query      \n        ,last_request_end_time\n  FROM BSDUPTIME.monitoring.active_transactions\n  where last_request_end_time > DATEADD(minute, -15 , getdate())\n  and duration_secs >0	dbexpert	Long duration transactions	1	2025-04-21 20:14:08.51687
60	Long transaction	select 'transaction duration is over 60 seconds: '+ convert(varchar,duration_secs)   + ' seconds: ' + Text from monitoring.active_transactions_requests where login_time > dateadd(minute,-1,getdate()) and duration_secs > 0	dbexpert	long duration transaction	1	2025-04-21 20:14:15.511979
61	blocking transactions	SELECT    server\n      ,database_name , 1 Locks ,  convert(varchar(19),last_request_end_time  ,121 ) TIMESTAMP\n  FROM monitoring.active_transactions\n  where last_request_end_time > DATEADD(minute, -1 , GETDATE())\n  and duration_secs >60\n  and session_id in\n  (\n  select blocking_session_id  \n    FROM monitoring.active_transactions\n  where last_request_end_time > DATEADD(minute, -1 , GETDATE())\n  )\n	dbexpert	blocking transactions	1	2025-04-21 20:14:15.511979
62	last_transaction	    SELECT\n      server\n      ,database_name\n        ,MAX(last_request_end_time) TIMESTAMP\n        ,datediff(minute,MAX(last_request_end_time),getdate())\n  FROM BSDUPTIME.monitoring.active_transactions at with(nolock)\n  where server is not null and command IN('update','INSERT into ','delete')  \n  group by server\n      ,database_name      \norder by server\n      ,database_name      \n	dbexpert	Last transaction is older then threshold	1	2025-04-21 20:14:15.511979
70	Average reads	\n\nwith A AS\n(\nselect\nrow_number() over ( partition by INSTANCE ,Database Name order by entry_date dESC ) seq\n,INSTANCE\n,Database Name\n,entry_date\n,avg_read_stall_ms\nFROM monitoring.database_performance\nwhere INSTANCE not in\n(\n'DESKTOP-ENQA4J7\\SQL2022',\n'bsduptime.c5kauuuesqps.us-east-1.rds.amazonaws.com,1433'\n)\n)\nselect\nINSTANCE\n,Database Name\n,entry_date\n,avg_read_stall_ms\nfrom A\nwhere  seq=1	dbexpert	Average reads	1	2025-04-21 21:20:57.143085
40	tempdb used	SELECT\n       internal object MB space   \n      INSTANCE\n      ,statement text\n      ,entry_date    \n  FROM BSDUPTIME.monitoring.tempdb_used	dbexpert	used tempdb	3	2025-04-21 20:06:34.375322
92	query_statistic_history	select servername SERVER , Root_Cause_Analysis  , Impact_Level ,entry_date from monitoring.Tracker   with(nolock)	dbexpert	database_slow_response	2	2025-04-21 21:23:37.842697
93	Read Latency	select\n            INSTANCE_NAME SERVER,\n            'DB:' +DB + ' physical_name: ' + physical_name + ' ReadLatency:' ,\n            ReadLatency  ,\n            entry_date\n      from monitoring.latency_per_file where INSTANCE_NAME in (select ''+LInked_server + '' from T_SERVERS where IS_ACTIVE=1)\n	dbexpert	database_slow_response	2	2025-04-21 21:23:45.909049
94	Write Latency	select\n            INSTANCE_NAME SERVER,\n            'DB:' +DB + ' physical_name: ' + physical_name + ' WriteLatency:'\n            WriteLatency       ,\n            entry_date\n      from monitoring.latency_per_file where INSTANCE_NAME in (select ''+LInked_server + '' from T_SERVERS where IS_ACTIVE=1)	dbexpert	database_slow_response	2	2025-04-21 21:24:25.252997
95	Overall Latency	    select\n            INSTANCE_NAME SERVER,\n            'DB:' +DB + ' physical_name: ' + physical_name + ' OverallLatency:'\n            OverallLatency     ,\n            entry_date\n      from monitoring.latency_per_file where INSTANCE_NAME in (select ''+LInked_server + '' from T_SERVERS where IS_ACTIVE=1)\n\n\n	dbexpert	database_slow_response	2	2025-04-21 21:24:29.683177
98	Unkown IP Adress - dressed to kill	SELECT server       ,'Checking Unkown IP address server:'+server+' '+   'client_net_address :'+ client_net_address   + 'connect_time:' +  convert(varchar(19),connect_time ,121)  +' net_transport: ' +net_transport + ' protocol_type:'+convert(varchar , protocol_type)        +' auth_scheme:' + auth_scheme        +' num_reads:'+convert(varchar,num_reads)        +' num_writes:'+convert(varchar,num_writes) details     ,session_id    \nFROM DBDOME.monitoring.TCP_connections c  with(nolock)  \nwhere   (   last_read > dateadd(minute , -1 , (select MAX(last_read) from DBDOME.monitoring.TCP_connections b where c.server =  b.server) )   or    last_write > dateadd(minute , -1 , (select MAX(last_write) from DBDOME.monitoring.TCP_connections b where c.server =  b.server) )  )  \nand\nCONNECT_TIME  > DATEADD(MINUTE,-1,getdate())  \nand client_net_address  NOT IN (SELECT client_net_address FROM DBDOME.monitoring.TCP_connections where connect_time < DATEadd(day , -1 , getdate()))\n	dbexpert	unknown tcp connection	2	2025-04-21 21:24:37.551649
100	Roles	select server ,  concat('server:' + dr.server   , ' user_name:' , 'database_name:' , database_name ,  user_name,',','database_role:',database_role) Description  , 1 COUNT from monitoring.database_database_role_users dr where database_role in ('db_owner','db_ddladmin')	dbexpert	Database roles	3	2025-04-21 21:24:47.719462
41	service info	SELECT startup_type\n      ,INSTANCE\n       ,servicename + ' ' + INSTANCE      \n      ,entry_date\n  FROM BSDUPTIME.monitoring.running_services	dbexpert	services	1	2025-04-21 20:06:39.987299
42	TotalTransactions	SELECT TotalTransactions\n      ,INSTANCE_NAME\n      ,DBNAME\n      ,entry_date\n  FROM BSDUPTIME.monitoring.transactions_per_db	dbexpert	Total transactions	1	2025-04-21 20:07:31.400556
43	No of indexes	SELECT COUNT(*) No of ondexes\n      ,INSTANCE_NAME\n      ,DATABASE_NAME\n      ,CONVERT(VARCHAR(10),entry_date,121)\n  FROM BSDUPTIME.monitoring.unused_indexes\nGROUP BY\n      INSTANCE_NAME\n      ,DATABASE_NAME\n,CONVERT(VARCHAR(10),entry_date,121)	dbexpert	No of indexes	3	2025-04-21 20:07:38.002026
44	Volums	SELECT Space Free %      \n      ,INSTANCE\n        ,volume_mount_point\n      ,entry_date\n  FROM BSDUPTIME.monitoring.volums	dbexpert	Volums	1	2025-04-21 20:07:42.314461
68	database increase	SELECT         INSTANCE\n      ,database_name\n        ,entry_date\n,Avg Size Diff From Previous (MB)\n  FROM BSDUPTIME.monitoring.data_stats	dbexpert	database increase	1	2025-04-21 21:20:45.437531
63	Long transactions requests	select servername  , database_name ,  Login_time , duration_secs  \nfrom monitoring.active_transactions_requests where login_time > dateadd(minute,-10,getdate()) and duration_secs > 0\n	dbexpert	Blocks	1	2025-04-21 21:19:56.531181
65	Active session Locks	\nSELECT      SERVER , '' database_name ,\n            convert(varchar(19),entry_date,121) TIMESTAMP,\n            count(*) LOCKS    \n  FROM BSDUPTIME.monitoring.Active_Sessions\n  where WAIT_TYPE LIKE '%_LCK'\n  AND entry_date >DATEADD(minute , -1 , getdate())\ngroup by SERVER,convert(varchar(19),entry_date,121)	dbexpert	Active session locks	1	2025-04-21 21:19:56.531181
66	buffer	select   server ,'' database_name , entry_date , case when cntr_value > 3600 then 0 else cntr_value end  value\n  FROM BSDUPTIME.monitoring.Buffer_Manager\n	dbexpert	cache	1	2025-04-21 21:20:29.014633
67	cpu utilization	with a as\n(\nSELECT\n      row_number() over (partition by   SERVER   order by Event Time desc) seq\n      ,  SERVER\n        ,'' Database_name\n        ,Event Time\n        ,SQL Server Process CPU Utilization   + Other Process CPU Utilization           Total Process CPU Utilization     \n  FROM BSDUPTIME.monitoring.cpu_events\n  where Event Time > dateadd(minute,-10,getdate())\n  )\n  select\n        SERVER\n        ,Database_name\n        ,Event Time\n        ,Total Process CPU Utilization    \nfrom a where seq=1\n\n\n	dbexpert	cpu	1	2025-04-21 21:20:37.249777
69	Database growth	with A as\n  (\n  SELECT      \n        row_number() over ( partition by instance , Database Name      order by entry_date DESC) seq\n        ,INSTANCE\n        ,Database Name      \n        ,entry_date\n      ,Growth in MB  value\n  FROM BSDUPTIME.monitoring.database_growth_info\n  where Database Name not in ('master','msdb' , 'model','demo')\n  )\n  select\n        INSTANCE\n        ,Database Name      \n        ,entry_date\n      ,value\n        from A where seq=1	dbexpert	Database growth	1	2025-04-21 21:20:45.437531
71	Average writes	\n\n\nwith A AS\n(\nselect\nrow_number() over ( partition by INSTANCE ,Database Name order by entry_date dESC ) seq\n,INSTANCE\n,Database Name\n,entry_date\n,avg_write_stall_ms\nFROM monitoring.database_performance\nwhere INSTANCE not in\n(\n'DESKTOP-ENQA4J7\\SQL2022',\n'bsduptime.c5kauuuesqps.us-east-1.rds.amazonaws.com,1433'\n)\n)\nselect\nINSTANCE\n,Database Name\n,entry_date\n,avg_write_stall_ms  \nfrom A where seq=1	dbexpert	Average writes	1	2025-04-21 21:20:57.143085
72	io stalls	with A AS\n(\nselect\nrow_number() over ( partition by INSTANCE ,Database Name order by entry_date dESC ) seq\n,INSTANCE\n,Database Name\n,entry_date\n,io_stalls\nFROM monitoring.database_performance\nwhere INSTANCE not in\n(\n'DESKTOP-ENQA4J7\\SQL2022',\n'bsduptime.c5kauuuesqps.us-east-1.rds.amazonaws.com,1433'\n)\n)\nselect\nINSTANCE\n,Database Name\n,entry_date\n,io_stalls\nFROM A where seq=1\n	dbexpert	IO stalls	1	2025-04-21 21:20:57.143085
73	Deadlocks	  SELECT\n       INSTANCE_NAME      \n         ,DatabaseName\n      ,convert(varchar(19),entry_date,121) entry_date\n        ,count(*) dead_locks\n  FROM monitoring.deadlock\nwhere entry_date > dateadd(minute,-10 , getdate())\nand instance_name is not null\nAND SqlStatement NOT LIKE '%CURSOR%'\ngroup by\nINSTANCE_NAME\n,DatabaseName\n,convert(varchar(19),entry_date,121)\n	dbexpert	Deadlocks	1	2025-04-21 21:20:57.143085
74	Free space	select  \nSERVER\n,'' database_name\n,entry_date\n,Space Free %  value\nFROM monitoring.disk_volums\n	dbexpert	Free space	1	2025-04-21 21:21:41.258695
75	Latency	SELECT   SERVER\n             ,'' Database_name\n            ,entry_date\n            ,Overall Latency            \nFROM BSDUPTIME.monitoring.latency\n	dbexpert	Latency	1	2025-04-21 21:21:47.761838
76	Read Latency	SELECT SERVER\n      ,'' Database_name     \n      ,entry_date\n        ,Read Latency\n  FROM BSDUPTIME.monitoring.latency	dbexpert	Read latency	1	2025-04-21 21:21:53.522663
77	Write latency	SELECT SERVER\n      ,'' Database_name     \n      ,entry_date\n        ,Write Latency\n  FROM BSDUPTIME.monitoring.latency	dbexpert	Write latency	1	2025-04-21 21:21:57.931501
78	Available memory	SELECT\n      INSTANCE      \n      ,'' Database\n      ,entry_date\n        ,Available_OS_Memory_GB\n  FROM BSDUPTIME.monitoring.os_memory\n	dbexpert	Available memory	1	2025-04-21 21:22:02.532531
79	Log used	SELECT INSTANCE\n      ,Database Name\n      ,entry_date\n        ,Log Used %\n  FROM BSDUPTIME.monitoring.recoverymodel\n	dbexpert	Log used	1	2025-04-21 21:22:18.234027
80	Lock wait	SELECT\n            INSTANCE\n         ,''DATABASE_NAME      \n         ,convert(varchar(19),entry_date,121)entry_date     \n      ,MAX(convert(int,signal_cpu_waits))           signal_cpu_waits\n        \n  FROM BSDUPTIME.monitoring.signal_wait_time_ms\n  where ( WAIT_TYPE LIKE 'LCK_%' OR WAIT_TYPE LIKE 'PAGELATCH%')\ngroup by       INSTANCE , convert(varchar(19),entry_date,121)	dbexpert	Lock wait	1	2025-04-21 21:22:18.234027
81	Service down	SELECT\n      INSTANCE\n        ,'' Database_name\n      ,entry_date\n        ,1 service down\n     \n  FROM BSDUPTIME.monitoring.running_services\n  where servicename not like '%agent%' and startup_type !=2\n	dbexpert	Service down	1	2025-04-21 21:22:18.234027
22	Write Latency	SELECT Write Latency\n      ,INSTANCE\n      ,Drive\n      ,entry_date\n  FROM BSDUPTIME.monitoring.drive_latency	dbexpert	write latency	1	2025-04-21 19:08:04.832264
23	Overall Latency	SELECT Overall Latency\n      ,INSTANCE\n      ,Drive\n      ,entry_date\n  FROM BSDUPTIME.monitoring.drive_latency	dbexpert	overall latency	1	2025-04-21 19:08:34.926469
24	avg_fragmentation_in_percent	SELECT\n      AVG(avg_fragmentation_in_percent)avg_fragmentation_in_percent\n      ,INSTANCE\n      ,CONVERT(VARCHAR(16),entry_date,121)\n      ,DatabaseName\n  FROM BSDUPTIME.monitoring.fragmentation\n\nGROUP BY\nINSTANCE,\nCONVERT(VARCHAR(16),entry_date,121),\nDatabaseName	dbexpert	Average fragmentation percents	1	2025-04-21 19:09:11.122103
25	growthinfo	\n  SELECT\n      Avg Size Diff From Previous (MB)\n      ,SERVER\n      ,database_name\n      ,entry_date    \n  FROM BSDUPTIME.monitoring.growthinfo	dbexpert	Growth	1	2025-04-21 19:10:13.784274
26	last_backups	SELECT TimeTaken\n      ,INSTANCE\n      ,database_name\n      ,entry_date\n  FROM BSDUPTIME.monitoring.last_backups	dbexpert	Last backups	1	2025-04-21 19:10:58.958998
27	latency	SELECT Overall Latency\n      ,SERVER\n      ,Drive\n      ,entry_date\n  FROM BSDUPTIME.monitoring.latency	dbexpert	Latency	1	2025-04-21 19:11:32.109077
28	Read Latency	SELECT Read Latency\n      ,SERVER\n      ,Drive\n      ,entry_date\n  FROM BSDUPTIME.monitoring.latency	dbexpert	Read Latency	1	2025-04-21 19:12:25.789176
29	Write Latency	SELECT Write Latency\n      ,SERVER\n      ,Drive\n      ,entry_date\n  FROM BSDUPTIME.monitoring.latency	dbexpert	Write Latency	1	2025-04-21 19:12:55.788161
30	long_procedures_Duration	SELECT Current_Duration\n      ,INSTANCE\n      ,executing batch\n      ,entry_date\n  FROM BSDUPTIME.monitoring.long_procedures\n  where entry_date > DATEADD(HOUR,-1 , getdate())	dbexpert	procedure statistics	3	2025-04-21 19:47:53.1167
11	avg_write_stall_ms	select\navg_write_stall_ms\nFROM monitoring.database_performance where server = $server	dbexpert	Average write stall in Milli seconds	1	10000-01-01 00:00:00
12	avg_write_stall_ms	select\navg_write_stall_ms\nFROM monitoring.database_performance  where server = $server	dbexpert	Average write stall in Milli seconds	1	2025-04-21 18:49:38.077704
13	num_of_reads	select\nnum_of_reads\nFROM monitoring.database_performance  where server = $server	dbexpert	high reads	1	2025-04-21 18:50:23.162131
14	io_stall_write_ms	SELECT\n    AVG(io_stall_write_ms)::DECIMAL(18,0) AS io_stall_write_ms\nFROM monitoring.database_performance   where server = $server	dbexpert	io stall  writes in milliseconds	1	2025-04-21 18:52:31.639804
15	num_of_writes	select\navg(num_of_writes)::decimal(18,0)num_of_writes\nFROM monitoring.database_performance where server= $server\n	dbexpert	High number of writes	1	2025-04-21 18:53:02.443533
16	io_stalls	select\navg(io_stalls)::decimal(18,0)io_stalls\nFROM monitoring.database_performance where server = $server	dbexpert	High IO	1	2025-04-21 18:55:24.281655
31	long_queries_Duration	SELECT Current_Duration\n      ,INSTANCE\n      ,executing batch\n      ,entry_date\n  FROM BSDUPTIME.monitoring.long_queries\n  where entry_date > DATEADD(hour,-1 , getdate())	dbexpert	Log duration queries	3	2025-04-21 19:49:12.959771
32	missing indexes	SELECT distinct avg_total_user_cost\n      ,INSATANCE\n      ,Database.Schema.Table\n      ,entry_date      \n  FROM BSDUPTIME.monitoring.Missing_Indexes	dbexpert	Missing indexes	1	2025-04-21 19:49:18.311324
33	Available_OS_Memory_GB	SELECT Available_OS_Memory_GB\n      ,INSTANCE      \n      ,'' description\n      ,entry_date\n  FROM BSDUPTIME.monitoring.os_memory	dbexpert	Available memory	1	2025-04-21 19:49:23.307319
34	virtual memory	SELECT      \n            virtual memory\n            ,SERVER\n            ,perfmon memory\n      ,entry_date\n  FROM BSDUPTIME.monitoring.performance	dbexpert	virtual memory	1	2025-04-21 19:49:28.683761
35	procedure_stats	select AVG_DURATION msec\n,INSTANCE_NAME\n,procedure\n,entry_date\nFROM monitoring.procedure_stats	dbexpert	high duration procedure statistics	3	2025-04-21 20:06:08.207515
36	recoverymodel	SELECT Log Used %\n       ,INSTANCE\n      ,Database Name\n      ,entry_date\n  FROM BSDUPTIME.monitoring.recoverymodel	dbexpert	recoverymodel	1	2025-04-21 20:06:17.540402
38	wait_type	SELECT signal_cpu_waits\n            wait_type\n      ,INSTANCE\n      ,entry_date\n  FROM BSDUPTIME.monitoring.signal_wait_time_ms	dbexpert	\N	1	2025-04-21 20:06:22.466072
39	Average CPU Time (sec)	SELECT Average CPU Time (sec)\n       ,INSTANCE\n      ,SQL Statement\n      ,Last Execution Time            \n  FROM BSDUPTIME.monitoring.statements_in_cache	dbexpert	Wait types	2	2025-04-21 20:06:27.272941
1	avg_read_stall_ms	select avg_read_stall_ms FROM monitoring.database_performance where server = $server	dbexpert	\N	1	2025-04-25 19:33:53.125371
2	avg_write_stall_ms	select avg_write_stall_ms FROM monitoring.database_performance where server = $server	dbexpert	\N	1	2025-04-25 19:35:04.4332
3	num_of_reads	select num_of_reads FROM monitoring.database_performance where server = $server	dbexpert	\N	1	2025-04-25 19:36:49.542676
4	num_of_writes	select io_stall_write_ms FROM monitoring.database_performance where server = $server	dbexpert	\N	1	2025-04-25 19:45:38.974647
5	io_stalls	select io_stalls FROM monitoring.database_performance where server = $server	dbexpert	\N	1	2025-04-25 19:47:05.393356
6	total_io	select total_io FROM monitoring.database_performance where server = $server	dbexpert	\N	1	2025-04-25 19:47:30.082834
8	Read_Latency	SELECT Read_Latency FROM monitoring.latency where server = $server	dbexpert	\N	1	2025-04-25 20:39:44.095628
9	Write_Latency	SELECT Write_Latency FROM monitoring.latency where server = $server	dbexpert	\N	1	2025-04-25 20:41:02.949796
83	sql_injection	  select server , database_name ,  last_request_end_time , sql_injection  , '' OBJECT_NAME\n  from\n  (\n  SELECT\n      row_number() over (partition by SERVER order by last_request_end_time desc) seq\n    ,SERVER\n        ,at.database_name\n      , at.last_request_end_time\n        ,count(*)    sql_injection  \n  FROM BSDUPTIME.monitoring.active_transactions at where  last_request_end_time > dateadd(hour , -1 , getdate())\n  and ( statement  LIKE ('%users%') OR statement  LIKE ('%logins%') and statement like '%password%' or statement like '%1=1%')\ngroup by  \n      SERVER\n        ,at.database_name\n        ,last_request_end_time\n) A where a.seq=1\n	dbexpert	sql_injection	1	2025-04-21 21:22:18.234027
84	cpu stats	\nselect\n      server\n      ,DatabaseName\n   ,CPUPercent\n   ,entry_date\nfrom\n(\nSELECT\n      ROW_NUMBER() over (partition by INSTANCE_NAME  ORDER BY CPUPercent DESC )seq\n      ,INSTANCE_NAME SERVER\n        ,DatabaseName\n        ,CPUPercent\n   , entry_date FROM BSDUPTIME.monitoring.cpu_stats\n) A where seq=1\n\n	dbexpert	Database slow response	2	2025-04-21 21:22:24.242409
85	high_duration	\n\n\nSELECT server  , query , duration_secs  ,entry_date from\n(\nselect\nrow_number() over (partition by server  +'.'+ statement  order by duration_secs DESC ) seq\n,server  +'.'+ statement  server ,\nquery ,\nduration_secs ,\n(SELECT MAX(entry_date) FROM  monitoring_runtime.operation_log where operatiom_name = 'monitoring_sp.Active_transactions') entry_date\nfrom  monitoring.active_transactions  with(nolock) where last_request_end_time > dateadd(minute , -10 , (SELECT MAX(entry_date) FROM  monitoring_runtime.operation_log where operatiom_name = 'monitoring_sp.Active_transactions'))\nand duration_secs >0\n)a\nwhere a.seq=1	dbexpert	Database slow response	2	2025-04-21 21:22:24.242409
87	Locks_statement	SELECT server , statement   , count(blocking_session_id)Locks ,\n(select max(entry_date) from monitoring_runtime.operation_log where  message_content = 'monitoring_sp.Active_transactions completed') entry_date\nFROM monitoring.active_transactions with(nolock) where last_request_end_time > dateadd(minute,-10  , (select max(entry_date) from monitoring_runtime.operation_log where  message_content = 'monitoring_sp.Active_transactions completed'))\nand duration_secs >0\nand blocking_session_id !=0\ngroup by server , statement  \n\n	dbexpert	database_slow_response	2	2025-04-21 21:22:24.242409
88	Locks_query	SELECT server , query   , count(blocking_session_id) Locks  , (select max(entry_date) from monitoring_runtime.operation_log where  message_content = 'monitoring_sp.Active_transactions completed')  FROM monitoring.active_transactions with(nolock) where last_request_end_time > dateadd(minute,-10  , (select max(entry_date) from monitoring_runtime.operation_log where  message_content = 'monitoring_sp.Active_transactions completed'))\nand duration_secs >0\nand blocking_session_id !=0\ngroup by server , query\n	dbexpert	database_slow_response	2	2025-04-21 21:22:24.242409
89	Long_duration_queries	SELECT distinct server , query   , duration_secs , (select max(entry_date) from monitoring_runtime.operation_log where  message_content = 'monitoring_sp.Active_transactions completed')  FROM monitoring.active_transactions with(nolock) where last_request_end_time > dateadd(minute,-10  , (select max(entry_date) from monitoring_runtime.operation_log where  message_content = 'monitoring_sp.Active_transactions completed'))\nand duration_secs >0\norder by duration_secs desc	dbexpert	database_slow_response	2	2025-04-21 21:22:48.96135
90	Missing indexes	WITH XMLNAMESPACES ('http://schemas.microsoft.com/sqlserver/2004/07/showplan' AS p)\nSELECT \n      at.server,\n    n.value('(p:Column/@Name)1', 'NVARCHAR(128)')  + ' '  + \n      n.value('(p:ColumnGroup/@Usage)1', 'NVARCHAR(128)') AS ColumnUsage    ,\n    n.value('(p:MissingIndex/@Impact)1', 'FLOAT') AS ImpactPercentage ,  \n      at.last_request_end_time\nFROM monitoring.active_transactions at\nCROSS APPLY at.query_plan.nodes('//p:MissingIndexGroup/p:MissingIndex/p:ColumnGroup/p:Column') AS t(n)\nWHERE at.query_plan.exist('//p:MissingIndex') = 1\nAND AT.ID IN\n(\n      SELECT ID from monitoring.active_transactions at with(nolock) where last_request_end_time > dateadd(minute,-10  , (select max(entry_date) from monitoring_runtime.operation_log where  message_content = 'monitoring_sp.Active_transactions completed'))\n      and duration_secs >0\n)\n\n	dbexpert	database_slow_response	2	2025-04-21 21:22:48.96135
91	Table scans	\nWITH XMLNAMESPACES ('http://schemas.microsoft.com/sqlserver/2004/07/showplan' AS p)\nSELECT \n      at.server,\n    n.value('(p:Column/@Name)1', 'NVARCHAR(128)')  + ' '  + \n      n.value('(p:ColumnGroup/@Usage)1', 'NVARCHAR(128)') AS ColumnUsage    ,\n    n.value('(p:MissingIndex/@Impact)1', 'FLOAT') AS ImpactPercentage ,  \n      at.last_request_end_time\nFROM monitoring.active_transactions at\nCROSS APPLY at.query_plan.nodes('//p:MissingIndexGroup/p:MissingIndex/p:ColumnGroup/p:Column') AS t(n)\nWHERE at.query_plan.exist('//p:MissingIndex') = 1\nAND AT.ID IN\n(\n      SELECT ID from monitoring.active_transactions at with(nolock)  where last_request_end_time > dateadd(minute,-20  , (select max(entry_date) from monitoring_runtime.operation_log where  message_content = 'monitoring_sp.Active_transactions completed'))\n      and duration_secs > 0\n)\n\n\n	dbexpert	database_slow_response	2	2025-04-21 21:22:48.96135
99	Active_Transaction	select w.server ,'server:'+w.server+' '+ 'Login_name:' + Login_name  ,  A.session_id  FRom monitoring.whoisactive w\n  join\n  (\n  SELECT server , session_id    FROM DBDOME.monitoring.TCP_connections c  with(nolock)  where   (   last_read > dateadd(minute , -1 , (select MAX(last_read) from DBDOME.monitoring.TCP_connections b where c.server =  b.server) )   or    last_write > dateadd(minute , -1 , (select MAX(last_write) from DBDOME.monitoring.TCP_connections b where c.server =  b.server) )  )  \n    and connect_time > DATEADD(MINUTE,-1,getdate())  \n    --and client_net_address not in   (  SELECT client_net_address FROM DBDOME.monitoring.TCP_connections where entry_date  < DATEADD(HOUR,-1,getdate())  )  \n  )A   ON A.server  = w.server and A.session_Id   = w.session_id	dbexpert	Active transactions	2	2025-04-21 21:24:37.551649
101	Elevated users	 select SERVER ,\nconcat('server:' , server,'authentication_type:',authentication_type_desc,' ', 'databse_role:',database_role ) Description ,\ncount(*) COUNT\nfrom monitoring.database_elevated_users\ngroup by server , authentication_type_desc , Database_role	dbexpert	elevated users	3	2025-04-21 21:24:47.719462
\.
INSERT INTO metrics.metrics (row_id, metric_name, query, metric_type, metric_description, category_id, entry_date)
SELECT row_id, metric_name, query, metric_type, metric_description, category_id, entry_date FROM _stg_load
WHERE NOT EXISTS (SELECT 1 FROM metrics.metrics);
DROP TABLE _stg_load;

SELECT setval('metrics.metrics_row_id_seq', GREATEST((SELECT COALESCE(max(row_id),0) FROM metrics.metrics),1), (SELECT count(*) FROM metrics.metrics) > 0);

DO $do$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint con
        JOIN pg_class c ON c.oid = con.conrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'metrics' AND c.relname = 'metrics'
          AND con.conname = 'metrics_pkey') THEN
        ALTER TABLE ONLY metrics.metrics
    ADD CONSTRAINT metrics_pkey PRIMARY KEY (row_id);
    END IF;
END $do$;
