#!/usr/bin/env python3
"""
Generate insert_<module>_rootcause.sql from a module spec (JSON).

The output mirrors the existing hand-written scripts (e.g.
insert_pii_sensitive_columns_rootcause.sql): it seeds rootcause.root_causes,
per-vendor rootcause.detection_steps (the actual SQL), detection_paths +
detection_path_steps, resolution_steps + resolution_paths + resolution_path_steps,
and a monitoring.v_<rc> view per root cause. Wrapped in BEGIN/COMMIT, idempotent
inserts where practical.

Usage:
    python gen_rootcause_module.py specs/insider_threat.json > insert_insider_threat_rootcause.sql

Spec shape (see specs/insider_threat.json and specs/_template.json):
{
  "module": "insider_threat",
  "vendors": ["postgresql","sqlserver","oracle","mysql"],
  "root_causes": [
    {
      "rc": "SEC-SQL-INS-001-RC01",
      "issue": "SEC-SQL-INS-001",
      "name": "...", "slug": "...", "description": "...",
      "topics": ["..."], "risk_level": "high",
      "resolution": "remediation text",
      "expected": {"condition": "row_count > 0", "description": "..."},
      "columns": ["col_a","col_b"],          # optional: keys exposed by the view
      "detect": {"postgresql": "SELECT ...", "sqlserver": null, "oracle": null, "mysql": null}
    }
  ]
}
Vendors whose detect SQL is null/empty are skipped (no step/path emitted) — fill
them in later and re-generate.
"""
import json
import sys


def sql_lit(s):
    """Single-quoted SQL string literal (doubles embedded quotes)."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def sql_text_array(items):
    if not items:
        return "ARRAY[]::text[]"
    return "ARRAY[" + ", ".join(sql_lit(x) for x in items) + "]"


def jsonb_lit(obj):
    """A jsonb literal from a Python object: '<json>'::jsonb (SQL-escaped)."""
    return "'" + json.dumps(obj).replace("'", "''") + "'::jsonb"


def emit(spec):
    module = spec["module"]
    vendors = spec.get("vendors", ["postgresql", "sqlserver", "oracle", "mysql"])
    rcs = spec["root_causes"]
    out = []
    w = out.append

    w(f"-- ===========================================================================")
    w(f"-- Auto-generated by gen_rootcause_module.py from specs/{module}.json")
    w(f"-- Module: {module}   Root causes: {len(rcs)}   Vendors: {', '.join(vendors)}")
    w(f"-- DO NOT hand-edit; edit the spec and regenerate.")
    w(f"-- ===========================================================================")
    w("BEGIN;")
    w("")

    # 1) root_causes
    w("-- 1) ROOT CAUSES -----------------------------------------------------------")
    for rc in rcs:
        applicable = [v for v in vendors if rc.get("detect", {}).get(v)]
        w("INSERT INTO rootcause.root_causes "
          "(root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)")
        w("VALUES (")
        w(f"    {sql_lit(rc['rc'])}, {sql_lit(rc.get('issue'))}, {sql_lit(rc['name'])},")
        w(f"    {sql_lit(rc.get('slug'))}, {sql_lit(rc.get('description'))},")
        w(f"    {sql_text_array(rc.get('topics'))}, {sql_text_array(applicable or vendors)}")
        w(") ON CONFLICT (root_cause_id) DO UPDATE SET")
        w("    name = EXCLUDED.name, description = EXCLUDED.description,")
        w("    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;")
        w("")

    # 2) detection_steps (per vendor with SQL)
    w("-- 2) DETECTION STEPS (per vendor) ------------------------------------------")
    for rc in rcs:
        for v in vendors:
            detect = rc.get("detect", {}).get(v)
            if not detect:
                continue
            step_name = f"Detect {rc['rc']} ({v})"
            expected = rc.get("expected", {"condition": "row_count > 0",
                                           "description": rc.get("name", "")})
            w(f"INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)")
            w(f"VALUES ({sql_lit(v)}, 'query', {sql_lit(step_name)},")
            w(f"        {jsonb_lit({'sql': detect})},")
            w(f"        {jsonb_lit(expected)})")
            w(f"ON CONFLICT (vendor_slug, name) DO UPDATE SET")
            w(f"    content = EXCLUDED.content, expected = EXCLUDED.expected;")
            w("")

    # 3) paths + resolutions via a DO block
    w("-- 3) DETECTION PATHS + RESOLUTION (per root cause x vendor) ----------------")
    w("DO $gen$")
    w("DECLARE")
    w("    v_step_id   bigint;")
    w("    v_path_id   bigint;")
    w("    v_res_step  bigint;")
    w("    v_res_path  bigint;")
    w("BEGIN")
    for rc in rcs:
        res_text = rc.get("resolution", "Review and remediate per the root-cause guidance.")
        risk = rc.get("risk_level", "medium")
        for v in vendors:
            if not rc.get("detect", {}).get(v):
                continue
            step_name = f"Detect {rc['rc']} ({v})"
            w(f"    -- {rc['rc']} / {v}")
            w(f"    SELECT id INTO v_step_id FROM rootcause.detection_steps")
            w(f"     WHERE vendor_slug = {sql_lit(v)} AND name = {sql_lit(step_name)} "
              f"ORDER BY id DESC LIMIT 1;")
            w(f"    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths")
            w(f"       WHERE root_cause_id = {sql_lit(rc['rc'])} AND vendor_slug = {sql_lit(v)}) THEN")
            w(f"        INSERT INTO rootcause.detection_paths "
              f"(root_cause_id, vendor_slug, name, description, path_type, is_active)")
            w(f"        VALUES ({sql_lit(rc['rc'])}, {sql_lit(v)}, {sql_lit(step_name)}, "
              f"{sql_lit(rc.get('name'))}, 'diagnostic', true) RETURNING id INTO v_path_id;")
            w(f"        INSERT INTO rootcause.detection_path_steps "
              f"(detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)")
            w(f"        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');")
            w(f"        INSERT INTO rootcause.resolution_steps "
              f"(vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)")
            w(f"        VALUES ({sql_lit(v)}, 'recommendation', {sql_lit('Resolve: ' + step_name)}, "
              f"{jsonb_lit({'action': res_text})}, {sql_lit(risk)}, false, true) "
              f"RETURNING id INTO v_res_step;")
            w(f"        INSERT INTO rootcause.resolution_paths "
              f"(root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)")
            slug = "resolve-" + rc['rc'].lower().replace('-', '_') + "-" + v
            w(f"        VALUES ({sql_lit(rc['rc'])}, {sql_lit(v)}, {sql_lit('Resolve: ' + step_name)}, "
              f"{sql_lit(slug)}, {sql_lit(res_text)}, 'supervised', {sql_lit(risk)}, true) "
              f"RETURNING id INTO v_res_path;")
            w(f"        INSERT INTO rootcause.resolution_path_steps "
              f"(resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);")
            w(f"    END IF;")
    w("END")
    w("$gen$;")
    w("")

    # 4) monitoring views per root cause
    w("-- 4) MONITORING VIEWS (one per root cause) ---------------------------------")
    for rc in rcs:
        view = "monitoring.v_" + rc['rc'].lower().replace('-', '_')
        cols = rc.get("columns") or []
        col_sql = ",\n".join(
            f"    (j.value ->> {sql_lit(c)}) AS {c}" for c in cols
        )
        w(f"CREATE OR REPLACE VIEW {view} AS")
        w("SELECT r.server,")
        if col_sql:
            w(col_sql + ",")
        else:
            w("    j.value AS data,")
        w("    r.entry_date")
        w("FROM monitoring.general_metric_metadata_results r")
        w("  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)")
        w(f" WHERE r.metric_name = {sql_lit(rc['rc'])};")
        w("")

    # 5) verify
    w("-- 5) VERIFY ----------------------------------------------------------------")
    rc_ids = ", ".join(sql_lit(rc['rc']) for rc in rcs)
    w(f"SELECT root_cause_id, name, vendors_applicable FROM rootcause.root_causes")
    w(f" WHERE root_cause_id IN ({rc_ids});")
    w("")
    w("COMMIT;")
    return "\n".join(out)


def main():
    try:
        sys.stdout.reconfigure(encoding="utf-8")   # descriptions may contain — / →
    except Exception:
        pass
    if len(sys.argv) < 2:
        print("usage: gen_rootcause_module.py <spec.json>", file=sys.stderr)
        sys.exit(2)
    with open(sys.argv[1], "r", encoding="utf-8") as f:
        spec = json.load(f)
    sys.stdout.write(emit(spec))
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
