-- ===========================================================================
-- Auto-generated by gen_rootcause_module.py from specs/ransomware.json
-- Module: ransomware   Root causes: 71   Vendors: postgresql, sqlserver, oracle, mysql
-- DO NOT hand-edit; edit the spec and regenerate.
-- ===========================================================================
BEGIN;

-- 1) ROOT CAUSES -----------------------------------------------------------
INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-001-RC01', 'SEC-SQL-RAN-001', 'Ransom-note artifacts',
    'ran-001-ransom-note-artifacts', 'tables/databases named `RECOVER_YOUR_DATA`, `PLEASE_READ`, `WARNING`, `README_TO_RECOVER`, `DECRYPT_*`, `RESTORE_FILES`.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-002-RC01', 'SEC-SQL-RAN-002', 'Mass destruction events',
    'ran-002-mass-destruction-events', 'clusters of `DROP TABLE`, unqualified `DELETE`/`TRUNCATE`, unexplained row-count collapse.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-003-RC01', 'SEC-SQL-RAN-003', 'Shell-execution surface active',
    'ran-003-shell-execution-surface-active', '`xp_cmdshell`, `pg_execute_server_program`, `lib_mysqludf_sys` / `sys_exec`, Oracle DBMS_SCHEDULER `EXECUTABLE` jobs.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-004-RC01', 'SEC-SQL-RAN-004', 'Backup & recovery sabotage',
    'ran-004-backup-recovery-sabotage', 'history gaps, archive-log / WAL / binlog deletion.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-005-RC01', 'SEC-SQL-RAN-005', 'Pre-attack reconnaissance',
    'ran-005-pre-attack-reconnaissance', 'failed-login spikes, new privileged accounts, off-hours admin sessions from new client IPs.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-006-RC01', 'SEC-SQL-RAN-006', 'Data exfiltration indicators',
    'ran-006-data-exfiltration-indicators', 'anomalously large result sets, pagination with extreme OFFSET, native bulk-export primitives (`COPY TO PROGRAM`, `INTO OUTFILE`, `BCP OUT`, `expdp`).',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-007-RC01', 'SEC-SQL-RAN-007', 'Credential and schema reconnaissance',
    'ran-007-credential-and-schema-reconnaissance', 'reads of `pg_authid` / `mysql.user` / `SYS.USER$` / `sys.sql_logins`; INFORMATION_SCHEMA enumeration bursts.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-008-RC01', 'SEC-SQL-RAN-008', 'Living-off-the-land DBA tool abuse',
    'ran-008-living-off-the-land-dba-tool-abuse', '`pg_dump` / `mysqldump` / `BCP` / `expdp` running from hosts outside the documented backup-operator allow-list. 62% of CrowdStrike-tracked 2026 breaches are malware-free.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-009-RC01', 'SEC-SQL-RAN-009', 'Replication and backup infrastructure hijack',
    'ran-009-replication-and-backup-infrastructure-hijack', 'unauthorised replication slots, new REPLICATION grants, backup-catalog reads by non-backup accounts (Qilin''s signature move).',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-010-RC01', 'SEC-SQL-RAN-010', 'Audit and logging tampering',
    'ran-010-audit-and-logging-tampering', '`pgaudit` removed, MySQL `general_log` OFF, SQL Server XE session dropped, Oracle unified-audit policy `NOAUDIT`''d.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-011-RC01', 'SEC-SQL-RAN-011', 'Ransom-note collections',
    'ran-011-ransom-note-collections', 'on document DBs.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-012-RC01', 'SEC-SQL-RAN-012', 'Mass collection wipe',
    'ran-012-mass-collection-wipe', 'indicators.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-013-RC01', 'SEC-SQL-RAN-013', 'MongoDB pre-attack recon',
    'ran-013-mongodb-pre-attack-recon', 'auth-failure spikes.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-014-RC01', 'SEC-SQL-RAN-014', 'MongoDB exfiltration',
    'ran-014-mongodb-exfiltration', '`$out` / `$merge` to external collections, hostile replica-set members.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-015-RC01', 'SEC-SQL-RAN-015', 'PostgreSQL event-trigger backdoor / DDL persistence',
    'ran-015-postgresql-event-trigger-backdoor-ddl-persistence', 'attacker installs a `ddl_command_end` event trigger whose body grants superuser to a backdoor role. Next time *any* real superuser runs DDL, the trigger fires under that superuser''s identity and creates the backdoor. (CVE-2020-25695, Staaldraad PoC, Supabase write-up.)',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-016-RC01', 'SEC-SQL-RAN-016', 'Hypervisor-level ransomware (ESXi / vSphere)',
    'ran-016-hypervisor-level-ransomware-esxi-vsphere', 'Scattered Spider''s 2025 campaign + CVE-2025-22225 give attackers kernel-level ESXi access; they encrypt every DB VM on the host at once. Disk-swap variant detaches NTDS.dit from a powered-off DC VM and reattaches it to an attacker VM. Hypervisor share of encryption events rose from 3% (H1-2025) to 25% (H2-2025).',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-017-RC01', 'SEC-SQL-RAN-017', 'SaaS / Cloud-DB credential compromise without MFA',
    'ran-017-saas-cloud-db-credential-compromise-without-mfa', 'Snowflake 2024 / UNC5537: ~165 customer instances hit using infostealer-log credentials from as far back as 2020 against instances with MFA not required. AT&T, Ticketmaster, Santander, LendingTree all on the victim list.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-018-RC01', 'SEC-SQL-RAN-018', 'psql client-side SQL injection (CVE-2025-1094)',
    'ran-018-psql-client-side-sql-injection-cve-2025-1094', 'zero-day used in the BeyondTrust breach and the December 2024 US Treasury hack. The vulnerability is in the **client tool**, not the server. Any DBA workstation running psql against an untrusted SQL file is at risk.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-019-RC01', 'SEC-SQL-RAN-019', 'Cross-account / cross-region snapshot sharing',
    'ran-019-cross-account-cross-region-snapshot-sharing', 'Datadog Cloud Security Atlas attack-of-record. `rds:ModifyDBSnapshotAttribute` shares the snapshot with the attacker''s AWS account; the data never leaves the AWS VPC. Same surface for GCP Cloud SQL and Azure SQL long-term retention.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-020-RC01', 'SEC-SQL-RAN-020', 'REFRESH MATERIALIZED VIEW privilege escalation (CVE-2024-0985)',
    'ran-020-refresh-materialized-view-privilege-escalation-cve-2024-0985', 'attacker-owned materialized view tricks a superuser running `REFRESH … CONCURRENTLY` into executing arbitrary SQL with superuser privileges. Affects PG < 15.6 / 14.11 / 13.14 / 12.18.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-021-RC01', 'SEC-SQL-RAN-021', 'Deterministic / ECB-mode column encryption',
    'ran-021-deterministic-ecb-mode-column-encryption', '`aes-ecb` in pgcrypto, MySQL `AES_ENCRYPT()` without IV, SQL Server Always Encrypted DETERMINISTIC. Even without keys an attacker can frequency-analyse low-cardinality columns (state, country, status) and reconstruct values.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-022-RC01', 'SEC-SQL-RAN-022', 'Functional-index / CHECK-constraint persistence',
    'ran-022-functional-index-check-constraint-persistence', '`CREATE INDEX ON tbl ((attacker_function(col)))` or `CHECK (attacker_function(col))`. Every INSERT runs the attacker''s function under the table owner''s privileges. Invisible to trigger-only audits.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-023-RC01', 'SEC-SQL-RAN-023', 'Pre-auth SQLi on DB-backed vendor app (MOVEit / CL0P pattern)',
    'ran-023-pre-auth-sqli-on-db-backed-vendor-app-moveit-cl0p-pattern', 'CVE-2023-34362 hit 2,700+ orgs and 93.3M individuals. Same surface: Progress WS_FTP, Citrix NetScaler, Ivanti Sentry, ScreenConnect. Backing DB sees a webshell-pattern stored procedure (LEMURLOOT) or unfamiliar sessions from the vendor app''s account.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-024-RC01', 'SEC-SQL-RAN-024', 'Automated-scanner toolkit signature',
    'ran-024-automated-scanner-toolkit-signature', 'SQLMap, Nuclei, nmap NSE, Burp Suite leave footprints: `application_name` like `sqlmap/1.x.x`, query velocity > 5/sec, distinctive WHERE patterns (`AND 1=1`, `AND SLEEP(N)`, `'' OR ''''=''`).',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-025-RC01', 'SEC-SQL-RAN-025', 'Database Activity Stream / audit-sink tampering',
    'ran-025-database-activity-stream-audit-sink-tampering', 'RDS DAS, Azure SQL audit, Cloud SQL log destinations can be silently disabled or redirected via the cloud control plane.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-026-RC01', 'SEC-SQL-RAN-026', 'Kubernetes DB-operator / CRD tampering',
    'ran-026-kubernetes-db-operator-crd-tampering', 'CloudNativePG, Crunchy PGO, Zalando, Vitess, MongoDB Operator. Spec mutation, sidecar injection, hostPath / PVC tampering, image-tag swap. Detection: Kubernetes-side audit diff against GitOps manifest.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-027-RC01', 'SEC-SQL-RAN-027', 'KMS key-policy / grant tampering',
    'ran-027-kms-key-policy-grant-tampering', '`kms:CreateGrant` + `kms:Decrypt` to an attacker principal = silent decrypt capability for every snapshot. Detection: CloudTrail diff on the DB''s CMK.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-028-RC01', 'SEC-SQL-RAN-028', 'Insider threat — departing-employee or service-account bulk access',
    'ran-028-insider-threat-departing-employee-or-service-account-bulk-ac', 'read rate > 100× baseline. Less an attack signature than a behavior; only baseline-deviation analysis catches it.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-029-RC01', 'SEC-SQL-RAN-029', 'Stale / orphaned account reactivation',
    'ran-029-stale-orphaned-account-reactivation', 'account dormant > 90 days suddenly authenticates. The single highest-yield abandoned-credential signal.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-030-RC01', 'SEC-SQL-RAN-030', 'DB-host outbound DNS / C2 beacon',
    'ran-030-db-host-outbound-dns-c2-beacon', 'Cobalt Strike / Sliver / Havoc default-sleep cadences (30/60/120/300/600 s) + high-entropy subdomain labels from the DB host''s source IP.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-031-RC01', 'SEC-SQL-RAN-031', 'Block-storage / snapshot direct-API access',
    'ran-031-block-storage-snapshot-direct-api-access', 'EBS Direct API (`ebs:GetSnapshotBlock`), Azure managed-disk `beginGetAccess`, GCP persistent-disk copy. Bypasses every DB-side access control. GuardDuty rule: `Exfiltration:EBS/MaliciousIPCaller`.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-032-RC01', 'SEC-SQL-RAN-032', 'Statistics / histogram poisoning',
    'ran-032-statistics-histogram-poisoning', '`ALTER TABLE … ALTER COLUMN … SET STATISTICS 1` makes the planner choose bad plans for the very queries operators rely on for detection. Surveillance queries time out or scan the wrong index.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-033-RC01', 'SEC-SQL-RAN-033', 'Vector database embedding theft / poisoning',
    'ran-033-vector-database-embedding-theft-poisoning', 'Milvus / Pinecone / Chroma / Qdrant / Weaviate (dbExpert already supports all of these). Embeddings cannot be deleted; bulk export = permanent semantic data leak. Hubness-poisoning (arXiv 2602.22427) hijacks RAG retrieval. Chroma April-2026 unpatched SQLi.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-034-RC01', 'SEC-SQL-RAN-034', 'Vector DB collection wipe / index corruption',
    'ran-034-vector-db-collection-wipe-index-corruption', 'same wipe-then-ransom pattern as SQL, applied to vector collections. Recovery requires re-embedding the source corpus — often impossible because the source data was already pseudonymised.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-035-RC01', 'SEC-SQL-RAN-035', 'Audit-trail UPDATE tampering',
    'ran-035-audit-trail-update-tampering', 'smarter attackers UPDATE audit rows rather than delete them (rewrite their actions into someone else''s identity). Invisible without a cryptographic hash chain. Ships with a **proactive playbook** that deploys SHA-256 per-row hash chaining on the customer''s audit table.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-036-RC01', 'SEC-SQL-RAN-036', 'DBA tool / IDE vulnerability',
    'ran-036-dba-tool-ide-vulnerability', 'pgAdmin 2025/2026 CVE chain: CVE-2025-2945 (RCE), CVE-2025-9636 (COOP / account takeover), CVE-2025-12762 (RCE), CVE-2025-13780 (shell bypass), CVE-2026-7815 (SQLi → `COPY TO PROGRAM`). Detection: surfaces every connected IDE''s version from `application_name` and maps to known-CVE ranges.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-037-RC01', 'SEC-SQL-RAN-037', 'AI-agent / LLM-driven anomalous session',
    'ran-037-ai-agent-llm-driven-anomalous-session', 'Microsoft 365 Copilot zero-click prompt injection, Varonis Reprompt attack (Jan 2026), Palo Alto Unit 42 autonomous-cloud-attack research. Detection: per-session object-diversity entropy + application_name signatures (`langchain`, `mcp`, `openai-tools`, `autogen`, `crewai`).',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-038-RC01', 'SEC-SQL-RAN-038', 'Steganographic payload in BLOB columns',
    'ran-038-steganographic-payload-in-blob-columns', '(MITRE T1027.003) — high-entropy headerless BYTEA/VARBINARY rows hiding webshells or staging data inside ostensibly-image columns.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-039-RC01', 'SEC-SQL-RAN-039', 'Session-termination abuse against monitoring',
    'ran-039-session-termination-abuse-against-monitoring', 'attacker calls `pg_terminate_backend` / `KILL <spid>` from a non-admin role to remove the watchdog right before destruction.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-040-RC01', 'SEC-SQL-RAN-040', '`SET ROLE` / impersonation-chain abuse',
    'ran-040-set-role-impersonation-chain-abuse', 'attacker uses native impersonation (`SET ROLE`, `EXECUTE AS`, `BECOME USER`) so the downstream audit attributes the destructive activity to an *innocent* role.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-041-RC01', 'SEC-SQL-RAN-041', 'Forged `application_name` / session-identity spoofing',
    'ran-041-forged-application-name-session-identity-spoofing', '`application_name` is client-supplied. An attacker claiming to be `pg_dump` from outside the documented backup-host range is exposed by cross-referencing app-name with client_addr.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-042-RC01', 'SEC-SQL-RAN-042', 'Database clock / time-zone manipulation',
    'ran-042-database-clock-time-zone-manipulation', 'affects time-based logic bombs (fire early), audit timestamps (misattribution), session-expiry. Detection: drift > 60 s vs trusted reference, or TIMEZONE setting change.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-043-RC01', 'SEC-SQL-RAN-043', 'Weak / legacy password-hash storage',
    'ran-043-weak-legacy-password-hash-storage', 'pg_authid still using `md5`, MySQL `mysql_old_password` / `mysql_native_password`. An attacker who reads the credential table cracks these offline at ~10 GH/s.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-044-RC01', 'SEC-SQL-RAN-044', 'MongoDB `$where` / `$function` server-side JavaScript eval',
    'ran-044-mongodb-where-function-server-side-javascript-eval', 'JS-eval inside the database engine, NoSQL-injection RCE primitive.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-045-RC01', 'SEC-SQL-RAN-045', 'Backup repository / Veeam server compromise',
    'ran-045-backup-repository-veeam-server-compromise', '2026 Veeam CVEs (CVE-2026-21666 / 21667 / 21668) give an authenticated domain user RCE on the backup server or arbitrary file manipulation in the repository. Qilin specifically hits Veeam credential DBs first. Detection: archiver continuity + operator-supplied repo state.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-046-RC01', 'SEC-SQL-RAN-046', 'Application secrets / API tokens stored in DB tables',
    'ran-046-application-secrets-api-tokens-stored-in-db-tables', 'API credential theft is the **#2 cause of breaches in 2026**, behind phishing. Modern apps stash OAuth refresh tokens, JWT signing secrets, encryption keys, webhook secrets in regular DB columns. Once read, the attacker pivots straight to the customer''s cloud/payment/messaging accounts — never has to encrypt anything. Detection: column-name pattern scan + read tracking.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-047-RC01', 'SEC-SQL-RAN-047', 'Untrusted procedural language functions',
    'ran-047-untrusted-procedural-language-functions', 'PL/PythonU, PL/PerlU, PL/TclU, PL/JavaU, Oracle Java with broad permissions, SQL CLR UNSAFE. Each function = permanent OS shell callable via SQL.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-048-RC01', 'SEC-SQL-RAN-048', 'Unpatched critical database CVE',
    'ran-048-unpatched-critical-database-cve', 'version inventory mapped to known-exploited ranges. Current high-priority entries: CVE-2026-2005 (pgcrypto, 20-year heap overflow, CVSS 8.8, ~80% of cloud PostgreSQL affected), CVE-2026-6638 (logical-replication SQL-injection-to-superuser, fixed in PG 18.4 / 17.10 / 16.14 / 15.18 / 14.23), CVE-2026-6476 (pg_createsubscriber, near-9), CVE-2025-8714 (pg_dump code injection), Oracle Jan-2026 CPU cluster, MariaDB CVE-2026-32710, MySQL Jan-2026 CPU (20 patches, 7 remote-no-auth).',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-049-RC01', 'SEC-SQL-RAN-049', 'SQL Server Database Mail / Service Broker abuse',
    'ran-049-sql-server-database-mail-service-broker-abuse', 'Database Mail = outbound-SMTP exfil channel; Service Broker queues = quiet C2. Microsoft documented this exact path in their 2023 SQL-Server-to-cloud-lateral writeup.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-050-RC01', 'SEC-SQL-RAN-050', 'Connection pooler compromise',
    'ran-050-connection-pooler-compromise', 'PgBouncer < 1.25.1 has CVE-2025-12819: unauthenticated SQL injection via the SCRAM startup-message `search_path`. Pre-auth RCE on the front of every PostgreSQL connection. Multiple pre-auth integer-overflow CVEs also crash the pooler with one malformed packet.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-051-RC01', 'SEC-SQL-RAN-051', 'Hostile logical-replication subscription',
    'ran-051-hostile-logical-replication-subscription', 'attacker creates a `pg_subscription` from their own host. Every commit streams to them in real time. CVE-2026-6638 in `ALTER SUBSCRIPTION ... REFRESH PUBLICATION` further auto-escalates to publication-side superuser.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-052-RC01', 'SEC-SQL-RAN-052', 'WAL / redo archive integrity compromise',
    'ran-052-wal-redo-archive-integrity-compromise', 'archive bucket file count drifts from `pg_stat_archiver` counters. Backups exist but PITR fails because the attacker corrupted the archived WAL segments.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-053-RC01', 'SEC-SQL-RAN-053', 'Stored procedure / function body obfuscation',
    'ran-053-stored-procedure-function-body-obfuscation', 'Oracle PL/SQL wrapped via `DBMS_DDL.WRAP`, SQL Server objects created `WITH ENCRYPTION` (definition reads as NULL), PostgreSQL functions whose body is a single base64 blob. Closed-source backdoor inside your database.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-054-RC01', 'SEC-SQL-RAN-054', 'Database-to-cloud lateral movement via IMDS',
    'ran-054-database-to-cloud-lateral-movement-via-imds', 'Microsoft Security Blog (Oct 2023) documented SQL Server → cloud lateral via `xp_cmdshell` + `curl 169.254.169.254`. The DB process pulls IAM role credentials from the instance metadata service and pivots into S3 / KMS / Secrets Manager. Detection: network-flow rule on outbound `169.254.169.254` from the DB host.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-055-RC01', 'SEC-SQL-RAN-055', 'Cloud control-plane surface flip',
    'ran-055-cloud-control-plane-surface-flip', 'RDS/Aurora flipped to `publicly_accessible`, security group opened to 0.0.0.0/0, parameter group edited to disable SSL or `pgaudit.log`. The single most catastrophic managed-DB attack — never touches SQL. Detection via operator-supplied cloud telemetry diff. AWS GuardDuty RDS Protection documents this surface; Coalition''s 2025 Cyber Claims Report puts cloud-credential misuse at 47% of intrusions.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-056-RC01', 'SEC-SQL-RAN-056', 'search_path / schema poisoning',
    'ran-056-search-path-schema-poisoning', 'CVE-2018-1058 family. SECURITY DEFINER function that doesn''t pin its `search_path` gets hijacked by a function the attacker created in a writable schema. Detection: SECURITY DEFINER inventory + public-schema-writability check.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-057-RC01', 'SEC-SQL-RAN-057', 'Malicious extension / trojanized library',
    'ran-057-malicious-extension-trojanized-library', 'PG_MEM-family (Aqua Nautilus 2024; 1,500+ servers compromised by April 2025 per The Hacker News). Brute-force → CREATE SUPERUSER → COPY FROM PROGRAM → cryptominer payload. Detection: extension allow-list diff + backdoor-superuser inventory.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-058-RC01', 'SEC-SQL-RAN-058', 'Out-of-band network exfiltration via DB-internal functions',
    'ran-058-out-of-band-network-exfiltration-via-db-internal-functions', 'Oracle `UTL_HTTP`/`UTL_INADDR` (DNS exfil), PostgreSQL `pgsql-http`/`aws_s3`/`lo_export`, SQL Server `sp_OACreate`+`MSXML2.ServerXMLHTTP` / `xp_smtpsendmail`, MySQL outbound UDFs. The connection originates from the DB process, bypassing all host-network monitoring. UTL_INADDR is the textbook OOB SQL-injection primitive (HackTricks, DBSecWorx).',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-059-RC01', 'SEC-SQL-RAN-059', 'Database configuration tamper',
    'ran-059-database-configuration-tamper', '`ALTER SYSTEM SET ssl=off` / `log_statement=none` / `log_destination=''''` (PostgreSQL); `sp_configure` for `xp_cmdshell`, `Ad Hoc Distributed Queries`, `Ole Automation Procedures` (SQL Server); `audit_trail=NONE` (Oracle). PostgreSQL''s `allow_alter_system` is the only protection and is documented as **not a security mechanism**.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-060-RC01', 'SEC-SQL-RAN-060', 'RLS / compensating-control bypass',
    'ran-060-rls-compensating-control-bypass', 'row-level-security policies dropped, BYPASSRLS granted, dynamic data masking removed, Always Encrypted disabled on PII columns. Red-Gate Simple Talk''s RLS attack series documents the vectors.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-061-RC01', 'SEC-SQL-RAN-061', 'Ransom-DDoS / database resource exhaustion',
    'ran-061-ransom-ddos-database-resource-exhaustion', 'sustained max_connections saturation, fork-bomb queries (`WITH RECURSIVE` infinite, cross-join cartesian, parallel-worker fork), long transactions bloating WAL. DoS as a prelude to or substitute for encryption-based extortion (Cloudflare, NETSCOUT, Wallarm).',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-062-RC01', 'SEC-SQL-RAN-062', 'Object ownership / default privilege poisoning',
    'ran-062-object-ownership-default-privilege-poisoning', '`ALTER TABLE ... OWNER TO` shifts critical objects to an attacker role; `ALTER DEFAULT PRIVILEGES` makes every future table auto-grant to the attacker. Survives single-account credential rotation because the ownership chain itself was modified.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-063-RC01', 'SEC-SQL-RAN-063', 'In-database encryption ransomware',
    'ran-063-in-database-encryption-ransomware', 'attacker uses `pgcrypto` / `AES_ENCRYPT` / `ENCRYPTBYKEY` / `DBMS_CRYPTO` to encrypt application columns in-place with a key only they hold. The disk and backup files look normal; file-level EDR sees nothing. Detection: native-crypto function calls + column-type drift to BYTEA/VARBINARY.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-064-RC01', 'SEC-SQL-RAN-064', 'Logic-bomb / time-bomb persistence',
    'ran-064-logic-bomb-time-bomb-persistence', 'triggers, stored procedures, scheduled jobs (`pg_cron`, `DBMS_SCHEDULER`, SQL Agent, MySQL events) created with destructive bodies and future-only schedules. Survives OS-level remediation entirely. The 2026 wormable XMRig campaign popularized this (The Hacker News).',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-065-RC01', 'SEC-SQL-RAN-065', 'Federation / DBLINK exfiltration',
    'ran-065-federation-dblink-exfiltration', 'attacker creates `postgres_fdw`, dblink, Oracle DBLINK, SQL Server linked server, or MongoDB change-stream pointing at attacker infrastructure. Data ships off-host directly from the DB engine, bypassing host-network monitoring. The PostgreSQL dblink+`COPY FROM` chain is documented as the canonical exfil route (HackTricks, NetSPI, Imperva).',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-066-RC01', 'SEC-SQL-RAN-066', 'Synonym / view redirection backdoor',
    'ran-066-synonym-view-redirection-backdoor', 'attacker creates a synonym or recompiles a view in the application schema so application reads silently bypass attacker rows or are redirected. Application keeps working; operator never sees the persistence layer (SQL Server indexed-view restore-boundary attacks, Red-Gate Simple Talk).',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-067-RC01', 'SEC-SQL-RAN-067', 'Extended stored procedure / CLR DLL backdoor',
    'ran-067-extended-stored-procedure-clr-dll-backdoor', 'Maggie (DCSO 2022), skip-2.0 (Winnti), and Cobalt-Strike SQL backdoors register themselves as `xp_` procedures or UNSAFE CLR assemblies. Hundreds of MSSQL servers backdoored in the 2022 Maggie campaign alone (BleepingComputer).',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-068-RC01', 'SEC-SQL-RAN-068', 'TDE / encryption-key tampering',
    'ran-068-tde-encryption-key-tampering', 'attacker rotates the TDE master key or drops the certificate, making the database unrecoverable. Microsoft Learn documents that TDE-protected DBs cannot be restored without the original certificate. Detection: certificate state + `pvt_key_last_backup_date`.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-069-RC01', 'SEC-SQL-RAN-069', 'Honeytoken / canary-row access (proactive)',
    'ran-069-honeytoken-canary-row-access-proactive', 'dbExpert deploys decoy tables with names like `canary_dbexpert_customers` and `canary_dbexpert_credentials` into operator-blessed schemas. Any read of those rows is a confirmed intruder. CrowdStrike, Acalvio, CounterCraft cite this as the highest-signal SQL-layer detection that exists.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-070-RC01', 'SEC-SQL-RAN-070', 'Anti-forensics — query-history / plan-cache wipe',
    'ran-070-anti-forensics-query-history-plan-cache-wipe', '`DBCC FREEPROCCACHE`, `pg_stat_statements_reset()`, Oracle shared-pool flush, audit-table TRUNCATE. Visibility-suppression immediately before the destructive phase.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-RAN-071-RC01', 'SEC-SQL-RAN-071', 'Geo-velocity / impossible-travel',
    'ran-071-geo-velocity-impossible-travel', 'same login authenticates from two distant geographies within minutes. Catches stolen-credential and session-replay attacks regardless of which tool the attacker uses.',
    ARRAY['ransomware', 'ran'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

-- 2) DETECTION STEPS (per vendor) ------------------------------------------
-- 3) DETECTION PATHS + RESOLUTION (per root cause x vendor) ----------------
DO $gen$
DECLARE
    v_step_id   bigint;
    v_path_id   bigint;
    v_res_step  bigint;
    v_res_path  bigint;
BEGIN
END
$gen$;

-- 4) MONITORING VIEWS (one per root cause) ---------------------------------
CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_001_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-001-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_002_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-002-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_003_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-003-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_004_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-004-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_005_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-005-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_006_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-006-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_007_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-007-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_008_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-008-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_009_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-009-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_010_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-010-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_011_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-011-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_012_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-012-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_013_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-013-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_014_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-014-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_015_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-015-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_016_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-016-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_017_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-017-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_018_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-018-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_019_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-019-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_020_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-020-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_021_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-021-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_022_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-022-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_023_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-023-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_024_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-024-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_025_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-025-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_026_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-026-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_027_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-027-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_028_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-028-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_029_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-029-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_030_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-030-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_031_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-031-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_032_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-032-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_033_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-033-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_034_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-034-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_035_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-035-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_036_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-036-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_037_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-037-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_038_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-038-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_039_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-039-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_040_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-040-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_041_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-041-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_042_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-042-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_043_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-043-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_044_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-044-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_045_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-045-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_046_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-046-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_047_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-047-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_048_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-048-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_049_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-049-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_050_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-050-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_051_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-051-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_052_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-052-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_053_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-053-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_054_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-054-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_055_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-055-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_056_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-056-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_057_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-057-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_058_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-058-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_059_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-059-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_060_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-060-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_061_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-061-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_062_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-062-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_063_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-063-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_064_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-064-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_065_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-065-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_066_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-066-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_067_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-067-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_068_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-068-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_069_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-069-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_070_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-070-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ran_071_rc01 AS
SELECT r.server,
    j.value AS data,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-RAN-071-RC01';

-- 5) VERIFY ----------------------------------------------------------------
SELECT root_cause_id, name, vendors_applicable FROM rootcause.root_causes
 WHERE root_cause_id IN ('SEC-SQL-RAN-001-RC01', 'SEC-SQL-RAN-002-RC01', 'SEC-SQL-RAN-003-RC01', 'SEC-SQL-RAN-004-RC01', 'SEC-SQL-RAN-005-RC01', 'SEC-SQL-RAN-006-RC01', 'SEC-SQL-RAN-007-RC01', 'SEC-SQL-RAN-008-RC01', 'SEC-SQL-RAN-009-RC01', 'SEC-SQL-RAN-010-RC01', 'SEC-SQL-RAN-011-RC01', 'SEC-SQL-RAN-012-RC01', 'SEC-SQL-RAN-013-RC01', 'SEC-SQL-RAN-014-RC01', 'SEC-SQL-RAN-015-RC01', 'SEC-SQL-RAN-016-RC01', 'SEC-SQL-RAN-017-RC01', 'SEC-SQL-RAN-018-RC01', 'SEC-SQL-RAN-019-RC01', 'SEC-SQL-RAN-020-RC01', 'SEC-SQL-RAN-021-RC01', 'SEC-SQL-RAN-022-RC01', 'SEC-SQL-RAN-023-RC01', 'SEC-SQL-RAN-024-RC01', 'SEC-SQL-RAN-025-RC01', 'SEC-SQL-RAN-026-RC01', 'SEC-SQL-RAN-027-RC01', 'SEC-SQL-RAN-028-RC01', 'SEC-SQL-RAN-029-RC01', 'SEC-SQL-RAN-030-RC01', 'SEC-SQL-RAN-031-RC01', 'SEC-SQL-RAN-032-RC01', 'SEC-SQL-RAN-033-RC01', 'SEC-SQL-RAN-034-RC01', 'SEC-SQL-RAN-035-RC01', 'SEC-SQL-RAN-036-RC01', 'SEC-SQL-RAN-037-RC01', 'SEC-SQL-RAN-038-RC01', 'SEC-SQL-RAN-039-RC01', 'SEC-SQL-RAN-040-RC01', 'SEC-SQL-RAN-041-RC01', 'SEC-SQL-RAN-042-RC01', 'SEC-SQL-RAN-043-RC01', 'SEC-SQL-RAN-044-RC01', 'SEC-SQL-RAN-045-RC01', 'SEC-SQL-RAN-046-RC01', 'SEC-SQL-RAN-047-RC01', 'SEC-SQL-RAN-048-RC01', 'SEC-SQL-RAN-049-RC01', 'SEC-SQL-RAN-050-RC01', 'SEC-SQL-RAN-051-RC01', 'SEC-SQL-RAN-052-RC01', 'SEC-SQL-RAN-053-RC01', 'SEC-SQL-RAN-054-RC01', 'SEC-SQL-RAN-055-RC01', 'SEC-SQL-RAN-056-RC01', 'SEC-SQL-RAN-057-RC01', 'SEC-SQL-RAN-058-RC01', 'SEC-SQL-RAN-059-RC01', 'SEC-SQL-RAN-060-RC01', 'SEC-SQL-RAN-061-RC01', 'SEC-SQL-RAN-062-RC01', 'SEC-SQL-RAN-063-RC01', 'SEC-SQL-RAN-064-RC01', 'SEC-SQL-RAN-065-RC01', 'SEC-SQL-RAN-066-RC01', 'SEC-SQL-RAN-067-RC01', 'SEC-SQL-RAN-068-RC01', 'SEC-SQL-RAN-069-RC01', 'SEC-SQL-RAN-070-RC01', 'SEC-SQL-RAN-071-RC01');

COMMIT;
