-- ===========================================================================
-- Auto-generated by gen_rootcause_module.py from specs/insider_threat.json
-- Module: insider_threat   Root causes: 6   Vendors: postgresql, sqlserver, oracle, mysql
-- DO NOT hand-edit; edit the spec and regenerate.
-- ===========================================================================
BEGIN;

-- 1) ROOT CAUSES -----------------------------------------------------------
INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-INS-001-RC01', 'SEC-SQL-INS-001', 'Admin granting privileges to themselves (self-grant)',
    'insider-self-grant', 'A role was granted membership/privileges by itself (grantor = member). Self-granted privileges are a hallmark of privilege abuse by an insider who already holds elevated rights.',
    ARRAY['insider', 'privilege abuse', 'self-grant', 'least-privilege', 'pci-dss'], ARRAY['postgresql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-INS-003-RC01', 'SEC-SQL-INS-003', 'Excessive number of superusers',
    'insider-excessive-superusers', 'More principals hold superuser/sysadmin than a least-privilege posture warrants. A large superuser population widens the insider-abuse blast radius and is hard to monitor.',
    ARRAY['insider', 'superuser', 'least-privilege', 'attack surface'], ARRAY['postgresql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-INS-012-RC01', 'SEC-SQL-INS-012', 'Off-hours privileged sessions',
    'insider-off-hours-admin', 'Superuser/admin sessions started outside business hours (before 07:00 or at/after 19:00 server time). Off-hours admin activity is a common insider-abuse indicator and should be paired with another signal before alerting.',
    ARRAY['insider', 'off-hours', 'privileged session', 'ueba'], ARRAY['postgresql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-INS-004-RC01', 'SEC-SQL-INS-004', 'Separation-of-duties violation',
    'insider-sod-violation', 'A principal holds both sides of an operator-defined conflict pair (e.g., can both create payments and approve them). Requires the customer''s SoD conflict matrix as an operator-supplied feed.',
    ARRAY['insider', 'separation of duties', 'sod', 'compliance'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-INS-010-RC01', 'SEC-SQL-INS-010', 'Privileged access to objects outside role baseline',
    'insider-object-access-outside-baseline', 'A DBA/privileged user read objects outside their per-principal expected-object baseline. Requires an audit trail (pgAudit / SQL Server Audit / Oracle Unified Audit) plus the per-principal baseline as operator feeds.',
    ARRAY['insider', 'audit', 'object access', 'baseline', 'ueba'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-INS-015-RC01', 'SEC-SQL-INS-015', 'Pre-departure mass extraction',
    'insider-pre-departure-extraction', 'Rows-read by a user spiked versus their personal baseline while they appear in the offboarding feed (resignation/notice). Requires per-user access stats + an HR/IDP offboarding feed as operator inputs.',
    ARRAY['insider', 'data exfiltration', 'offboarding', 'pre-departure', 'baseline'], ARRAY['postgresql', 'sqlserver', 'oracle', 'mysql']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

-- 2) DETECTION STEPS (per vendor) ------------------------------------------
INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('postgresql', 'query', 'Detect SEC-SQL-INS-001-RC01 (postgresql)',
        '{"sql": "SELECT g.rolname AS grantor, m.rolname AS member, r.rolname AS granted_role FROM pg_auth_members am JOIN pg_roles g ON g.oid = am.grantor JOIN pg_roles m ON m.oid = am.member JOIN pg_roles r ON r.oid = am.roleid WHERE am.grantor = am.member ORDER BY m.rolname"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Role membership rows where the grantor is also the member"}'::jsonb);

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('postgresql', 'query', 'Detect SEC-SQL-INS-003-RC01 (postgresql)',
        '{"sql": "SELECT rolname, rolcanlogin FROM pg_roles WHERE rolsuper ORDER BY rolname"}'::jsonb,
        '{"condition": "row_count > 3", "description": "Superuser roles (alert when more than the per-customer threshold)"}'::jsonb);

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('postgresql', 'query', 'Detect SEC-SQL-INS-012-RC01 (postgresql)',
        '{"sql": "SELECT sa.usename, host(sa.client_addr) AS client_addr, sa.backend_start, sa.state FROM pg_stat_activity sa JOIN pg_roles r ON r.rolname = sa.usename WHERE r.rolsuper AND sa.backend_start IS NOT NULL AND (extract(hour FROM sa.backend_start) < 7 OR extract(hour FROM sa.backend_start) >= 19) ORDER BY sa.backend_start DESC"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Superuser sessions opened outside business hours"}'::jsonb);

-- 3) DETECTION PATHS + RESOLUTION (per root cause x vendor) ----------------
DO $gen$
DECLARE
    v_step_id   bigint;
    v_path_id   bigint;
    v_res_step  bigint;
    v_res_path  bigint;
BEGIN
    -- SEC-SQL-INS-001-RC01 / postgresql
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'postgresql' AND name = 'Detect SEC-SQL-INS-001-RC01 (postgresql)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-INS-001-RC01', 'postgresql', 'Detect SEC-SQL-INS-001-RC01 (postgresql)', 'Admin granting privileges to themselves (self-grant)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('postgresql', 'recommendation', 'Resolve: Detect SEC-SQL-INS-001-RC01 (postgresql)', '{"action": "Review the self-granted role membership. Revoke privileges that were not approved through change control, and require all grants to go through a separate approver (separation of duties)."}'::jsonb, 'high', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-INS-001-RC01', 'postgresql', 'Resolve: Detect SEC-SQL-INS-001-RC01 (postgresql)', 'resolve-sec_sql_ins_001_rc01-postgresql', 'Review the self-granted role membership. Revoke privileges that were not approved through change control, and require all grants to go through a separate approver (separation of duties).', 'supervised', 'high', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-INS-003-RC01 / postgresql
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'postgresql' AND name = 'Detect SEC-SQL-INS-003-RC01 (postgresql)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-INS-003-RC01', 'postgresql', 'Detect SEC-SQL-INS-003-RC01 (postgresql)', 'Excessive number of superusers', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('postgresql', 'recommendation', 'Resolve: Detect SEC-SQL-INS-003-RC01 (postgresql)', '{"action": "Review every superuser. Remove standing superuser from accounts that don''t need it; prefer time-boxed elevation (break-glass) with auditing. Tune the acceptable count per environment."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-INS-003-RC01', 'postgresql', 'Resolve: Detect SEC-SQL-INS-003-RC01 (postgresql)', 'resolve-sec_sql_ins_003_rc01-postgresql', 'Review every superuser. Remove standing superuser from accounts that don''t need it; prefer time-boxed elevation (break-glass) with auditing. Tune the acceptable count per environment.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-INS-012-RC01 / postgresql
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'postgresql' AND name = 'Detect SEC-SQL-INS-012-RC01 (postgresql)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-INS-012-RC01', 'postgresql', 'Detect SEC-SQL-INS-012-RC01 (postgresql)', 'Off-hours privileged sessions', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('postgresql', 'recommendation', 'Resolve: Detect SEC-SQL-INS-012-RC01 (postgresql)', '{"action": "Correlate off-hours superuser sessions with change tickets / on-call schedules. Investigate any session with no corresponding approved activity. Tune the business-hours window per customer."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-INS-012-RC01', 'postgresql', 'Resolve: Detect SEC-SQL-INS-012-RC01 (postgresql)', 'resolve-sec_sql_ins_012_rc01-postgresql', 'Correlate off-hours superuser sessions with change tickets / on-call schedules. Investigate any session with no corresponding approved activity. Tune the business-hours window per customer.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
END
$gen$;

-- 4) MONITORING VIEWS (one per root cause) ---------------------------------
CREATE OR REPLACE VIEW monitoring.v_sec_sql_ins_001_rc01 AS
SELECT r.server,
    (j.value ->> 'grantor') AS grantor,
    (j.value ->> 'member') AS member,
    (j.value ->> 'granted_role') AS granted_role,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-INS-001-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ins_003_rc01 AS
SELECT r.server,
    (j.value ->> 'rolname') AS rolname,
    (j.value ->> 'rolcanlogin') AS rolcanlogin,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-INS-003-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ins_012_rc01 AS
SELECT r.server,
    (j.value ->> 'usename') AS usename,
    (j.value ->> 'client_addr') AS client_addr,
    (j.value ->> 'backend_start') AS backend_start,
    (j.value ->> 'state') AS state,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-INS-012-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ins_004_rc01 AS
SELECT r.server,
    (j.value ->> 'principal') AS principal,
    (j.value ->> 'conflict_pair') AS conflict_pair,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-INS-004-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ins_010_rc01 AS
SELECT r.server,
    (j.value ->> 'principal') AS principal,
    (j.value ->> 'object_name') AS object_name,
    (j.value ->> 'access_time') AS access_time,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-INS-010-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_ins_015_rc01 AS
SELECT r.server,
    (j.value ->> 'principal') AS principal,
    (j.value ->> 'rows_read') AS rows_read,
    (j.value ->> 'baseline') AS baseline,
    (j.value ->> 'departure_date') AS departure_date,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-INS-015-RC01';

-- 5) VERIFY ----------------------------------------------------------------
SELECT root_cause_id, name, vendors_applicable FROM rootcause.root_causes
 WHERE root_cause_id IN ('SEC-SQL-INS-001-RC01', 'SEC-SQL-INS-003-RC01', 'SEC-SQL-INS-012-RC01', 'SEC-SQL-INS-004-RC01', 'SEC-SQL-INS-010-RC01', 'SEC-SQL-INS-015-RC01');

COMMIT;
