-- monitoring.v_all_active_transactions: UNION ALL of every view returning transactions
-- (v_active_transactions + all root-cause transaction views). Unix-epoch time columns
-- are converted to timestamp; all columns unified to text (entry_date kept as timestamp).
--
-- Rebuilt here after 1055 CASCADE-drops this view to change
-- v_sec_sql_acc_011_rc02.transaction_begin_time to timestamptz. The start_time CASE
-- below already tolerates both text-epoch and a real timestamp, so no logic change
-- is needed - this comment exists to bump the checksum so the ledger re-applies it.
CREATE OR REPLACE VIEW monitoring.v_all_active_transactions AS
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, (host_name)::text AS host_name, (database_name)::text AS database_name, (status)::text AS status, CASE WHEN (start_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((start_time)::text::double precision / CASE WHEN length((start_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (start_time)::text END AS start_time, (command)::text AS command, (cpu_time)::text AS cpu_time, (total_elapsed_time)::text AS total_elapsed_time, (query)::text AS query, entry_date, 'v_active_transactions'::text AS source
FROM monitoring.v_active_transactions
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, (host_name)::text AS host_name, NULL::text AS database_name, (status)::text AS status, CASE WHEN (start_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((start_time)::text::double precision / CASE WHEN length((start_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (start_time)::text END AS start_time, (command)::text AS command, (cpu_time)::text AS cpu_time, (total_elapsed_time)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_long_block_transactions'::text AS source
FROM monitoring.v_long_block_transactions
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, (host_name)::text AS host_name, NULL::text AS database_name, NULL::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, NULL::text AS command, NULL::text AS cpu_time, NULL::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_cn_002_rc12'::text AS source
FROM monitoring.v_perf_sql_cn_002_rc12
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, (host_name)::text AS host_name, (database_name)::text AS database_name, NULL::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, NULL::text AS command, NULL::text AS cpu_time, (duration_sec)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_cpu_001_rc19'::text AS source
FROM monitoring.v_perf_sql_cpu_001_rc19
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, NULL::text AS host_name, NULL::text AS database_name, NULL::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, NULL::text AS command, NULL::text AS cpu_time, (duration_sec)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_io_004_rc16'::text AS source
FROM monitoring.v_perf_sql_io_004_rc16
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, (host_name)::text AS host_name, NULL::text AS database_name, NULL::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, NULL::text AS command, NULL::text AS cpu_time, (duration_seconds)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_lc_001_rc02'::text AS source
FROM monitoring.v_perf_sql_lc_001_rc02
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, NULL::text AS login_name, (host_name)::text AS host_name, NULL::text AS database_name, NULL::text AS status, NULL::text AS start_time, NULL::text AS command, NULL::text AS cpu_time, (duration_sec)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_lc_001_rc13'::text AS source
FROM monitoring.v_perf_sql_lc_001_rc13
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, NULL::text AS login_name, (host_name)::text AS host_name, NULL::text AS database_name, NULL::text AS status, NULL::text AS start_time, NULL::text AS command, (cpu_time)::text AS cpu_time, (txn_duration_sec)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_lc_002_rc10'::text AS source
FROM monitoring.v_perf_sql_lc_002_rc10
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, (host_name)::text AS host_name, NULL::text AS database_name, (transaction_state)::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, NULL::text AS command, NULL::text AS cpu_time, (duration_seconds)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_lc_003_rc01'::text AS source
FROM monitoring.v_perf_sql_lc_003_rc01
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, (host_name)::text AS host_name, NULL::text AS database_name, NULL::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, (command)::text AS command, NULL::text AS cpu_time, (duration_sec)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_lc_005_rc01'::text AS source
FROM monitoring.v_perf_sql_lc_005_rc01
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, NULL::text AS login_name, NULL::text AS host_name, NULL::text AS database_name, NULL::text AS status, NULL::text AS start_time, NULL::text AS command, NULL::text AS cpu_time, (duration_sec)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_mem_001_rc11'::text AS source
FROM monitoring.v_perf_sql_mem_001_rc11
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, (host_name)::text AS host_name, NULL::text AS database_name, NULL::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, (command)::text AS command, NULL::text AS cpu_time, (duration_sec)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_tx_001_rc03'::text AS source
FROM monitoring.v_perf_sql_tx_001_rc03
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, (host_name)::text AS host_name, NULL::text AS database_name, NULL::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, (command)::text AS command, NULL::text AS cpu_time, (duration_sec)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_tx_001_rc05'::text AS source
FROM monitoring.v_perf_sql_tx_001_rc05
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, (host_name)::text AS host_name, NULL::text AS database_name, NULL::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, (command)::text AS command, NULL::text AS cpu_time, (duration_sec)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_tx_001_rc07'::text AS source
FROM monitoring.v_perf_sql_tx_001_rc07
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, (host_name)::text AS host_name, NULL::text AS database_name, NULL::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, (command)::text AS command, NULL::text AS cpu_time, (duration_sec)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_tx_001_rc09'::text AS source
FROM monitoring.v_perf_sql_tx_001_rc09
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, (host_name)::text AS host_name, NULL::text AS database_name, NULL::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, (command)::text AS command, NULL::text AS cpu_time, (duration_sec)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_tx_001_rc11'::text AS source
FROM monitoring.v_perf_sql_tx_001_rc11
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, (host_name)::text AS host_name, NULL::text AS database_name, NULL::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, NULL::text AS command, NULL::text AS cpu_time, NULL::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_perf_sql_tx_002_rc01'::text AS source
FROM monitoring.v_perf_sql_tx_002_rc01
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, NULL::text AS login_name, NULL::text AS host_name, NULL::text AS database_name, NULL::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, NULL::text AS command, NULL::text AS cpu_time, (duration_seconds)::text AS total_elapsed_time, NULL::text AS query, entry_date, 'v_sec_sql_acc_010_rc13'::text AS source
FROM monitoring.v_sec_sql_acc_010_rc13
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, (host_name)::text AS host_name, (database_name)::text AS database_name, (transaction_state)::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, NULL::text AS command, NULL::text AS cpu_time, (duration_seconds)::text AS total_elapsed_time, (query_text)::text AS query, entry_date, 'v_sec_sql_acc_011_rc02'::text AS source
FROM monitoring.v_sec_sql_acc_011_rc02
UNION ALL
SELECT (server)::text AS server, (session_id)::text AS session_id, (transaction_id)::text AS transaction_id, (login_name)::text AS login_name, NULL::text AS host_name, NULL::text AS database_name, NULL::text AS status, CASE WHEN (transaction_begin_time)::text ~ '^[0-9]{9,}$' THEN to_timestamp((transaction_begin_time)::text::double precision / CASE WHEN length((transaction_begin_time)::text) >= 13 THEN 1000 ELSE 1 END)::text ELSE (transaction_begin_time)::text END AS start_time, NULL::text AS command, NULL::text AS cpu_time, NULL::text AS total_elapsed_time, (query_text)::text AS query, entry_date, 'v_sec_sql_pri_001_rc15'::text AS source
FROM monitoring.v_sec_sql_pri_001_rc15
