-- ============================================================
-- 6260  Destructive DDL/DML audit-trail detections (SQL Server + Oracle)
--   Issue SEC-SQL-AUD-020 with 4 root causes:
--     RC01 drop database/schema (critical), RC02 drop table (high),
--     RC03 drop user/role (critical),        RC04 delete/truncate data (high)
--   SQL Server reads live activity + plan cache (sys.dm_exec_requests /
--   dm_exec_query_stats -> dm_exec_sql_text), modeled on SEC-SQL-ACC-011-RC02 —
--   resilient, no SQL Server Audit dependency (avoids the fn_get_audit_file 33224
--   error when no audit file exists). Oracle reads UNIFIED_AUDIT_TRAIL (a view,
--   returns no rows when unified auditing is off).
--   Auto-generated via gen_rootcause_module.py; edit the spec + regenerate.
-- ============================================================

-- ===========================================================================
-- Auto-generated by gen_rootcause_module.py from specs/destructive_ddl_audit.json
-- Module: destructive_ddl_audit   Root causes: 4   Vendors: sqlserver, oracle
-- DO NOT hand-edit; edit the spec and regenerate.
-- ===========================================================================
BEGIN;

-- 0) ISSUE (generator does not create issues) ------------------------------
INSERT INTO rootcause.issues
    (issue_id, domain_code, database_type_code, area_code, name, slug, description, created_at, updated_at)
VALUES (
    'SEC-SQL-AUD-020', 'SEC', 'SQL', 'AUD',
    'Destructive DDL/DML detected via audit trail',
    'destructive-ddl-dml-audit',
    'Audit-trail detections for high-impact destructive operations: dropping a database/schema, table, or user/role, and deleting/truncating table data.',
    now(), now())
ON CONFLICT (issue_id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;


-- 1) ROOT CAUSES -----------------------------------------------------------
INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-AUD-020-RC01', 'SEC-SQL-AUD-020', 'Database or schema dropped (audit trail)',
    'audit-drop-database', 'A DROP DATABASE / DROP SCHEMA (SQL Server) or DROP PLUGGABLE DATABASE / DROP TABLESPACE (Oracle) was recorded in the audit trail within the last 24 hours.',
    ARRAY['audit', 'ddl', 'drop-database', 'data-loss'], ARRAY['sqlserver', 'oracle']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-AUD-020-RC02', 'SEC-SQL-AUD-020', 'Table dropped (audit trail)',
    'audit-drop-table', 'A DROP TABLE statement was recorded in the audit trail within the last 24 hours, on any table.',
    ARRAY['audit', 'ddl', 'drop-table', 'data-loss'], ARRAY['sqlserver', 'oracle']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-AUD-020-RC03', 'SEC-SQL-AUD-020', 'User, login or role dropped (audit trail)',
    'audit-drop-user', 'A DROP USER / DROP LOGIN / DROP ROLE statement was recorded in the audit trail within the last 24 hours.',
    ARRAY['audit', 'ddl', 'drop-user', 'access-control'], ARRAY['sqlserver', 'oracle']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-AUD-020-RC04', 'SEC-SQL-AUD-020', 'Data deleted from a table (audit trail)',
    'audit-delete-data', 'A DELETE or TRUNCATE TABLE statement was recorded in the audit trail within the last 24 hours, on any table.',
    ARRAY['audit', 'dml', 'delete', 'truncate', 'data-loss'], ARRAY['sqlserver', 'oracle']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

-- 2) DETECTION STEPS (per vendor) ------------------------------------------
INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('sqlserver', 'query', 'Detect SEC-SQL-AUD-020-RC01 (sqlserver)',
        '{"sql": "SELECT TOP 500 CAST(GETDATE() AS DATETIME) AS event_time, s.login_name AS login_name,\n       DB_NAME(r.database_id) AS database_name, CAST(NULL AS NVARCHAR(128)) AS object_name,\n       CAST(qt.text AS NVARCHAR(MAX)) AS statement\nFROM sys.dm_exec_requests AS r WITH (NOLOCK)\nJOIN sys.dm_exec_sessions AS s WITH (NOLOCK) ON s.session_id = r.session_id\nOUTER APPLY sys.dm_exec_sql_text(r.sql_handle) AS qt\nWHERE s.session_id <> @@SPID AND ISNULL(s.login_name,'''') NOT LIKE ''%dbdome%''\n  AND qt.text IS NOT NULL AND (qt.text LIKE ''%DROP%DATABASE%'' OR qt.text LIKE ''%DROP%SCHEMA%'')\nUNION ALL\nSELECT TOP 500 qs.last_execution_time AS event_time, CAST(NULL AS NVARCHAR(128)) AS login_name,\n       DB_NAME(st.dbid) AS database_name, CAST(NULL AS NVARCHAR(128)) AS object_name,\n       CAST(st.text AS NVARCHAR(MAX)) AS statement\nFROM sys.dm_exec_query_stats AS qs WITH (NOLOCK)\nOUTER APPLY sys.dm_exec_sql_text(qs.sql_handle) AS st\nWHERE qs.last_execution_time >= DATEADD(DAY,-1, GETDATE())\n  AND st.text IS NOT NULL AND st.text NOT LIKE ''%dm_exec_query_stats%''\n  AND (st.text LIKE ''%DROP%DATABASE%'' OR st.text LIKE ''%DROP%SCHEMA%'')"}'::jsonb,
        '{"condition": "row_count > 0", "description": "A database/schema drop is present in the audit trail (last 24h)."}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('oracle', 'query', 'Detect SEC-SQL-AUD-020-RC01 (oracle)',
        '{"sql": "SELECT event_timestamp AS event_time, dbusername AS login_name, object_schema AS database_name, object_name, sql_text AS statement\nFROM unified_audit_trail\nWHERE event_timestamp > SYSTIMESTAMP - INTERVAL ''1'' DAY\n  AND (action_name IN (''DROP PLUGGABLE DATABASE'',''DROP TABLESPACE'') OR UPPER(sql_text) LIKE ''%DROP DATABASE%'')\nORDER BY event_timestamp DESC FETCH FIRST 500 ROWS ONLY"}'::jsonb,
        '{"condition": "row_count > 0", "description": "A database/schema drop is present in the audit trail (last 24h)."}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('sqlserver', 'query', 'Detect SEC-SQL-AUD-020-RC02 (sqlserver)',
        '{"sql": "SELECT TOP 500 CAST(GETDATE() AS DATETIME) AS event_time, s.login_name AS login_name,\n       DB_NAME(r.database_id) AS database_name, CAST(NULL AS NVARCHAR(128)) AS object_name,\n       CAST(qt.text AS NVARCHAR(MAX)) AS statement\nFROM sys.dm_exec_requests AS r WITH (NOLOCK)\nJOIN sys.dm_exec_sessions AS s WITH (NOLOCK) ON s.session_id = r.session_id\nOUTER APPLY sys.dm_exec_sql_text(r.sql_handle) AS qt\nWHERE s.session_id <> @@SPID AND ISNULL(s.login_name,'''') NOT LIKE ''%dbdome%''\n  AND qt.text IS NOT NULL AND (qt.text LIKE ''%DROP%TABLE%'')\nUNION ALL\nSELECT TOP 500 qs.last_execution_time AS event_time, CAST(NULL AS NVARCHAR(128)) AS login_name,\n       DB_NAME(st.dbid) AS database_name, CAST(NULL AS NVARCHAR(128)) AS object_name,\n       CAST(st.text AS NVARCHAR(MAX)) AS statement\nFROM sys.dm_exec_query_stats AS qs WITH (NOLOCK)\nOUTER APPLY sys.dm_exec_sql_text(qs.sql_handle) AS st\nWHERE qs.last_execution_time >= DATEADD(DAY,-1, GETDATE())\n  AND st.text IS NOT NULL AND st.text NOT LIKE ''%dm_exec_query_stats%''\n  AND (st.text LIKE ''%DROP%TABLE%'')"}'::jsonb,
        '{"condition": "row_count > 0", "description": "A DROP TABLE is present in the audit trail (last 24h)."}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('oracle', 'query', 'Detect SEC-SQL-AUD-020-RC02 (oracle)',
        '{"sql": "SELECT event_timestamp AS event_time, dbusername AS login_name, object_schema AS database_name, object_name, sql_text AS statement\nFROM unified_audit_trail\nWHERE event_timestamp > SYSTIMESTAMP - INTERVAL ''1'' DAY\n  AND (action_name = ''DROP TABLE'')\nORDER BY event_timestamp DESC FETCH FIRST 500 ROWS ONLY"}'::jsonb,
        '{"condition": "row_count > 0", "description": "A DROP TABLE is present in the audit trail (last 24h)."}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('sqlserver', 'query', 'Detect SEC-SQL-AUD-020-RC03 (sqlserver)',
        '{"sql": "SELECT TOP 500 CAST(GETDATE() AS DATETIME) AS event_time, s.login_name AS login_name,\n       DB_NAME(r.database_id) AS database_name, CAST(NULL AS NVARCHAR(128)) AS object_name,\n       CAST(qt.text AS NVARCHAR(MAX)) AS statement\nFROM sys.dm_exec_requests AS r WITH (NOLOCK)\nJOIN sys.dm_exec_sessions AS s WITH (NOLOCK) ON s.session_id = r.session_id\nOUTER APPLY sys.dm_exec_sql_text(r.sql_handle) AS qt\nWHERE s.session_id <> @@SPID AND ISNULL(s.login_name,'''') NOT LIKE ''%dbdome%''\n  AND qt.text IS NOT NULL AND (qt.text LIKE ''%DROP%LOGIN%'' OR qt.text LIKE ''%DROP%USER%'' OR qt.text LIKE ''%DROP%ROLE%'')\nUNION ALL\nSELECT TOP 500 qs.last_execution_time AS event_time, CAST(NULL AS NVARCHAR(128)) AS login_name,\n       DB_NAME(st.dbid) AS database_name, CAST(NULL AS NVARCHAR(128)) AS object_name,\n       CAST(st.text AS NVARCHAR(MAX)) AS statement\nFROM sys.dm_exec_query_stats AS qs WITH (NOLOCK)\nOUTER APPLY sys.dm_exec_sql_text(qs.sql_handle) AS st\nWHERE qs.last_execution_time >= DATEADD(DAY,-1, GETDATE())\n  AND st.text IS NOT NULL AND st.text NOT LIKE ''%dm_exec_query_stats%''\n  AND (st.text LIKE ''%DROP%LOGIN%'' OR st.text LIKE ''%DROP%USER%'' OR st.text LIKE ''%DROP%ROLE%'')"}'::jsonb,
        '{"condition": "row_count > 0", "description": "A user/login/role drop is present in the audit trail (last 24h)."}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('oracle', 'query', 'Detect SEC-SQL-AUD-020-RC03 (oracle)',
        '{"sql": "SELECT event_timestamp AS event_time, dbusername AS login_name, object_schema AS database_name, object_name, sql_text AS statement\nFROM unified_audit_trail\nWHERE event_timestamp > SYSTIMESTAMP - INTERVAL ''1'' DAY\n  AND (action_name IN (''DROP USER'',''DROP ROLE''))\nORDER BY event_timestamp DESC FETCH FIRST 500 ROWS ONLY"}'::jsonb,
        '{"condition": "row_count > 0", "description": "A user/login/role drop is present in the audit trail (last 24h)."}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('sqlserver', 'query', 'Detect SEC-SQL-AUD-020-RC04 (sqlserver)',
        '{"sql": "SELECT TOP 500 CAST(GETDATE() AS DATETIME) AS event_time, s.login_name AS login_name,\n       DB_NAME(r.database_id) AS database_name, CAST(NULL AS NVARCHAR(128)) AS object_name,\n       CAST(qt.text AS NVARCHAR(MAX)) AS statement\nFROM sys.dm_exec_requests AS r WITH (NOLOCK)\nJOIN sys.dm_exec_sessions AS s WITH (NOLOCK) ON s.session_id = r.session_id\nOUTER APPLY sys.dm_exec_sql_text(r.sql_handle) AS qt\nWHERE s.session_id <> @@SPID AND ISNULL(s.login_name,'''') NOT LIKE ''%dbdome%''\n  AND qt.text IS NOT NULL AND (qt.text LIKE ''%DELETE%'' OR qt.text LIKE ''%TRUNCATE%TABLE%'')\nUNION ALL\nSELECT TOP 500 qs.last_execution_time AS event_time, CAST(NULL AS NVARCHAR(128)) AS login_name,\n       DB_NAME(st.dbid) AS database_name, CAST(NULL AS NVARCHAR(128)) AS object_name,\n       CAST(st.text AS NVARCHAR(MAX)) AS statement\nFROM sys.dm_exec_query_stats AS qs WITH (NOLOCK)\nOUTER APPLY sys.dm_exec_sql_text(qs.sql_handle) AS st\nWHERE qs.last_execution_time >= DATEADD(DAY,-1, GETDATE())\n  AND st.text IS NOT NULL AND st.text NOT LIKE ''%dm_exec_query_stats%''\n  AND (st.text LIKE ''%DELETE%'' OR st.text LIKE ''%TRUNCATE%TABLE%'')"}'::jsonb,
        '{"condition": "row_count > 0", "description": "A DELETE/TRUNCATE is present in the audit trail (last 24h)."}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('oracle', 'query', 'Detect SEC-SQL-AUD-020-RC04 (oracle)',
        '{"sql": "SELECT event_timestamp AS event_time, dbusername AS login_name, object_schema AS database_name, object_name, sql_text AS statement\nFROM unified_audit_trail\nWHERE event_timestamp > SYSTIMESTAMP - INTERVAL ''1'' DAY\n  AND (action_name IN (''DELETE'',''TRUNCATE TABLE''))\nORDER BY event_timestamp DESC FETCH FIRST 500 ROWS ONLY"}'::jsonb,
        '{"condition": "row_count > 0", "description": "A DELETE/TRUNCATE is present in the audit trail (last 24h)."}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

-- 3) DETECTION PATHS + RESOLUTION (per root cause x vendor) ----------------
DO $gen$
DECLARE
    v_step_id   bigint;
    v_path_id   bigint;
    v_res_step  bigint;
    v_res_path  bigint;
BEGIN
    -- SEC-SQL-AUD-020-RC01 / sqlserver
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'sqlserver' AND name = 'Detect SEC-SQL-AUD-020-RC01 (sqlserver)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-020-RC01' AND vendor_slug = 'sqlserver') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-020-RC01', 'sqlserver', 'Detect SEC-SQL-AUD-020-RC01 (sqlserver)', 'Database or schema dropped (audit trail)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('sqlserver', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-020-RC01 (sqlserver)', '{"action": "Confirm the drop was authorised (change ticket). If not, isolate the principal, revoke its privileges, and restore the database/schema from backup. Verify the audit policy still captures DDL."}'::jsonb, 'critical', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-020-RC01', 'sqlserver', 'Resolve: Detect SEC-SQL-AUD-020-RC01 (sqlserver)', 'resolve-sec_sql_aud_020_rc01-sqlserver', 'Confirm the drop was authorised (change ticket). If not, isolate the principal, revoke its privileges, and restore the database/schema from backup. Verify the audit policy still captures DDL.', 'supervised', 'critical', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-020-RC01 / oracle
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'oracle' AND name = 'Detect SEC-SQL-AUD-020-RC01 (oracle)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-020-RC01' AND vendor_slug = 'oracle') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-020-RC01', 'oracle', 'Detect SEC-SQL-AUD-020-RC01 (oracle)', 'Database or schema dropped (audit trail)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('oracle', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-020-RC01 (oracle)', '{"action": "Confirm the drop was authorised (change ticket). If not, isolate the principal, revoke its privileges, and restore the database/schema from backup. Verify the audit policy still captures DDL."}'::jsonb, 'critical', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-020-RC01', 'oracle', 'Resolve: Detect SEC-SQL-AUD-020-RC01 (oracle)', 'resolve-sec_sql_aud_020_rc01-oracle', 'Confirm the drop was authorised (change ticket). If not, isolate the principal, revoke its privileges, and restore the database/schema from backup. Verify the audit policy still captures DDL.', 'supervised', 'critical', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-020-RC02 / sqlserver
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'sqlserver' AND name = 'Detect SEC-SQL-AUD-020-RC02 (sqlserver)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-020-RC02' AND vendor_slug = 'sqlserver') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-020-RC02', 'sqlserver', 'Detect SEC-SQL-AUD-020-RC02 (sqlserver)', 'Table dropped (audit trail)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('sqlserver', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-020-RC02 (sqlserver)', '{"action": "Confirm the table drop was authorised. If not, restore the table from backup or a recycle-bin/flashback, identify the principal, and review its DDL privileges."}'::jsonb, 'high', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-020-RC02', 'sqlserver', 'Resolve: Detect SEC-SQL-AUD-020-RC02 (sqlserver)', 'resolve-sec_sql_aud_020_rc02-sqlserver', 'Confirm the table drop was authorised. If not, restore the table from backup or a recycle-bin/flashback, identify the principal, and review its DDL privileges.', 'supervised', 'high', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-020-RC02 / oracle
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'oracle' AND name = 'Detect SEC-SQL-AUD-020-RC02 (oracle)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-020-RC02' AND vendor_slug = 'oracle') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-020-RC02', 'oracle', 'Detect SEC-SQL-AUD-020-RC02 (oracle)', 'Table dropped (audit trail)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('oracle', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-020-RC02 (oracle)', '{"action": "Confirm the table drop was authorised. If not, restore the table from backup or a recycle-bin/flashback, identify the principal, and review its DDL privileges."}'::jsonb, 'high', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-020-RC02', 'oracle', 'Resolve: Detect SEC-SQL-AUD-020-RC02 (oracle)', 'resolve-sec_sql_aud_020_rc02-oracle', 'Confirm the table drop was authorised. If not, restore the table from backup or a recycle-bin/flashback, identify the principal, and review its DDL privileges.', 'supervised', 'high', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-020-RC03 / sqlserver
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'sqlserver' AND name = 'Detect SEC-SQL-AUD-020-RC03 (sqlserver)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-020-RC03' AND vendor_slug = 'sqlserver') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-020-RC03', 'sqlserver', 'Detect SEC-SQL-AUD-020-RC03 (sqlserver)', 'User, login or role dropped (audit trail)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('sqlserver', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-020-RC03 (sqlserver)', '{"action": "Confirm the account/role drop was authorised (de-provisioning ticket). If not, recreate the principal and its grants from your IAM baseline, and investigate the actor."}'::jsonb, 'critical', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-020-RC03', 'sqlserver', 'Resolve: Detect SEC-SQL-AUD-020-RC03 (sqlserver)', 'resolve-sec_sql_aud_020_rc03-sqlserver', 'Confirm the account/role drop was authorised (de-provisioning ticket). If not, recreate the principal and its grants from your IAM baseline, and investigate the actor.', 'supervised', 'critical', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-020-RC03 / oracle
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'oracle' AND name = 'Detect SEC-SQL-AUD-020-RC03 (oracle)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-020-RC03' AND vendor_slug = 'oracle') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-020-RC03', 'oracle', 'Detect SEC-SQL-AUD-020-RC03 (oracle)', 'User, login or role dropped (audit trail)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('oracle', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-020-RC03 (oracle)', '{"action": "Confirm the account/role drop was authorised (de-provisioning ticket). If not, recreate the principal and its grants from your IAM baseline, and investigate the actor."}'::jsonb, 'critical', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-020-RC03', 'oracle', 'Resolve: Detect SEC-SQL-AUD-020-RC03 (oracle)', 'resolve-sec_sql_aud_020_rc03-oracle', 'Confirm the account/role drop was authorised (de-provisioning ticket). If not, recreate the principal and its grants from your IAM baseline, and investigate the actor.', 'supervised', 'critical', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-020-RC04 / sqlserver
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'sqlserver' AND name = 'Detect SEC-SQL-AUD-020-RC04 (sqlserver)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-020-RC04' AND vendor_slug = 'sqlserver') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-020-RC04', 'sqlserver', 'Detect SEC-SQL-AUD-020-RC04 (sqlserver)', 'Data deleted from a table (audit trail)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('sqlserver', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-020-RC04 (sqlserver)', '{"action": "Confirm the deletion was authorised. If not, restore affected rows from backup / flashback / point-in-time, identify the principal, and review DML privileges and WHERE-clause controls."}'::jsonb, 'high', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-020-RC04', 'sqlserver', 'Resolve: Detect SEC-SQL-AUD-020-RC04 (sqlserver)', 'resolve-sec_sql_aud_020_rc04-sqlserver', 'Confirm the deletion was authorised. If not, restore affected rows from backup / flashback / point-in-time, identify the principal, and review DML privileges and WHERE-clause controls.', 'supervised', 'high', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-020-RC04 / oracle
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'oracle' AND name = 'Detect SEC-SQL-AUD-020-RC04 (oracle)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-020-RC04' AND vendor_slug = 'oracle') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-020-RC04', 'oracle', 'Detect SEC-SQL-AUD-020-RC04 (oracle)', 'Data deleted from a table (audit trail)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('oracle', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-020-RC04 (oracle)', '{"action": "Confirm the deletion was authorised. If not, restore affected rows from backup / flashback / point-in-time, identify the principal, and review DML privileges and WHERE-clause controls."}'::jsonb, 'high', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-020-RC04', 'oracle', 'Resolve: Detect SEC-SQL-AUD-020-RC04 (oracle)', 'resolve-sec_sql_aud_020_rc04-oracle', 'Confirm the deletion was authorised. If not, restore affected rows from backup / flashback / point-in-time, identify the principal, and review DML privileges and WHERE-clause controls.', 'supervised', 'high', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
END
$gen$;

-- 4) MONITORING VIEWS (one per root cause) ---------------------------------
CREATE OR REPLACE VIEW monitoring.v_sec_sql_aud_020_rc01 AS
SELECT r.server,
    (j.value ->> 'event_time') AS event_time,
    (j.value ->> 'login_name') AS login_name,
    (j.value ->> 'database_name') AS database_name,
    (j.value ->> 'object_name') AS object_name,
    (j.value ->> 'statement') AS statement,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-AUD-020-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_aud_020_rc02 AS
SELECT r.server,
    (j.value ->> 'event_time') AS event_time,
    (j.value ->> 'login_name') AS login_name,
    (j.value ->> 'database_name') AS database_name,
    (j.value ->> 'object_name') AS object_name,
    (j.value ->> 'statement') AS statement,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-AUD-020-RC02';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_aud_020_rc03 AS
SELECT r.server,
    (j.value ->> 'event_time') AS event_time,
    (j.value ->> 'login_name') AS login_name,
    (j.value ->> 'database_name') AS database_name,
    (j.value ->> 'object_name') AS object_name,
    (j.value ->> 'statement') AS statement,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-AUD-020-RC03';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_aud_020_rc04 AS
SELECT r.server,
    (j.value ->> 'event_time') AS event_time,
    (j.value ->> 'login_name') AS login_name,
    (j.value ->> 'database_name') AS database_name,
    (j.value ->> 'object_name') AS object_name,
    (j.value ->> 'statement') AS statement,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-AUD-020-RC04';

-- 5) VERIFY ----------------------------------------------------------------
SELECT root_cause_id, name, vendors_applicable FROM rootcause.root_causes
 WHERE root_cause_id IN ('SEC-SQL-AUD-020-RC01', 'SEC-SQL-AUD-020-RC02', 'SEC-SQL-AUD-020-RC03', 'SEC-SQL-AUD-020-RC04');

COMMIT;
