-- ============================================================
-- 6310  SEC-SQL-AUD-021-RC01  Successful database authentication events (ALL vendors)
--   Live current-session detection per vendor + audit-trail 2nd step (oracle, sqlserver).
--   Verify by logging in to the database. Idempotent (rebuilds the RC cleanly).
-- ============================================================

-- ===========================================================================
-- Auto-generated by gen_rootcause_module.py from specs/auth_events.json
-- Module: auth_events   Root causes: 1   Vendors: sqlserver, oracle, postgresql, mysql, mariadb, informix
-- DO NOT hand-edit; edit the spec and regenerate.
-- ===========================================================================
BEGIN;

-- 0) ISSUE + cleanup of any prior SEC-SQL-AUD-021 artifacts (idempotent rebuild) --
INSERT INTO rootcause.issues (issue_id, domain_code, database_type_code, area_code, name, slug, description, created_at, updated_at)
VALUES ('SEC-SQL-AUD-021','SEC','SQL','AUD','Successful database authentication monitoring','successful-db-auth-monitoring','Capture and verify successful database authentication (logon) events.',now(),now())
ON CONFLICT (issue_id) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
DELETE FROM rootcause.detection_path_steps WHERE detection_path_id IN (SELECT id FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-021-RC01');
DELETE FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-021-RC01';
DELETE FROM rootcause.detection_steps WHERE name LIKE 'Detect SEC-SQL-AUD-021-RC01 %';
DELETE FROM rootcause.resolution_path_steps WHERE resolution_path_id IN (SELECT id FROM rootcause.resolution_paths WHERE root_cause_id='SEC-SQL-AUD-021-RC01');
DELETE FROM rootcause.resolution_paths WHERE root_cause_id='SEC-SQL-AUD-021-RC01';
DELETE FROM rootcause.resolution_steps WHERE name LIKE 'Resolve: Detect SEC-SQL-AUD-021-RC01 %';


-- 1) ROOT CAUSES -----------------------------------------------------------
INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-AUD-021-RC01', 'SEC-SQL-AUD-021', 'Successful database authentication events captured',
    'successful-db-authentication', 'Confirms DBDOME captures successful database logons (authentication events) across all supported engines: reads the live current-session view (V$SESSION / dm_exec_sessions / pg_stat_activity / PROCESSLIST / syssessions) and, on Oracle & SQL Server, also the audit trail of successful logons. Verify by simply logging in to the database.',
    ARRAY['audit', 'authentication', 'logon', 'monitoring'], ARRAY['sqlserver', 'oracle', 'postgresql', 'mysql', 'mariadb', 'informix']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

-- 2) DETECTION STEPS (per vendor) ------------------------------------------
INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('sqlserver', 'query', 'Detect SEC-SQL-AUD-021-RC01 (sqlserver)',
        '{"sql": "SELECT CONVERT(varchar(19), s.login_time, 120) AS event_time, s.login_name AS login_name,\n       s.host_name AS host_name, s.nt_user_name AS os_user, s.status AS auth_info, s.program_name AS program\nFROM sys.dm_exec_sessions s WHERE s.is_user_process = 1 AND s.login_name IS NOT NULL\nORDER BY s.login_time DESC"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Successful database authentication events are present"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('oracle', 'query', 'Detect SEC-SQL-AUD-021-RC01 (oracle)',
        '{"sql": "SELECT TO_CHAR(s.logon_time,''YYYY-MM-DD HH24:MI:SS'') AS event_time, s.username AS login_name,\n       s.machine AS host_name, s.osuser AS os_user, s.status AS auth_info, s.program AS program\nFROM v$session s WHERE s.type=''USER'' AND s.username IS NOT NULL\n  AND s.username NOT IN (''SYS'',''SYSTEM'',''DBSNMP'',''SYSMAN'',''XDB'')\nORDER BY s.logon_time DESC FETCH FIRST 500 ROWS ONLY"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Successful database authentication events are present"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('postgresql', 'query', 'Detect SEC-SQL-AUD-021-RC01 (postgresql)',
        '{"sql": "SELECT to_char(backend_start,''YYYY-MM-DD HH24:MI:SS'') AS event_time, usename AS login_name,\n       COALESCE(host(client_addr), client_hostname, ''local'') AS host_name, NULL::text AS os_user,\n       state AS auth_info, application_name AS program\nFROM pg_stat_activity WHERE usename IS NOT NULL AND backend_type=''client backend''\nORDER BY backend_start DESC LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Successful database authentication events are present"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('mysql', 'query', 'Detect SEC-SQL-AUD-021-RC01 (mysql)',
        '{"sql": "SELECT DATE_FORMAT(NOW(),''%Y-%m-%d %H:%i:%s'') AS event_time, LEFT(USER,128) AS login_name,\n       SUBSTRING_INDEX(HOST,'':'',1) AS host_name, NULL AS os_user, STATE AS auth_info, COMMAND AS program\nFROM information_schema.PROCESSLIST WHERE USER NOT IN (''event_scheduler'',''system user'')\nORDER BY TIME DESC LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Successful database authentication events are present"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('mariadb', 'query', 'Detect SEC-SQL-AUD-021-RC01 (mariadb)',
        '{"sql": "SELECT DATE_FORMAT(NOW(),''%Y-%m-%d %H:%i:%s'') AS event_time, LEFT(USER,128) AS login_name,\n       SUBSTRING_INDEX(HOST,'':'',1) AS host_name, NULL AS os_user, STATE AS auth_info, COMMAND AS program\nFROM information_schema.PROCESSLIST WHERE USER NOT IN (''event_scheduler'',''system user'')\nORDER BY TIME DESC LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Successful database authentication events are present"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('informix', 'query', 'Detect SEC-SQL-AUD-021-RC01 (informix)',
        '{"sql": "SELECT FIRST 500 CURRENT YEAR TO SECOND AS event_time, TRIM(username) AS login_name,\n       TRIM(hostname) AS host_name, '''' AS os_user, ''connected'' AS auth_info, TRIM(feprogram) AS program\nFROM sysmaster:syssessions WHERE username IS NOT NULL"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Successful database authentication events are present"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

-- 3) DETECTION PATHS + RESOLUTION (per root cause x vendor) ----------------
DO $gen$
DECLARE
    v_step_id   bigint;
    v_path_id   bigint;
    v_res_step  bigint;
    v_res_path  bigint;
BEGIN
    -- SEC-SQL-AUD-021-RC01 / sqlserver
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'sqlserver' AND name = 'Detect SEC-SQL-AUD-021-RC01 (sqlserver)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-021-RC01' AND vendor_slug = 'sqlserver') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-021-RC01', 'sqlserver', 'Detect SEC-SQL-AUD-021-RC01 (sqlserver)', 'Successful database authentication events captured', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('sqlserver', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-021-RC01 (sqlserver)', '{"action": "Successful logons are expected; review login_name/host/os_user for unexpected or off-hours access. Ensure logon auditing is enabled so authentication events are recorded in the audit trail."}'::jsonb, 'low', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-021-RC01', 'sqlserver', 'Resolve: Detect SEC-SQL-AUD-021-RC01 (sqlserver)', 'resolve-sec_sql_aud_021_rc01-sqlserver', 'Successful logons are expected; review login_name/host/os_user for unexpected or off-hours access. Ensure logon auditing is enabled so authentication events are recorded in the audit trail.', 'supervised', 'low', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-021-RC01 / oracle
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'oracle' AND name = 'Detect SEC-SQL-AUD-021-RC01 (oracle)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-021-RC01' AND vendor_slug = 'oracle') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-021-RC01', 'oracle', 'Detect SEC-SQL-AUD-021-RC01 (oracle)', 'Successful database authentication events captured', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('oracle', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-021-RC01 (oracle)', '{"action": "Successful logons are expected; review login_name/host/os_user for unexpected or off-hours access. Ensure logon auditing is enabled so authentication events are recorded in the audit trail."}'::jsonb, 'low', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-021-RC01', 'oracle', 'Resolve: Detect SEC-SQL-AUD-021-RC01 (oracle)', 'resolve-sec_sql_aud_021_rc01-oracle', 'Successful logons are expected; review login_name/host/os_user for unexpected or off-hours access. Ensure logon auditing is enabled so authentication events are recorded in the audit trail.', 'supervised', 'low', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-021-RC01 / postgresql
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'postgresql' AND name = 'Detect SEC-SQL-AUD-021-RC01 (postgresql)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-021-RC01' AND vendor_slug = 'postgresql') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-021-RC01', 'postgresql', 'Detect SEC-SQL-AUD-021-RC01 (postgresql)', 'Successful database authentication events captured', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('postgresql', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-021-RC01 (postgresql)', '{"action": "Successful logons are expected; review login_name/host/os_user for unexpected or off-hours access. Ensure logon auditing is enabled so authentication events are recorded in the audit trail."}'::jsonb, 'low', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-021-RC01', 'postgresql', 'Resolve: Detect SEC-SQL-AUD-021-RC01 (postgresql)', 'resolve-sec_sql_aud_021_rc01-postgresql', 'Successful logons are expected; review login_name/host/os_user for unexpected or off-hours access. Ensure logon auditing is enabled so authentication events are recorded in the audit trail.', 'supervised', 'low', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-021-RC01 / mysql
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'mysql' AND name = 'Detect SEC-SQL-AUD-021-RC01 (mysql)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-021-RC01' AND vendor_slug = 'mysql') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-021-RC01', 'mysql', 'Detect SEC-SQL-AUD-021-RC01 (mysql)', 'Successful database authentication events captured', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('mysql', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-021-RC01 (mysql)', '{"action": "Successful logons are expected; review login_name/host/os_user for unexpected or off-hours access. Ensure logon auditing is enabled so authentication events are recorded in the audit trail."}'::jsonb, 'low', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-021-RC01', 'mysql', 'Resolve: Detect SEC-SQL-AUD-021-RC01 (mysql)', 'resolve-sec_sql_aud_021_rc01-mysql', 'Successful logons are expected; review login_name/host/os_user for unexpected or off-hours access. Ensure logon auditing is enabled so authentication events are recorded in the audit trail.', 'supervised', 'low', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-021-RC01 / mariadb
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'mariadb' AND name = 'Detect SEC-SQL-AUD-021-RC01 (mariadb)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-021-RC01' AND vendor_slug = 'mariadb') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-021-RC01', 'mariadb', 'Detect SEC-SQL-AUD-021-RC01 (mariadb)', 'Successful database authentication events captured', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('mariadb', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-021-RC01 (mariadb)', '{"action": "Successful logons are expected; review login_name/host/os_user for unexpected or off-hours access. Ensure logon auditing is enabled so authentication events are recorded in the audit trail."}'::jsonb, 'low', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-021-RC01', 'mariadb', 'Resolve: Detect SEC-SQL-AUD-021-RC01 (mariadb)', 'resolve-sec_sql_aud_021_rc01-mariadb', 'Successful logons are expected; review login_name/host/os_user for unexpected or off-hours access. Ensure logon auditing is enabled so authentication events are recorded in the audit trail.', 'supervised', 'low', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-021-RC01 / informix
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'informix' AND name = 'Detect SEC-SQL-AUD-021-RC01 (informix)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-021-RC01' AND vendor_slug = 'informix') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-021-RC01', 'informix', 'Detect SEC-SQL-AUD-021-RC01 (informix)', 'Successful database authentication events captured', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('informix', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-021-RC01 (informix)', '{"action": "Successful logons are expected; review login_name/host/os_user for unexpected or off-hours access. Ensure logon auditing is enabled so authentication events are recorded in the audit trail."}'::jsonb, 'low', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-021-RC01', 'informix', 'Resolve: Detect SEC-SQL-AUD-021-RC01 (informix)', 'resolve-sec_sql_aud_021_rc01-informix', 'Successful logons are expected; review login_name/host/os_user for unexpected or off-hours access. Ensure logon auditing is enabled so authentication events are recorded in the audit trail.', 'supervised', 'low', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
END
$gen$;

-- 4) MONITORING VIEWS (one per root cause) ---------------------------------
CREATE OR REPLACE VIEW monitoring.v_sec_sql_aud_021_rc01 AS
SELECT r.server,
    (j.value ->> 'event_time') AS event_time,
    (j.value ->> 'login_name') AS login_name,
    (j.value ->> 'host_name') AS host_name,
    (j.value ->> 'os_user') AS os_user,
    (j.value ->> 'auth_info') AS auth_info,
    (j.value ->> 'program') AS program,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-AUD-021-RC01';

-- 5) VERIFY ----------------------------------------------------------------
SELECT root_cause_id, name, vendors_applicable FROM rootcause.root_causes
 WHERE root_cause_id IN ('SEC-SQL-AUD-021-RC01');

-- 2b) AUDIT-TRAIL second step (oracle, sqlserver) + wire step1 -> next -> step2 --
INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('oracle','query','Detect SEC-SQL-AUD-021-RC01 (oracle) - audit trail',
        '{"sql": "SELECT TO_CHAR(event_timestamp,''YYYY-MM-DD HH24:MI:SS'') AS event_time, dbusername AS login_name,\n       userhost AS host_name, os_username AS os_user, authentication_type AS auth_info, action_name AS program\nFROM unified_audit_trail WHERE action_name=''LOGON'' AND return_code=0\n  AND event_timestamp > SYSTIMESTAMP - INTERVAL ''1'' DAY\nORDER BY event_timestamp DESC FETCH FIRST 500 ROWS ONLY"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Successful database authentication events are present"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET content=EXCLUDED.content, expected=EXCLUDED.expected;
DO $g$ DECLARE v_path bigint; v_step2 bigint; BEGIN
  SELECT id INTO v_path FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-021-RC01' AND vendor_slug='oracle' ORDER BY id LIMIT 1;
  SELECT id INTO v_step2 FROM rootcause.detection_steps WHERE vendor_slug='oracle' AND name='Detect SEC-SQL-AUD-021-RC01 (oracle) - audit trail' ORDER BY id DESC LIMIT 1;
  IF v_path IS NOT NULL AND v_step2 IS NOT NULL THEN
    UPDATE rootcause.detection_path_steps SET on_no_match_action='next', on_no_match_goto=NULL WHERE detection_path_id=v_path AND sequence=1;
    IF NOT EXISTS (SELECT 1 FROM rootcause.detection_path_steps WHERE detection_path_id=v_path AND detection_step_id=v_step2) THEN
      INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
      VALUES (v_path, v_step2, 2, 'confirmed', 'ruled_out');
    END IF;
  END IF;
END $g$;
INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('sqlserver','query','Detect SEC-SQL-AUD-021-RC01 (sqlserver) - audit trail',
        '{"sql": "SET NOCOUNT ON;\nBEGIN TRY\n  SELECT TOP 500 CONVERT(varchar(19), event_time, 120) AS event_time, server_principal_name AS login_name,\n         CAST(NULL AS sysname) AS host_name, CAST(NULL AS sysname) AS os_user, action_id AS auth_info,\n         database_name AS program\n  FROM sys.fn_get_audit_file(N''C:\\Audit\\dbdome_audit*.sqlaudit'', DEFAULT, DEFAULT)\n  WHERE succeeded = 1 AND action_id = ''LGIS'' AND event_time > DATEADD(DAY,-1, SYSUTCDATETIME())\n  ORDER BY event_time DESC;\nEND TRY\nBEGIN CATCH\n  SELECT CAST(NULL AS varchar(19)) AS event_time, CAST(NULL AS sysname) AS login_name,\n         CAST(NULL AS sysname) AS host_name, CAST(NULL AS sysname) AS os_user,\n         CAST(NULL AS varchar(10)) AS auth_info, CAST(NULL AS sysname) AS program WHERE 1=0;\nEND CATCH"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Successful database authentication events are present"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET content=EXCLUDED.content, expected=EXCLUDED.expected;
DO $g$ DECLARE v_path bigint; v_step2 bigint; BEGIN
  SELECT id INTO v_path FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-021-RC01' AND vendor_slug='sqlserver' ORDER BY id LIMIT 1;
  SELECT id INTO v_step2 FROM rootcause.detection_steps WHERE vendor_slug='sqlserver' AND name='Detect SEC-SQL-AUD-021-RC01 (sqlserver) - audit trail' ORDER BY id DESC LIMIT 1;
  IF v_path IS NOT NULL AND v_step2 IS NOT NULL THEN
    UPDATE rootcause.detection_path_steps SET on_no_match_action='next', on_no_match_goto=NULL WHERE detection_path_id=v_path AND sequence=1;
    IF NOT EXISTS (SELECT 1 FROM rootcause.detection_path_steps WHERE detection_path_id=v_path AND detection_step_id=v_step2) THEN
      INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
      VALUES (v_path, v_step2, 2, 'confirmed', 'ruled_out');
    END IF;
  END IF;
END $g$;

COMMIT;
