-- ============================================================
-- 6360  SEC-SQL-AUD-025-RC01  Unauthorized sensitive-data change (UPDATE/DELETE/INSERT) monitoring
--   Captures data-changing DML against designated sensitive Flexcube tables
--   (FSDH_CUSTOMER_BVN, STTM_Customer, STTM_Cust_Account, STTM_Personal, STTM_Corporate).
--   oracle V$SQL (command_type 6/7/2), sqlserver dm_exec_query_stats, mysql/mariadb digest.
--   Edit the table list in the rule SQL to extend. Verify with an UPDATE on a listed table.
--   Idempotent (rebuilds the RC cleanly).
-- ============================================================

-- ===========================================================================
-- Auto-generated by gen_rootcause_module.py from specs/data_change.json
-- Module: data_change   Root causes: 1   Vendors: oracle, sqlserver, mysql, mariadb
-- DO NOT hand-edit; edit the spec and regenerate.
-- ===========================================================================
BEGIN;

-- 0) ISSUE + cleanup (idempotent rebuild) ------------------------------
INSERT INTO rootcause.issues (issue_id, domain_code, database_type_code, area_code, name, slug, description, created_at, updated_at)
VALUES ('SEC-SQL-AUD-025','SEC','SQL','AUD','Unauthorized sensitive-data change monitoring','sensitive-data-change-monitoring','Monitor and capture unauthorized data changes (UPDATE/DELETE/INSERT) to designated sensitive business-data tables.',now(),now())
ON CONFLICT (issue_id) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
DELETE FROM rootcause.detection_path_steps WHERE detection_path_id IN (SELECT id FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-025-RC01');
DELETE FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-025-RC01';
DELETE FROM rootcause.detection_steps WHERE name LIKE 'Detect SEC-SQL-AUD-025-RC01 %';
DELETE FROM rootcause.resolution_path_steps WHERE resolution_path_id IN (SELECT id FROM rootcause.resolution_paths WHERE root_cause_id='SEC-SQL-AUD-025-RC01');
DELETE FROM rootcause.resolution_paths WHERE root_cause_id='SEC-SQL-AUD-025-RC01';
DELETE FROM rootcause.resolution_steps WHERE name LIKE 'Resolve: Detect SEC-SQL-AUD-025-RC01 %';


-- 1) ROOT CAUSES -----------------------------------------------------------
INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-AUD-025-RC01', 'SEC-SQL-AUD-025', 'Unauthorized data change (UPDATE/DELETE/INSERT) to designated sensitive tables detected',
    'sensitive-data-change', 'Captures data-changing DML (UPDATE / DELETE / INSERT) against designated sensitive business-data tables (Flexcube customer/account PII: FSDH_CUSTOMER_BVN, STTM_Customer, STTM_Cust_Account, STTM_Personal, STTM_Corporate ...). Oracle reads V$SQL (command_type 6/7/2, plan cache); SQL Server reads dm_exec_query_stats; MySQL/MariaDB read performance_schema.events_statements_summary_by_digest. The table list is embedded in the rule SQL - edit it to add/adjust sensitive objects. Verify by running an UPDATE against a listed table.',
    ARRAY['dam', 'sensitive-data', 'pii', 'flexcube', 'data-change', 'data-integrity', 'security'], ARRAY['oracle', 'sqlserver', 'mysql', 'mariadb']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

-- 2) DETECTION STEPS (per vendor) ------------------------------------------
INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('oracle', 'query', 'Detect SEC-SQL-AUD-025-RC01 (oracle)',
        '{"sql": "SELECT TO_CHAR(last_active_time,''YYYY-MM-DD HH24:MI:SS'') AS event_time, parsing_schema_name AS login_name,\n       SYS_CONTEXT(''USERENV'',''DB_NAME'') AS host_name, CAST(NULL AS VARCHAR2(30)) AS os_user,\n       CASE command_type WHEN 6 THEN ''UPDATE'' WHEN 7 THEN ''DELETE'' WHEN 2 THEN ''INSERT'' END AS auth_info,\n       SUBSTR(sql_text,1,4000) AS statement\nFROM v$sql\nWHERE command_type IN (6,7,2)   -- UPDATE / DELETE / INSERT (data change)\n  AND (UPPER(sql_text) LIKE ''%FSDH_CUSTOMER_BVN%'' OR UPPER(sql_text) LIKE ''%STTM_CUSTOMER%'' OR UPPER(sql_text) LIKE ''%STTM_CUST_ACCOUNT%'' OR UPPER(sql_text) LIKE ''%STTM_PERSONAL%'' OR UPPER(sql_text) LIKE ''%STTM_CORPORATE%'')\nORDER BY last_active_time DESC FETCH FIRST 500 ROWS ONLY"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Data change (UPDATE/DELETE/INSERT) to a designated sensitive table detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('sqlserver', 'query', 'Detect SEC-SQL-AUD-025-RC01 (sqlserver)',
        '{"sql": "SELECT TOP 500 qs.last_execution_time AS event_time, CAST(NULL AS sysname) AS login_name,\n       DB_NAME(st.dbid) AS host_name, CAST(NULL AS sysname) AS os_user, ''plan cache'' AS auth_info,\n       CAST(st.text AS NVARCHAR(MAX)) AS statement\nFROM sys.dm_exec_query_stats qs WITH (NOLOCK) OUTER APPLY sys.dm_exec_sql_text(qs.sql_handle) st\nWHERE qs.last_execution_time >= DATEADD(DAY,-1, GETDATE()) AND st.text IS NOT NULL\n  AND st.text NOT LIKE ''%dm_exec_query_stats%''\n  AND (UPPER(st.text) LIKE ''%UPDATE %'' OR UPPER(st.text) LIKE ''%DELETE %'' OR UPPER(st.text) LIKE ''%INSERT %'')\n  AND (UPPER(st.text) LIKE ''%FSDH_CUSTOMER_BVN%'' OR UPPER(st.text) LIKE ''%STTM_CUSTOMER%'' OR UPPER(st.text) LIKE ''%STTM_CUST_ACCOUNT%'' OR UPPER(st.text) LIKE ''%STTM_PERSONAL%'' OR UPPER(st.text) LIKE ''%STTM_CORPORATE%'')\nORDER BY qs.last_execution_time DESC"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Data change (UPDATE/DELETE/INSERT) to a designated sensitive table detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('mysql', 'query', 'Detect SEC-SQL-AUD-025-RC01 (mysql)',
        '{"sql": "SELECT DATE_FORMAT(LAST_SEEN,''%Y-%m-%d %H:%i:%s'') AS event_time, CAST(NULL AS CHAR) AS login_name,\n       @@hostname AS host_name, CAST(NULL AS CHAR) AS os_user, CONCAT(''count='',COUNT_STAR) AS auth_info,\n       LEFT(DIGEST_TEXT,4000) AS statement\nFROM performance_schema.events_statements_summary_by_digest\nWHERE DIGEST_TEXT IS NOT NULL\n  AND (DIGEST_TEXT LIKE ''UPDATE%'' OR DIGEST_TEXT LIKE ''DELETE%'' OR DIGEST_TEXT LIKE ''INSERT%'')\n  AND (UPPER(DIGEST_TEXT) LIKE ''%FSDH_CUSTOMER_BVN%'' OR UPPER(DIGEST_TEXT) LIKE ''%STTM_CUSTOMER%'' OR UPPER(DIGEST_TEXT) LIKE ''%STTM_CUST_ACCOUNT%'' OR UPPER(DIGEST_TEXT) LIKE ''%STTM_PERSONAL%'' OR UPPER(DIGEST_TEXT) LIKE ''%STTM_CORPORATE%'')\nORDER BY LAST_SEEN DESC LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Data change (UPDATE/DELETE/INSERT) to a designated sensitive table detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('mariadb', 'query', 'Detect SEC-SQL-AUD-025-RC01 (mariadb)',
        '{"sql": "SELECT DATE_FORMAT(LAST_SEEN,''%Y-%m-%d %H:%i:%s'') AS event_time, CAST(NULL AS CHAR) AS login_name,\n       @@hostname AS host_name, CAST(NULL AS CHAR) AS os_user, CONCAT(''count='',COUNT_STAR) AS auth_info,\n       LEFT(DIGEST_TEXT,4000) AS statement\nFROM performance_schema.events_statements_summary_by_digest\nWHERE DIGEST_TEXT IS NOT NULL\n  AND (DIGEST_TEXT LIKE ''UPDATE%'' OR DIGEST_TEXT LIKE ''DELETE%'' OR DIGEST_TEXT LIKE ''INSERT%'')\n  AND (UPPER(DIGEST_TEXT) LIKE ''%FSDH_CUSTOMER_BVN%'' OR UPPER(DIGEST_TEXT) LIKE ''%STTM_CUSTOMER%'' OR UPPER(DIGEST_TEXT) LIKE ''%STTM_CUST_ACCOUNT%'' OR UPPER(DIGEST_TEXT) LIKE ''%STTM_PERSONAL%'' OR UPPER(DIGEST_TEXT) LIKE ''%STTM_CORPORATE%'')\nORDER BY LAST_SEEN DESC LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Data change (UPDATE/DELETE/INSERT) to a designated sensitive table detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

-- 3) DETECTION PATHS + RESOLUTION (per root cause x vendor) ----------------
DO $gen$
DECLARE
    v_step_id   bigint;
    v_path_id   bigint;
    v_res_step  bigint;
    v_res_path  bigint;
BEGIN
    -- SEC-SQL-AUD-025-RC01 / oracle
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'oracle' AND name = 'Detect SEC-SQL-AUD-025-RC01 (oracle)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-025-RC01' AND vendor_slug = 'oracle') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-025-RC01', 'oracle', 'Detect SEC-SQL-AUD-025-RC01 (oracle)', 'Unauthorized data change (UPDATE/DELETE/INSERT) to designated sensitive tables detected', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('oracle', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-025-RC01 (oracle)', '{"action": "Review who (login_name / host / os_user) modified the sensitive table and whether the change was an authorised business transaction. If unauthorised: identify the affected rows and restore from backup/audit, revoke the offending principal''s DML privilege, apply least-privilege and row-level security on the PII columns, and investigate for tampering / privilege abuse."}'::jsonb, 'high', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-025-RC01', 'oracle', 'Resolve: Detect SEC-SQL-AUD-025-RC01 (oracle)', 'resolve-sec_sql_aud_025_rc01-oracle', 'Review who (login_name / host / os_user) modified the sensitive table and whether the change was an authorised business transaction. If unauthorised: identify the affected rows and restore from backup/audit, revoke the offending principal''s DML privilege, apply least-privilege and row-level security on the PII columns, and investigate for tampering / privilege abuse.', 'supervised', 'high', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-025-RC01 / sqlserver
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'sqlserver' AND name = 'Detect SEC-SQL-AUD-025-RC01 (sqlserver)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-025-RC01' AND vendor_slug = 'sqlserver') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-025-RC01', 'sqlserver', 'Detect SEC-SQL-AUD-025-RC01 (sqlserver)', 'Unauthorized data change (UPDATE/DELETE/INSERT) to designated sensitive tables detected', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('sqlserver', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-025-RC01 (sqlserver)', '{"action": "Review who (login_name / host / os_user) modified the sensitive table and whether the change was an authorised business transaction. If unauthorised: identify the affected rows and restore from backup/audit, revoke the offending principal''s DML privilege, apply least-privilege and row-level security on the PII columns, and investigate for tampering / privilege abuse."}'::jsonb, 'high', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-025-RC01', 'sqlserver', 'Resolve: Detect SEC-SQL-AUD-025-RC01 (sqlserver)', 'resolve-sec_sql_aud_025_rc01-sqlserver', 'Review who (login_name / host / os_user) modified the sensitive table and whether the change was an authorised business transaction. If unauthorised: identify the affected rows and restore from backup/audit, revoke the offending principal''s DML privilege, apply least-privilege and row-level security on the PII columns, and investigate for tampering / privilege abuse.', 'supervised', 'high', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-025-RC01 / mysql
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'mysql' AND name = 'Detect SEC-SQL-AUD-025-RC01 (mysql)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-025-RC01' AND vendor_slug = 'mysql') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-025-RC01', 'mysql', 'Detect SEC-SQL-AUD-025-RC01 (mysql)', 'Unauthorized data change (UPDATE/DELETE/INSERT) to designated sensitive tables detected', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('mysql', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-025-RC01 (mysql)', '{"action": "Review who (login_name / host / os_user) modified the sensitive table and whether the change was an authorised business transaction. If unauthorised: identify the affected rows and restore from backup/audit, revoke the offending principal''s DML privilege, apply least-privilege and row-level security on the PII columns, and investigate for tampering / privilege abuse."}'::jsonb, 'high', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-025-RC01', 'mysql', 'Resolve: Detect SEC-SQL-AUD-025-RC01 (mysql)', 'resolve-sec_sql_aud_025_rc01-mysql', 'Review who (login_name / host / os_user) modified the sensitive table and whether the change was an authorised business transaction. If unauthorised: identify the affected rows and restore from backup/audit, revoke the offending principal''s DML privilege, apply least-privilege and row-level security on the PII columns, and investigate for tampering / privilege abuse.', 'supervised', 'high', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-025-RC01 / mariadb
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'mariadb' AND name = 'Detect SEC-SQL-AUD-025-RC01 (mariadb)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-025-RC01' AND vendor_slug = 'mariadb') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-025-RC01', 'mariadb', 'Detect SEC-SQL-AUD-025-RC01 (mariadb)', 'Unauthorized data change (UPDATE/DELETE/INSERT) to designated sensitive tables detected', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('mariadb', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-025-RC01 (mariadb)', '{"action": "Review who (login_name / host / os_user) modified the sensitive table and whether the change was an authorised business transaction. If unauthorised: identify the affected rows and restore from backup/audit, revoke the offending principal''s DML privilege, apply least-privilege and row-level security on the PII columns, and investigate for tampering / privilege abuse."}'::jsonb, 'high', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-025-RC01', 'mariadb', 'Resolve: Detect SEC-SQL-AUD-025-RC01 (mariadb)', 'resolve-sec_sql_aud_025_rc01-mariadb', 'Review who (login_name / host / os_user) modified the sensitive table and whether the change was an authorised business transaction. If unauthorised: identify the affected rows and restore from backup/audit, revoke the offending principal''s DML privilege, apply least-privilege and row-level security on the PII columns, and investigate for tampering / privilege abuse.', 'supervised', 'high', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
END
$gen$;

-- 4) MONITORING VIEWS (one per root cause) ---------------------------------
CREATE OR REPLACE VIEW monitoring.v_sec_sql_aud_025_rc01 AS
SELECT r.server,
    (j.value ->> 'event_time') AS event_time,
    (j.value ->> 'login_name') AS login_name,
    (j.value ->> 'host_name') AS host_name,
    (j.value ->> 'os_user') AS os_user,
    (j.value ->> 'auth_info') AS auth_info,
    (j.value ->> 'statement') AS statement,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-AUD-025-RC01';

-- 5) VERIFY ----------------------------------------------------------------
SELECT root_cause_id, name, vendors_applicable FROM rootcause.root_causes
 WHERE root_cause_id IN ('SEC-SQL-AUD-025-RC01');

COMMIT;
