-- =============================================================================
-- 7450_mongodb_doc_detections.sql
--
-- MongoDB detections + resolutions for the DOC (document-database) taxonomy.
-- Makes 75 PERF-DOC / SEC-DOC / HLTH-DOC root causes visible to
-- rootcause.v_rootcauses -> metrics.v_custom_metrics, and therefore collectable.
--
-- The DOC root causes (2,335 of them) already ship in the catalog, but none had
-- a detection path OR a resolution path -- and v_rootcauses INNER JOINs BOTH
-- chains, so every one of them was invisible end-to-end. rootcause.vendors
-- already carries ('mongodb','MongoDB','DOC'), so no vendor row is required.
--
-- A MONGODB DETECTION STEP IS A JSON SPEC, NOT SQL. content->>'sql' holds a
-- document executed by the MongoDB collector, e.g.
--     {"command":{"serverStatus":1},"path":"connections"}
--     {"db":"admin","collection":"system.users","find":{"roles.role":"root"}}
-- The optional "path" selects a dotted sub-document of a command reply so nested
-- counters become real columns.
--
-- Every spec was executed against a live MongoDB 8.0 replica set and every
-- column-level condition evaluated to a definite verdict.
--
-- Add-only: a root cause is touched ONLY when no (root_cause_id,'mongodb')
-- detection path exists, so re-runs are no-ops. Idempotent; additive only.
-- =============================================================================
-- NOTE: `\set ON_ERROR_STOP on` removed. It is a psql CLIENT directive; this file is
-- applied by processes/sql_script_runner.py through psycopg2, which cannot parse a
-- backslash command and failed the whole script on it ("syntax error at or near \"\\\"").
-- The behaviour it asked for is already guaranteed: the runner executes each file in one
-- transaction and rolls the whole file back on the first error.

BEGIN;

CREATE TEMP TABLE _mongo_seed (
    rc text, spec text, cond text, descr text,
    risk text, res_name text, res_text text
);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-AUTH-003-RC01$mg$,$mg${"db":"admin","collection":"system.users","count":{}}$mg$,$mg$count = 0$mg$,$mg$No users are defined at all - every client that connects has full access (admin party)$mg$,$mg$critical$mg$,$mg$Create an administrative user and enable authorization$mg$,$mg$Create a user with the userAdminAnyDatabase role in the admin database, then set security.authorization: enabled in mongod.conf and restart. Until a user exists MongoDB accepts every connection with full rights (localhost exception aside). Verify with db.getSiblingDB('admin').system.users.countDocuments({}) > 0.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-AUTH-001-RC01$mg$,$mg${"db":"admin","collection":"system.users","find":{"user":{"$in":["admin","root","mongo","mongodb","test","user","guest","dbadmin"]}},"projection":{"user":1,"db":1},"limit":50}$mg$,$mg$row_count > 0$mg$,$mg$Accounts using vendor/default names still exist$mg$,$mg$high$mg$,$mg$Rename or remove default-named accounts$mg$,$mg$Replace accounts named admin/root/test/guest with named, per-application service accounts scoped to the databases they need. Drop the defaults with db.dropUser(). Default names are the first thing credential-stuffing tools try.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-AUTH-002-RC04$mg$,$mg${"db":"admin","collection":"system.users","find":{"credentials.SCRAM-SHA-256":{"$exists":false}},"projection":{"user":1,"db":1},"limit":50}$mg$,$mg$row_count > 0$mg$,$mg$Users retained for legacy compatibility carry no SCRAM-SHA-256 credential (SHA-1 only)$mg$,$mg$high$mg$,$mg$Re-create legacy users with SCRAM-SHA-256$mg$,$mg$Users carrying only a SCRAM-SHA-1 credential predate the SHA-256 default or were created with an explicit mechanisms list. Re-create each with mechanisms:['SCRAM-SHA-256'] (a password change is required - the hash cannot be upgraded in place), then set authenticationMechanisms to SCRAM-SHA-256 once no client needs SHA-1.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-AUTH-004-RC01$mg$,$mg${"command":{"getCmdLineOpts":1},"path":"parsed.security"}$mg$,$mg$row_count = 0$mg$,$mg$No security section in the running configuration - the server accepts unauthenticated clients$mg$,$mg$critical$mg$,$mg$Enable authorization in the running configuration$mg$,$mg$Add security.authorization: enabled (or a keyFile, which implies it) to mongod.conf and restart. Create the administrative user first, through the localhost exception, or you will lock yourself out.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-AUTHZ-005-RC01$mg$,$mg${"db":"admin","collection":"system.users","find":{"roles.role":"root"},"projection":{"user":1,"db":1},"limit":50}$mg$,$mg$row_count > 0$mg$,$mg$Accounts holding the root role exist - an application must never connect as one$mg$,$mg$critical$mg$,$mg$Give the application its own least-privilege account$mg$,$mg$Create a service account holding only readWrite on the specific databases the application uses, switch the connection string to it, and reserve root for interactive administration. Then confirm no application host still authenticates as a root-role account.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-AUTHZ-001-RC01$mg$,$mg${"db":"admin","collection":"system.users","find":{"roles.role":{"$in":["root","dbOwner","userAdminAnyDatabase","readWriteAnyDatabase","clusterAdmin","dbAdminAnyDatabase"]}},"projection":{"user":1,"db":1,"roles":1},"limit":100}$mg$,$mg$row_count > 0$mg$,$mg$Accounts hold cluster-wide privileged roles instead of least-privilege scoped roles$mg$,$mg$high$mg$,$mg$Replace cluster-wide roles with scoped grants$mg$,$mg$For each account, replace root/dbOwner/*AnyDatabase/clusterAdmin with the narrowest built-in or custom role covering its actual access, using db.updateUser(). Re-run this detection afterwards - it should return no rows.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-AUTHZ-002-RC01$mg$,$mg${"db":"admin","collection":"system.roles","find":{},"projection":{"role":1,"db":1},"limit":100}$mg$,$mg$row_count = 0$mg$,$mg$No custom roles defined - access control relies solely on built-in roles$mg$,$mg$medium$mg$,$mg$Define custom roles for the access patterns you actually have$mg$,$mg$Built-in roles are coarse. Create custom roles with db.createRole() granting only the actions each application or team needs, and reassign users to them, so privilege review becomes a role review rather than a per-user audit.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-ENC-001-RC01$mg$,$mg${"command":{"getParameter":1,"sslMode":1}}$mg$,$mg$sslMode = 'disabled'$mg$,$mg$TLS is disabled - client traffic, including credentials, crosses the network in clear text$mg$,$mg$critical$mg$,$mg$Enable TLS for all client connections$mg$,$mg$Set net.tls.mode to requireTLS with net.tls.certificateKeyFile in mongod.conf and restart. Roll clients over using preferTLS first if you cannot cut over at once. Without TLS, SCRAM protects the password but every document travels in clear text.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-ENC-003-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"encryptionAtRest"}$mg$,$mg$row_count = 0$mg$,$mg$Server reports no encryption-at-rest subsystem - data files are unencrypted on disk$mg$,$mg$high$mg$,$mg$Encrypt data at rest$mg$,$mg$MongoDB Enterprise offers native encryption at rest (security.enableEncryption with a KMIP key server or local keyfile); Community does not, so use filesystem or volume encryption (LUKS/dm-crypt, BitLocker, or a cloud provider's encrypted disks) instead. Encryption cannot be enabled on existing data files in place - it requires a fresh dbPath and a resync/restore.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-INJ-003-RC02$mg$,$mg${"command":{"getCmdLineOpts":1},"path":"parsed.security"}$mg$,$mg$row_count > 0$mg$,$mg$Running security configuration - absence of javascriptEnabled:false leaves $where/$function server-side JavaScript enabled (the default)$mg$,$mg$high$mg$,$mg$Disable server-side JavaScript$mg$,$mg$Set security.javascriptEnabled: false in mongod.conf and restart, unless mapReduce or $where/$function are genuinely required. With it on, an injected $where turns a query into arbitrary server-side code execution.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-AUD-001-RC01$mg$,$mg${"command":{"getCmdLineOpts":1},"path":"parsed.auditLog"}$mg$,$mg$row_count = 0$mg$,$mg$No auditLog section in the running configuration - auditing is off$mg$,$mg$high$mg$,$mg$Enable the audit log$mg$,$mg$MongoDB Enterprise: configure auditLog.destination/format/path and an auditLog.filter covering authentication, authorization failures and DDL. Community has no auditing - front the deployment with change streams or application-side logging, and treat the gap as a compliance risk in its own right.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-NET-002-RC01$mg$,$mg${"command":{"getCmdLineOpts":1},"path":"parsed.net"}$mg$,$mg$bindIp = '0.0.0.0'$mg$,$mg$Server binds every interface (0.0.0.0) - reachable from any network that can route to it$mg$,$mg$critical$mg$,$mg$Bind only the interfaces that must serve clients$mg$,$mg$Replace net.bindIp: 0.0.0.0 with the specific private addresses clients use (plus 127.0.0.1) and restart. Pair this with a firewall restricting 27017 to known sources - binding all interfaces is what turns a missing-auth mistake into an internet-exposed database.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-REP-002-RC02$mg$,$mg${"command":{"replSetGetStatus":1},"path":"members"}$mg$,$mg$health = 0$mg$,$mg$A replica set member is unreachable (health=0) - replication to it has stopped$mg$,$mg$critical$mg$,$mg$Restore connectivity to the unreachable member$mg$,$mg$health=0 means the primary cannot reach that member. Check the network path and firewall on port 27017 between members, confirm the member's mongod is running, and inspect its log for keyFile/certificate mismatches after a rolling change. Replication resumes on its own once the heartbeat succeeds.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-HA-001-RC01$mg$,$mg${"command":{"hello":1},"path":"hosts"}$mg$,$mg$row_count < 2$mg$,$mg$Fewer than two data-bearing hosts - the deployment cannot fail over$mg$,$mg$high$mg$,$mg$Convert to a replica set with at least three voting members$mg$,$mg$A standalone (or a set with one data-bearing host) has no failover and no redundant copy. Add two data-bearing members - or two plus an arbiter where cost forbids a third copy - so a majority survives a single node loss.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-REP-001-RC03$mg$,$mg${"command":{"serverStatus":1},"path":"metrics.repl.buffer"}$mg$,$mg$row_count > 0$mg$,$mg$Replication apply-buffer counters - a persistently non-empty buffer indicates the secondary cannot keep up$mg$,$mg$medium$mg$,$mg$Relieve the saturated secondary$mg$,$mg$A persistently non-empty apply buffer means the secondary cannot keep pace. Check its disk latency and CPU, move analytics reads off it, and confirm no foreground index build is running there. If the hardware is simply smaller than the primary's, match it.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-BAK-003-RC01$mg$,$mg${"db":"local","collection":"oplog.rs","aggregate":[{"$group":{"_id":null,"oplog_entries":{"$sum":1}}}]}$mg$,$mg$row_count > 0$mg$,$mg$Oplog entry count - a small oplog shortens the recovery/resync window$mg$,$mg$high$mg$,$mg$Size the oplog for your slowest recovery$mg$,$mg$The oplog must span longer than the worst-case secondary outage or backup window, or a lagging member needs a full resync. Measure with rs.printReplicationInfo() and grow it using replSetResizeOplog (online, no restart).$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-STG-001-RC01$mg$,$mg${"command":{"dbStats":1}}$mg$,$mg$row_count > 0$mg$,$mg$Database size vs filesystem capacity (dataSize/storageSize/fsUsedSize/fsTotalSize)$mg$,$mg$high$mg$,$mg$Reclaim space and add headroom$mg$,$mg$Compare dataSize with storageSize to see reclaimable space, and fsUsedSize with fsTotalSize for real headroom. Reclaim with compact on a secondary then step it over, or resync members one at a time. Extend the volume before free space reaches the point where the server cannot checkpoint.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-STG-004-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"storageEngine"}$mg$,$mg$row_count > 0$mg$,$mg$Storage engine in use and its capability flags$mg$,$mg$low$mg$,$mg$Confirm the storage engine suits the workload$mg$,$mg$WiredTiger is the only supported engine on current releases. If this reports anything else the deployment is on an unsupported legacy engine and must be migrated. Also review block compression (snappy vs zstd) against your read/write mix.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-UPG-003-RC01$mg$,$mg${"db":"admin","collection":"system.version","find":{"_id":"featureCompatibilityVersion"},"limit":5}$mg$,$mg$row_count > 0$mg$,$mg$featureCompatibilityVersion - an FCV behind the binary blocks new features and the next upgrade$mg$,$mg$medium$mg$,$mg$Advance featureCompatibilityVersion to match the binary$mg$,$mg$After a successful upgrade run db.adminCommand({setFeatureCompatibilityVersion: '<version>', confirm: true}). Leaving FCV behind keeps new features off and blocks the next major upgrade. Only advance once you are certain you will not downgrade.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-MNT-005-RC01$mg$,$mg${"command":{"buildInfo":1},"path":"versionArray"}$mg$,$mg$row_count > 0$mg$,$mg$Running server version components$mg$,$mg$medium$mg$,$mg$Plan an upgrade to a supported release$mg$,$mg$Check the running version against the MongoDB release and end-of-life calendar. Upgrade one major version at a time, secondaries first, then step down the primary, advancing FCV only after the whole set is on the new binary.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-LOG-001-RC01$mg$,$mg${"command":{"getCmdLineOpts":1},"path":"parsed.systemLog"}$mg$,$mg$row_count > 0$mg$,$mg$systemLog configuration - logRotate/destination settings govern whether logs are rotated$mg$,$mg$medium$mg$,$mg$Configure log rotation$mg$,$mg$Set systemLog.logRotate: reopen and hand rotation to logrotate (Linux), or use logRotate: rename where the platform has no external rotator. Without rotation the log grows until it fills the volume and takes the server down with it.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-CLU-001-RC01$mg$,$mg${"db":"config","collection":"settings","find":{"_id":"balancer"},"limit":5}$mg$,$mg$row_count > 0$mg$,$mg$Balancer settings document present - inspect stopped/activeWindow for a disabled balancer$mg$,$mg$high$mg$,$mg$Re-enable the balancer or fix its window$mg$,$mg$sh.startBalancer() re-enables balancing; check the activeWindow in config.settings if it only runs in a window that never opens. A stopped balancer lets chunk distribution skew until individual shards run hot or fill up.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-CON-004-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"connections"}$mg$,$mg$available < 100$mg$,$mg$Fewer than 100 connection slots remain available on the server$mg$,$mg$high$mg$,$mg$Raise the connection ceiling or reduce client pools$mg$,$mg$Available slots are nearly exhausted. Either lower maxPoolSize across application instances (total connections = instances x maxPoolSize) or raise the server's limit via net.maxIncomingConnections and the process ulimit. Exhaustion refuses new clients outright.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-CON-001-RC01$mg$,$mg${"db":"admin","aggregate":[{"$currentOp":{"allUsers":true,"idleConnections":true,"idleSessions":true}},{"$count":"connection_count"}]}$mg$,$mg$connection_count > 200$mg$,$mg$More than 200 client connections are attached$mg$,$mg$medium$mg$,$mg$Right-size the client connection pool$mg$,$mg$Very high connection counts usually mean pools sized per instance without accounting for horizontal scaling. Set maxPoolSize deliberately, and make sure clients reuse one MongoClient per process rather than constructing one per request.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-QRY-001-RC01$mg$,$mg${"db":"admin","aggregate":[{"$currentOp":{"allUsers":true,"idleSessions":false}},{"$match":{"secs_running":{"$gte":5},"op":{"$ne":"none"}}},{"$project":{"opid":1,"secs_running":1,"ns":1,"op":1,"planSummary":1}},{"$limit":50}]}$mg$,$mg$row_count > 0$mg$,$mg$Operations running 5 seconds or longer$mg$,$mg$high$mg$,$mg$Index the fields these operations filter and sort on$mg$,$mg$For each operation returned, run explain('executionStats') on its query shape and compare docsExamined with nReturned. A large ratio means the filter or sort is unindexed - add a compound index ordered equality, sort, range.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-QRY-002-RC01$mg$,$mg${"db":"admin","aggregate":[{"$currentOp":{"allUsers":true,"idleSessions":false}},{"$match":{"planSummary":"COLLSCAN"}},{"$project":{"opid":1,"ns":1,"op":1,"secs_running":1,"planSummary":1}},{"$limit":50}]}$mg$,$mg$row_count > 0$mg$,$mg$Operations executing a full collection scan (COLLSCAN)$mg$,$mg$high$mg$,$mg$Add indexes to eliminate the collection scans$mg$,$mg$Each row is an operation reading an entire collection. Create an index covering its filter, and where the query returns few fields, extend it to cover the projection so the scan disappears entirely.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-MEM-001-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"wiredTiger.cache"}$mg$,$mg$row_count > 0$mg$,$mg$WiredTiger cache counters - compare bytes currently in the cache against the configured maximum, and watch the dirty/eviction counters$mg$,$mg$high$mg$,$mg$Relieve WiredTiger cache pressure$mg$,$mg$Compare bytes currently in the cache against the configured maximum and watch the dirty-bytes and eviction counters. Sustained pressure means the working set exceeds the cache: add RAM, raise wiredTigerCacheSizeGB if the host has headroom, or reduce the working set with better indexes and projections.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-MEM-004-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"mem"}$mg$,$mg$row_count > 0$mg$,$mg$Process resident/virtual memory - resident far below the working set implies paging$mg$,$mg$medium$mg$,$mg$Investigate paging$mg$,$mg$Resident memory well below the working set, with virtual far above it, indicates the OS is paging MongoDB's mapped files. Confirm swap usage and disk read latency at the OS, disable transparent huge pages, and ensure no other process competes for RAM on the host.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-WRT-003-RC04$mg$,$mg${"command":{"serverStatus":1},"path":"globalLock.currentQueue"}$mg$,$mg$writers > 0$mg$,$mg$Writers are queued on the global lock$mg$,$mg$high$mg$,$mg$Reduce global-lock write contention$mg$,$mg$Writers queued on the global lock point at a hot collection or long-held write locks. Look for large multi-document updates, foreground index builds, or an unsharded hot collection, and break the work into smaller batches.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-WRT-001-RC04$mg$,$mg${"command":{"getDefaultRWConcern":1}}$mg$,$mg$row_count > 0$mg$,$mg$Cluster-wide default read/write concern - a strict default write concern costs latency on every write$mg$,$mg$medium$mg$,$mg$Match the default write concern to the durability you need$mg$,$mg$A cluster-wide default of majority costs a round trip to a second member on every write. Set it deliberately with setDefaultRWConcern - keep majority where correctness demands it, and let latency-sensitive collections opt down per operation rather than weakening the global default.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-IDX-002-RC01$mg$,$mg${"db":"appdb","collection":"orders","aggregate":[{"$indexStats":{}},{"$project":{"name":1,"ops":"$accesses.ops"}}]}$mg$,$mg$ops = 0$mg$,$mg$Index has never been used since the last server restart$mg$,$mg$medium$mg$,$mg$Drop indexes nothing uses$mg$,$mg$accesses.ops of zero means no query has used the index since the last restart, so confirm across a full business cycle and on every member before acting. Each unused index still costs write throughput and disk. Drop with db.collection.dropIndex(), keeping unique/TTL indexes regardless of usage.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-DOC-002-RC01$mg$,$mg${"db":"appdb","collection":"orders","aggregate":[{"$collStats":{"storageStats":{}}},{"$project":{"count":"$storageStats.count","avgObjSize":"$storageStats.avgObjSize","size":"$storageStats.size"}}]}$mg$,$mg$avgObjSize > 100000$mg$,$mg$Average document size exceeds 100 KB - approaching the 16 MB document limit$mg$,$mg$high$mg$,$mg$Restructure oversized documents$mg$,$mg$Documents averaging this size are heading for the 16 MB hard limit, and every read pulls the whole document into cache. Move unbounded arrays into their own collection referencing the parent, and split rarely-read blobs out of the hot document.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-CON-002-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"network"}$mg$,$mg$row_count > 0$mg$,$mg$Network request/byte counters - a spike in numRequests against physicalBytesIn signals a connection storm$mg$,$mg$medium$mg$,$mg$Throttle reconnect storms$mg$,$mg$Add jittered exponential backoff to client reconnect logic and cap maxPoolSize. A storm is usually every application instance reconnecting at once after a blip, which then keeps the server too busy to recover.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-CON-003-RC05$mg$,$mg${"db":"admin","aggregate":[{"$currentOp":{"allUsers":true,"idleConnections":true,"idleSessions":true}},{"$match":{"active":false}},{"$count":"idle_connections"}]}$mg$,$mg$idle_connections > 100$mg$,$mg$More than 100 idle connections are held open$mg$,$mg$medium$mg$,$mg$Find and close the leaking client path$mg$,$mg$A large idle pool that never drains points at connections created per request instead of per process. Ensure one MongoClient per application process and that request handlers never construct their own.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-CON-005-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"asserts"}$mg$,$mg$row_count > 0$mg$,$mg$Server assertion counters - rising user/warning asserts accompany connection and timeout errors$mg$,$mg$low$mg$,$mg$Correlate assertion counts with client timeouts$mg$,$mg$Read the mongod log around the time asserts increment. Persistent rollovers usually mean clients time out mid-operation; raise the client socket timeout or fix the slow operation underneath.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-CON-007-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"transactions"}$mg$,$mg$row_count > 0$mg$,$mg$Transaction counters - currentOpen against currentActive shows sessions pinned by open transactions$mg$,$mg$medium$mg$,$mg$Bound transaction lifetime$mg$,$mg$Open transactions pin a session and a connection for their whole life. Keep multi-document transactions short, and lower transactionLifetimeLimitSeconds so abandoned ones are reaped sooner.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-CON-008-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"metrics.cursor"}$mg$,$mg$row_count > 0$mg$,$mg$Cursor counters - open.total against timedOut shows cursors abandoned rather than exhausted$mg$,$mg$low$mg$,$mg$Close cursors explicitly$mg$,$mg$Cursors accumulating in timedOut mean client code abandons iteration without closing. Close cursors in a finally block, or set a batch size and consume fully.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-DOC-010-RC01$mg$,$mg${"db":"appdb","command":{"listCollections":1,"filter":{"options.validator":{"$exists":false}}},"path":"cursor.firstBatch"}$mg$,$mg$row_count > 0$mg$,$mg$Collections defined without any JSON-schema validator$mg$,$mg$medium$mg$,$mg$Attach a schema validator$mg$,$mg$Add a $jsonSchema validator with collMod so shape drift is rejected at write time. Start with validationLevel:'moderate' so existing documents are not blocked while new writes are constrained.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-DOC-003-RC01$mg$,$mg${"db":"appdb","collection":"orders","aggregate":[{"$collStats":{"storageStats":{}}},{"$project":{"avgObjSize":"$storageStats.avgObjSize","storageSize":"$storageStats.storageSize","freeStorageSize":"$storageStats.freeStorageSize"}}]}$mg$,$mg$row_count > 0$mg$,$mg$Per-collection storage: average document size, storage size and reclaimable free space$mg$,$mg$medium$mg$,$mg$Trim documents that carry cold data$mg$,$mg$Split rarely-read fields out of the hot document. Every read pulls the whole document into cache, so cold blobs inside a hot document waste cache proportionally to their size.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-IDX-001-RC01$mg$,$mg${"db":"appdb","collection":"orders","command":{"listIndexes":"orders"},"path":"cursor.firstBatch"}$mg$,$mg$row_count < 2$mg$,$mg$Collection carries only the default _id index - every non-_id filter is a collection scan$mg$,$mg$high$mg$,$mg$Index the collection's real query shapes$mg$,$mg$Collect the actual filters from the profiler or $currentOp and create compound indexes ordered equality, sort, range. A collection with only _id cannot serve any other predicate.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-IDX-008-RC01$mg$,$mg${"db":"appdb","collection":"orders","aggregate":[{"$collStats":{"storageStats":{}}},{"$project":{"totalIndexSize":"$storageStats.totalIndexSize","dataSize":"$storageStats.size","nindexes":"$storageStats.nindexes"}}]}$mg$,$mg$row_count > 0$mg$,$mg$Total index size against data size - indexes larger than the data they serve indicate bloat$mg$,$mg$medium$mg$,$mg$Rebuild or drop bloated indexes$mg$,$mg$Compare totalIndexSize with the data size. Rebuild on a secondary then step it over, and drop indexes that $indexStats shows unused before rebuilding the rest.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-IDX-010-RC01$mg$,$mg${"db":"admin","aggregate":[{"$currentOp":{"allUsers":true,"idleSessions":false}},{"$match":{"op":"command","command.createIndexes":{"$exists":true}}},{"$project":{"opid":1,"ns":1,"secs_running":1,"msg":1,"progress":1}},{"$limit":20}]}$mg$,$mg$row_count > 0$mg$,$mg$Index builds currently in progress$mg$,$mg$low$mg$,$mg$Let the build finish, or plan it off-peak$mg$,$mg$An in-progress build consumes IO and memory and holds resources on every member. Run builds during a quiet window; on a replica set they replicate, so expect the load on secondaries too.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-MEM-002-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"wiredTiger.block-manager"}$mg$,$mg$row_count > 0$mg$,$mg$Block-manager IO counters - sustained blocks read means the working set is being fetched from disk$mg$,$mg$high$mg$,$mg$Fit the working set in cache$mg$,$mg$Persistent block reads mean the working set exceeds the WiredTiger cache. Add RAM, or shrink the working set with tighter indexes and projections so fewer pages are touched.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-MEM-005-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"wiredTiger.cache"}$mg$,$mg$row_count > 0$mg$,$mg$Cache page statistics - compare pages requested from the cache against pages read into the cache for the hit ratio$mg$,$mg$high$mg$,$mg$Raise the cache hit ratio$mg$,$mg$Divide pages read into the cache by pages requested. A rising ratio means more reads miss cache; increase wiredTigerCacheSizeGB where the host has RAM to spare, or reduce the pages each query touches.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-MEM-007-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"metrics.queryExecutor"}$mg$,$mg$row_count > 0$mg$,$mg$Query executor counters - scanned against scannedObjects shows how much work each result costs$mg$,$mg$medium$mg$,$mg$Cut documents examined per result$mg$,$mg$A high scannedObjects-to-returned ratio means the executor reads far more than it returns. Add or reorder indexes so the filter is served by the index rather than by document inspection.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-QRY-006-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"metrics.operation"}$mg$,$mg$scanAndOrder > 0$mg$,$mg$Operations performed an in-memory sort because no index provided the sort order$mg$,$mg$high$mg$,$mg$Index the sort$mg$,$mg$scanAndOrder counts sorts done in memory, which fail outright past 100 MB. Extend the compound index so its trailing keys match the sort order and direction.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-QRY-008-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"metrics.document"}$mg$,$mg$row_count > 0$mg$,$mg$Document counters - returned against examined quantifies oversized result sets$mg$,$mg$medium$mg$,$mg$Project and paginate$mg$,$mg$Return only the fields the caller uses and paginate with a range filter on an indexed key rather than large skips. Large result sets cost cache, network and client memory at once.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-QRY-003-RC01$mg$,$mg${"db":"admin","aggregate":[{"$currentOp":{"allUsers":true,"idleSessions":false}},{"$match":{"op":"command","command.pipeline":{"$exists":true}}},{"$project":{"opid":1,"ns":1,"secs_running":1,"planSummary":1}},{"$limit":30}]}$mg$,$mg$row_count > 0$mg$,$mg$Aggregation pipelines currently executing$mg$,$mg$medium$mg$,$mg$Push filters to the front of the pipeline$mg$,$mg$Put $match and $project before $group and $lookup so later stages see fewer documents, and make sure the leading $match is index-served.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-WRT-002-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"wiredTiger.log"}$mg$,$mg$row_count > 0$mg$,$mg$Write-ahead log counters - sync time and slot-join contention expose journal commit latency$mg$,$mg$high$mg$,$mg$Put the journal on faster storage$mg$,$mg$Journal commit latency is bounded by fsync on the data volume. Move to lower-latency storage, or relax the write concern journal option where the durability trade-off is acceptable.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-WRT-004-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"opcounters"}$mg$,$mg$row_count > 0$mg$,$mg$Operation counters by type - many single inserts rather than batched ones show as a high insert count$mg$,$mg$low$mg$,$mg$Batch writes$mg$,$mg$Use bulkWrite or insertMany instead of per-document calls. Each unbatched write costs a full round trip and its own journal commit.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-WRT-008-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"flowControl"}$mg$,$mg$row_count > 0$mg$,$mg$Flow-control counters - a rising isLagged/timeAcquiringMicros means writes are being throttled to let secondaries catch up$mg$,$mg$high$mg$,$mg$Fix the replication lag behind the throttle$mg$,$mg$Flow control deliberately slows the primary when the majority commit point falls behind. Address the slow secondary - its disk, its CPU, or the network to it - rather than disabling flow control.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-SHD-003-RC01$mg$,$mg${"db":"config","collection":"chunks","find":{"jumbo":true},"projection":{"ns":1,"shard":1,"min":1,"max":1},"limit":50}$mg$,$mg$row_count > 0$mg$,$mg$Chunks flagged jumbo - too large to migrate, so the balancer cannot move them$mg$,$mg$high$mg$,$mg$Split or refine the shard key behind jumbo chunks$mg$,$mg$A jumbo chunk exceeds the chunk size and cannot be split on the current key, so distribution stays skewed. Refine the shard key to add cardinality, then clear the jumbo flag once the chunk splits.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-SHD-004-RC01$mg$,$mg${"db":"config","collection":"chunks","aggregate":[{"$group":{"_id":"$shard","chunks":{"$sum":1}}},{"$sort":{"chunks":-1}}]}$mg$,$mg$row_count > 0$mg$,$mg$Chunk count per shard - a wide spread means distribution is unbalanced$mg$,$mg$medium$mg$,$mg$Let the balancer even out the chunks$mg$,$mg$Confirm the balancer is running and its window is open. If counts stay skewed with the balancer active, the shard key is the cause, not the balancer.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$PERF-DOC-SHD-006-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"shardingStatistics"}$mg$,$mg$row_count > 0$mg$,$mg$Sharding statistics including range-deleter progress, which is where orphaned documents accumulate$mg$,$mg$medium$mg$,$mg$Let the range deleter drain$mg$,$mg$Orphans are documents left behind after a migration. The range deleter clears them in the background; a persistent backlog usually means it is starved by write load or blocked by open cursors on the range.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-AUTH-005-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"security.authentication.mechanisms.SCRAM-SHA-256.speculativeAuthenticate"}$mg$,$mg$row_count > 0$mg$,$mg$Authentication attempt counters - received against successful exposes failed authentications$mg$,$mg$medium$mg$,$mg$Investigate failed authentications$mg$,$mg$A gap between received and successful means repeated failures - either a stale credential in a deployed client, or credential stuffing. Correlate with source addresses in the mongod log before assuming the benign case.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-AUTH-010-RC01$mg$,$mg${"command":{"getParameter":1,"localLogicalSessionTimeoutMinutes":1}}$mg$,$mg$localLogicalSessionTimeoutMinutes > 30$mg$,$mg$Logical session timeout exceeds 30 minutes - abandoned sessions stay usable far too long$mg$,$mg$medium$mg$,$mg$Shorten the logical session timeout$mg$,$mg$Lower localLogicalSessionTimeoutMinutes so abandoned sessions expire promptly. Long-lived sessions keep transactions and cursors alive and widen the window for reuse of a stolen session.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-ENC-002-RC01$mg$,$mg${"command":{"getParameter":1,"opensslCipherConfig":1}}$mg$,$mg$row_count > 0$mg$,$mg$Configured OpenSSL cipher suite - permissive suites allow downgrade to weak ciphers$mg$,$mg$high$mg$,$mg$Restrict the cipher suite and minimum TLS version$mg$,$mg$Set net.tls.disabledProtocols to TLS1_0,TLS1_1 and pin a modern cipher config. Leaving the default permits negotiation down to ciphers that no longer meet policy.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-ENC-005-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"transportSecurity"}$mg$,$mg$row_count > 0$mg$,$mg$Transport security counters by TLS version - traffic on 1.0/1.1 indicates outdated clients or certificates$mg$,$mg$high$mg$,$mg$Retire outdated TLS clients and renew certificates$mg$,$mg$Any non-zero count on TLS 1.0/1.1 identifies clients that must be upgraded before you can disable those protocols. Check certificate expiry at the same time.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-DAT-001-RC01$mg$,$mg${"db":"admin","command":{"listDatabases":1,"nameOnly":false},"path":"databases"}$mg$,$mg$row_count > 0$mg$,$mg$Databases with their sizes - the inventory a data-classification review starts from$mg$,$mg$medium$mg$,$mg$Classify each database and encrypt what holds PII$mg$,$mg$Map every database to a data owner and classification. Any holding personal data needs field-level encryption or an equivalent control, plus a documented retention rule.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-NET-001-RC01$mg$,$mg${"command":{"getCmdLineOpts":1},"path":"parsed.processManagement"}$mg$,$mg$row_count > 0$mg$,$mg$Process management configuration - fork/pidfile settings alongside the network exposure review$mg$,$mg$medium$mg$,$mg$Review the exposure of the mongod process$mg$,$mg$Combine with the bindIp finding and a firewall review. A database reachable beyond its application tier should be moved behind a private subnet or security group.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$SEC-DOC-AUD-003-RC01$mg$,$mg${"command":{"getLog":"global"},"path":"totalLinesWritten"}$mg$,$mg$row_count > 0$mg$,$mg$In-memory log ring size - the only retention available when no audit log is configured$mg$,$mg$medium$mg$,$mg$Ship logs off the server$mg$,$mg$The in-memory log ring is small and lost on restart. Forward mongod logs to a retained store so authentication and DDL history survives long enough to satisfy retention policy.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-HA-002-RC01$mg$,$mg${"command":{"replSetGetConfig":1},"path":"config.members"}$mg$,$mg$row_count < 3$mg$,$mg$Replica set has fewer than three voting members - a single loss costs the majority$mg$,$mg$high$mg$,$mg$Bring the set to three voting members$mg$,$mg$With two members a single failure loses the majority and the set goes read-only. Add a third data-bearing member, or an arbiter where a third copy is not affordable.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-HA-006-RC01$mg$,$mg${"command":{"replSetGetConfig":1},"path":"config.members"}$mg$,$mg$priority = 0$mg$,$mg$Members configured with priority 0 can never be elected primary$mg$,$mg$medium$mg$,$mg$Review member priorities$mg$,$mg$Priority 0 is correct for analytics or hidden members but a mistake on a member you expect to take over. Confirm at least two members can be elected.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-REP-007-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"metrics.repl.network"}$mg$,$mg$row_count > 0$mg$,$mg$Replication network counters - ops and bytes fetched against getmores shows how well a secondary keeps up$mg$,$mg$high$mg$,$mg$Close the gap on the lagging secondary$mg$,$mg$Compare the fetch rate with the primary's write rate. A secondary that cannot match it falls behind until it drops off the oplog and needs a full resync.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-REP-009-RC01$mg$,$mg${"command":{"replSetGetStatus":1},"path":"members"}$mg$,$mg$lastHeartbeatMessage != ''$mg$,$mg$Members reporting a heartbeat message - any text here is the primary explaining why contact failed$mg$,$mg$high$mg$,$mg$Resolve the heartbeat error$mg$,$mg$An empty heartbeat message is the healthy case. Text usually names the cause directly - refused connection, TLS mismatch, or authentication failure between members.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-REP-010-RC01$mg$,$mg${"command":{"replSetGetConfig":1},"path":"config.members"}$mg$,$mg$arbiterOnly = true$mg$,$mg$Arbiter members present - arbiters vote but hold no data$mg$,$mg$medium$mg$,$mg$Reconsider the arbiter$mg$,$mg$An arbiter in a two-member set restores a voting majority but leaves only one data copy, so a single node loss is still data loss. Prefer a third data-bearing member.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-BAK-004-RC01$mg$,$mg${"db":"local","collection":"oplog.rs","find":{},"projection":{"ts":1},"sort":{"$natural":1},"limit":1}$mg$,$mg$row_count > 0$mg$,$mg$Oldest oplog entry - its timestamp is the earliest point recoverable without a restore$mg$,$mg$high$mg$,$mg$Extend the oplog to cover the recovery objective$mg$,$mg$The oldest oplog entry defines the PITR floor. If it is more recent than your recovery objective, grow the oplog with replSetResizeOplog and take backups more often.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-BAK-009-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"metrics.changeStreams"}$mg$,$mg$row_count > 0$mg$,$mg$Change stream counters - a growing backlog means downstream consumers are behind$mg$,$mg$medium$mg$,$mg$Speed up change stream consumers$mg$,$mg$A consumer that cannot keep pace eventually asks for a resume token no longer in the oplog and must resynchronise from scratch. Scale the consumer or widen the oplog.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-STG-002-RC01$mg$,$mg${"db":"appdb","collection":"orders","aggregate":[{"$collStats":{"storageStats":{}}},{"$project":{"freeStorageSize":"$storageStats.freeStorageSize","storageSize":"$storageStats.storageSize"}}]}$mg$,$mg$freeStorageSize > 0$mg$,$mg$Reclaimable free space inside the collection's storage - space deleted but not returned to the filesystem$mg$,$mg$medium$mg$,$mg$Compact to return free space$mg$,$mg$freeStorageSize is space WiredTiger holds but no longer uses. Run compact on a secondary and step it over, or resync members one at a time to return it to the filesystem.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-STG-006-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"queues.execution"}$mg$,$mg$row_count > 0$mg$,$mg$Execution ticket pools (queues.execution) - available tickets falling toward zero means storage IO is the bottleneck$mg$,$mg$high$mg$,$mg$Relieve the storage bottleneck$mg$,$mg$WiredTiger admits a fixed number of concurrent operations. Exhausted tickets mean operations queue on IO: move to faster disks, or cut the IO each query performs.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-STG-007-RC01$mg$,$mg${"command":{"serverStatus":1},"path":"wiredTiger.connection"}$mg$,$mg$row_count > 0$mg$,$mg$WiredTiger connection statistics, including files currently open and memory allocations$mg$,$mg$low$mg$,$mg$Track journal and file growth$mg$,$mg$Use alongside the filesystem headroom check. Steady growth in open files or allocations without a matching data increase is worth explaining before it becomes a space problem.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-MNT-004-RC01$mg$,$mg${"db":"appdb","collection":"orders","aggregate":[{"$indexStats":{}},{"$project":{"name":1,"since":"$accesses.since","ops":"$accesses.ops"}}]}$mg$,$mg$row_count > 0$mg$,$mg$Index usage counters with the timestamp they were reset - the window any usage judgement rests on$mg$,$mg$low$mg$,$mg$Judge index usage over a full business cycle$mg$,$mg$accesses.since resets on restart, so a short window makes healthy indexes look unused. Confirm across a full cycle, and on every member, before dropping anything.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-UPG-004-RC01$mg$,$mg${"command":{"buildInfo":1},"path":"modules"}$mg$,$mg$row_count = 0$mg$,$mg$Server modules - an empty list is MongoDB Community, so Enterprise-only controls are unavailable$mg$,$mg$medium$mg$,$mg$Match feature expectations to the edition$mg$,$mg$Community has no auditing, no native encryption at rest, no LDAP or Kerberos. Where policy requires them, either move to Enterprise or implement the control outside the database and record the compensating measure.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-LOG-003-RC01$mg$,$mg${"command":{"getParameter":1,"logLevel":1}}$mg$,$mg$logLevel > 0$mg$,$mg$Global log verbosity above the default - verbose logging costs IO and fills the disk$mg$,$mg$medium$mg$,$mg$Return log verbosity to the default$mg$,$mg$Set logLevel back to 0 once debugging is finished. Verbose logging is frequently left on after an incident and quietly becomes the next disk-full.$mg$);
INSERT INTO _mongo_seed VALUES ($mg$HLTH-DOC-CLU-003-RC01$mg$,$mg${"db":"config","collection":"shards","find":{},"projection":{"_id":1,"host":1,"state":1},"limit":50}$mg$,$mg$row_count > 0$mg$,$mg$Registered shards and their hosts - the inventory config server availability is judged against$mg$,$mg$critical$mg$,$mg$Restore config server availability$mg$,$mg$Config servers hold cluster metadata; without them mongos cannot route and the cluster is effectively down. Confirm the config replica set has a primary before investigating individual shards.$mg$);

-- ---------------------------------------------------------------------------
-- Replay the add-only contract for every seeded root cause.
-- ---------------------------------------------------------------------------
DO $do$
DECLARE
    r         record;
    lstep     bigint;
    lpath     bigint;
    lres_step bigint;
    lres_path bigint;
    n_added   integer := 0;
    has_is_enabled boolean;
    t         text;
    seqname   text;
BEGIN
    SELECT EXISTS (SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'rootcause' AND table_name = 'root_causes'
                      AND column_name = 'is_enabled')
      INTO has_is_enabled;

    -- Catalogs that predate migration 127 have no sequence default on these id columns, so a
    -- plain INSERT ... RETURNING id fails with a NOT NULL violation (seen on a dump-source
    -- catalog). Attach the sequence the same way 127 does, only where it is missing.
    FOREACH t IN ARRAY ARRAY['detection_steps','detection_paths','detection_path_steps',
                             'resolution_steps','resolution_paths','resolution_path_steps'] LOOP
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                        WHERE table_schema='rootcause' AND table_name=t
                          AND column_name='id' AND column_default IS NOT NULL) THEN
            seqname := format('rootcause.%I', t || '_id_seq');
            EXECUTE format('CREATE SEQUENCE IF NOT EXISTS %s', seqname);
            EXECUTE format('SELECT setval(%L, COALESCE((SELECT max(id) FROM rootcause.%I), 0) + 1, false)',
                           seqname, t);
            EXECUTE format('ALTER TABLE rootcause.%I ALTER COLUMN id SET DEFAULT nextval(%L)', t, seqname);
            RAISE NOTICE 'attached missing id sequence to rootcause.% (pre-127 catalog)', t;
        END IF;
    END LOOP;
    FOR r IN SELECT * FROM _mongo_seed ORDER BY rc LOOP
        -- The root cause must actually exist in this catalog (installs whose dump
        -- predates the DOC taxonomy simply skip it rather than fail the upgrade).
        IF NOT EXISTS (SELECT 1 FROM rootcause.root_causes WHERE root_cause_id = r.rc) THEN
            RAISE NOTICE 'skip % - not present in this catalog', r.rc;
            CONTINUE;
        END IF;

        IF EXISTS (SELECT 1 FROM rootcause.detection_paths
                    WHERE root_cause_id = r.rc AND vendor_slug = 'mongodb') THEN
            CONTINUE;                      -- already seeded: no-op on re-run
        END IF;

        -- ---- detection ----
        INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
             VALUES ('mongodb', 'query', format('Detect %s (mongodb)', r.rc),
                     jsonb_build_object('sql', r.spec),
                     jsonb_build_object('condition', r.cond, 'description', r.descr))
          RETURNING id INTO lstep;

        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
             VALUES (r.rc, 'mongodb', format('Detect %s (mongodb)', r.rc), r.descr, 'diagnostic', true)
          RETURNING id INTO lpath;

        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence,
                                                    on_match_action, on_no_match_action)
             VALUES (lpath, lstep, 1, 'confirmed', 'ruled_out');

        -- ---- resolution (v_rootcauses INNER JOINs this chain: without it the
        --      root cause stays invisible no matter how good the detection is) ----
        IF NOT EXISTS (SELECT 1 FROM rootcause.resolution_paths
                        WHERE root_cause_id = r.rc AND vendor_slug = 'mongodb') THEN
            -- rootcause.resolution_steps carries UNIQUE (vendor_slug, name), so a blind INSERT
            -- aborts the whole migration if a step of this name already exists — and
            -- apply_migrations is best-effort, so that would ship as a SILENT no-op
            -- (the v0.12.0/v0.12.1 failure mode called out in docs/RELEASING.md). Reuse the
            -- existing step instead; steps are shared content, only the path is per root cause.
            SELECT id INTO lres_step
              FROM rootcause.resolution_steps
             WHERE vendor_slug = 'mongodb' AND name = r.res_name
             ORDER BY id LIMIT 1;

            IF lres_step IS NULL THEN
                INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content,
                                                        risk_level, requires_confirmation,
                                                        is_reversible, estimated_duration)
                     VALUES ('mongodb', 'recommendation', r.res_name,
                             jsonb_build_object('text', r.res_text),
                             r.risk, true, true, '00:30:00')
                  RETURNING id INTO lres_step;
            END IF;

            INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description,
                                                    execution_mode, risk_level, status, is_active)
                 VALUES (r.rc, 'mongodb', r.res_name, r.rc || '-mongodb', r.res_text,
                         'manual', r.risk, 'authored', true)
              RETURNING id INTO lres_path;

            INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order)
                 VALUES (lres_path, lres_step, 1);
        END IF;

        -- ---- make it applicable ----
        UPDATE rootcause.root_causes
           SET vendors_applicable = (SELECT array(SELECT DISTINCT unnest(coalesce(vendors_applicable, ARRAY[]::text[]) || ARRAY['mongodb']) ORDER BY 1))
         WHERE root_cause_id = r.rc;

        -- ---- re-enable ----
        -- Migration 008 disabled every DOC root cause because none carried detection
        -- logic. These now do, which is precisely 008's own re-enable rule, so flip
        -- them (and their issue) back on. Guarded on the column existing: 008 adds
        -- is_enabled and sorts before this file, but catalogs predating it must not
        -- fail the upgrade.
        IF has_is_enabled THEN
            EXECUTE 'UPDATE rootcause.root_causes SET is_enabled = true WHERE root_cause_id = $1'
                USING r.rc;
            EXECUTE 'UPDATE rootcause.issues i SET is_enabled = true FROM rootcause.root_causes rc'
                 || ' WHERE rc.root_cause_id = $1 AND i.issue_id = rc.issue_id'
                USING r.rc;
        END IF;

        n_added := n_added + 1;
    END LOOP;

    RAISE NOTICE 'mongodb DOC detections seeded: % root cause(s)', n_added;
END $do$;

DROP TABLE _mongo_seed;

COMMIT;
