-- ===========================================================================
-- 5020_insert_sec_sql_qe_001_proc_duration_anomaly.sql
-- Creates issue SEC-SQL-QE-001 + root cause SEC-SQL-QE-001-RC01
--   'Stored procedure slower than its historical average' (SQL Server).
-- Generated from specs/proc_duration_anomaly.json via gen_rootcause_module.py;
-- issue insert prepended. Idempotent (ON CONFLICT / CREATE OR REPLACE).
-- ===========================================================================
-- ===========================================================================
-- Auto-generated by gen_rootcause_module.py from specs/proc_duration_anomaly.json
-- Module: proc_duration_anomaly   Root causes: 1   Vendors: sqlserver
-- DO NOT hand-edit; edit the spec and regenerate.
-- ===========================================================================

-- 0) ISSUE (parent of the root cause) ------------------------------------
INSERT INTO rootcause.issues (issue_id, domain_code, database_type_code, area_code, name, slug, description, category_id)
VALUES ('SEC-SQL-QE-001','SEC','SQL','QE','Anomalous Query/Procedure Execution',
        'anomalous-query-procedure-execution',
        'Queries or stored procedures executing abnormally relative to their baseline (e.g. running far longer than their historical average), which may indicate performance regressions or anomalous/abusive activity.',
        'c001')
ON CONFLICT (issue_id) DO NOTHING;

-- 1) ROOT CAUSES -----------------------------------------------------------
INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-QE-001-RC01', 'SEC-SQL-QE-001', 'Stored procedure slower than its historical average',
    'stored-procedure-slower-than-average', 'A user stored procedure is executing slower than that procedure''s own historical average duration. System (''sys'') procedures and system databases are excluded. Sustained or repeated regressions can indicate parameter sniffing, stale statistics, plan changes, blocking/resource contention, or anomalous/abusive use.',
    ARRAY['stored procedure', 'execution duration', 'performance regression', 'anomaly'], ARRAY['sqlserver']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

-- 2) DETECTION STEPS (per vendor) ------------------------------------------
INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('sqlserver', 'query', 'Detect SEC-SQL-QE-001-RC01 (sqlserver)',
        '{"sql": "SELECT @@SERVERNAME AS server, DB_NAME(r.database_id) AS database_name, OBJECT_SCHEMA_NAME(st.objectid, r.database_id) + ''.'' + OBJECT_NAME(st.objectid, r.database_id) AS procedure_name, s.login_name AS login_name, ps.total_elapsed_time / NULLIF(ps.execution_count, 0) / 1000.0 AS avg_duration_ms, r.total_elapsed_time / 1000.0 AS actual_duration_ms FROM sys.dm_exec_requests r JOIN sys.dm_exec_sessions s ON s.session_id = r.session_id CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) st JOIN sys.dm_exec_procedure_stats ps ON ps.object_id = st.objectid AND ps.database_id = r.database_id WHERE s.is_user_process = 1 AND st.objectid IS NOT NULL AND OBJECT_SCHEMA_NAME(st.objectid, r.database_id) <> ''sys'' AND DB_NAME(r.database_id) NOT IN (''master'',''model'',''msdb'',''tempdb'') AND (r.total_elapsed_time * 1000.0) > (ps.total_elapsed_time / NULLIF(ps.execution_count, 0)) ORDER BY actual_duration_ms DESC"}'::jsonb,
        '{"condition": "row_count > 0", "description": "A user stored procedure executed slower than its own historical average duration"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO NOTHING;

-- 3) DETECTION PATHS + RESOLUTION (per root cause x vendor) ----------------
DO $gen$
DECLARE
    v_step_id   bigint;
    v_path_id   bigint;
    v_res_step  bigint;
    v_res_path  bigint;
BEGIN
    -- SEC-SQL-QE-001-RC01 / sqlserver
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'sqlserver' AND name = 'Detect SEC-SQL-QE-001-RC01 (sqlserver)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-QE-001-RC01' AND vendor_slug = 'sqlserver') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-QE-001-RC01', 'sqlserver', 'Detect SEC-SQL-QE-001-RC01 (sqlserver)', 'Stored procedure slower than its historical average', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('sqlserver', 'recommendation', 'Resolve: Detect SEC-SQL-QE-001-RC01 (sqlserver)', '{"action": "Identify the procedure and compare the slow execution to its Query Store / cached-plan baseline. Check for parameter sniffing (test OPTION(RECOMPILE)), update statistics, look for blocking or resource contention during the slow run, and review recent plan changes. If the slowdown correlates with unusual callers or data volumes, investigate for anomalous or abusive use."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-QE-001-RC01', 'sqlserver', 'Resolve: Detect SEC-SQL-QE-001-RC01 (sqlserver)', 'resolve-sec_sql_qe_001_rc01-sqlserver', 'Identify the procedure and compare the slow execution to its Query Store / cached-plan baseline. Check for parameter sniffing (test OPTION(RECOMPILE)), update statistics, look for blocking or resource contention during the slow run, and review recent plan changes. If the slowdown correlates with unusual callers or data volumes, investigate for anomalous or abusive use.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
END
$gen$;

-- 4) MONITORING VIEWS (one per root cause) ---------------------------------
CREATE OR REPLACE VIEW monitoring.v_sec_sql_qe_001_rc01 AS
SELECT r.server,
    (j.value ->> 'procedure_name') AS procedure_name,
    (j.value ->> 'database_name') AS database_name,
    (j.value ->> 'login_name') AS login_name,
    (j.value ->> 'avg_duration_ms') AS avg_duration_ms,
    (j.value ->> 'actual_duration_ms') AS actual_duration_ms,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-QE-001-RC01';

-- 5) VERIFY ----------------------------------------------------------------
SELECT root_cause_id, name, vendors_applicable FROM rootcause.root_causes
 WHERE root_cause_id IN ('SEC-SQL-QE-001-RC01');
