-- ===========================================================================
-- 5040_insert_sec_sql_acc_011_rc02_active_transactions.sql
-- Root cause SEC-SQL-ACC-011-RC02 'Active transactions (excluding monitoring user)'
-- under existing issue SEC-SQL-ACC-011. SQL Server. Idempotent.
-- ===========================================================================
-- ===========================================================================
-- Auto-generated by gen_rootcause_module.py from specs/active_transactions_excl_mon.json
-- Module: active_transactions_excl_mon   Root causes: 1   Vendors: sqlserver
-- DO NOT hand-edit; edit the spec and regenerate.
-- ===========================================================================

-- 0) ISSUE (idempotent — so the script is self-contained on a fresh DB;
--    v_rootcauses inner-joins issues, so a missing parent issue = no rows) ----
INSERT INTO rootcause.issues (issue_id, domain_code, database_type_code, area_code, name, slug, description, category_id)
VALUES ('SEC-SQL-ACC-011','SEC','SQL','ACC','Active Transactions Present',
        'active-transactions-present',
        'Sessions are holding open (in-flight) transactions. Surfacing the active transactions - who is running them, against which database, how long they have been open, and the SQL text - is the starting point for spotting long-running / abandoned transactions, blocking, and anomalous or unauthorized activity.',
        NULL)
ON CONFLICT (issue_id) DO NOTHING;

-- 1) ROOT CAUSES -----------------------------------------------------------
INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-ACC-011-RC02', 'SEC-SQL-ACC-011', 'Active transactions (excluding monitoring user)',
    'active-transactions-excluding-monitoring-user', 'All currently open / in-flight user transactions on the instance, excluding the dbdome monitoring login (dbd_mon_usr / dbdome_mon_usr). Surfaces who is holding a transaction, against which database, for how long, the transaction state and the SQL text - for spotting long-running or abandoned transactions, blocking, and anomalous activity.',
    ARRAY['active transactions', 'in-flight transactions', 'blocking', 'long-running transaction', 'monitoring'], ARRAY['sqlserver']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

-- 2) DETECTION STEPS (per vendor) ------------------------------------------
INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('sqlserver', 'query', 'Detect SEC-SQL-ACC-011-RC02 (sqlserver)',
        '{"sql": "SELECT\n    @@SERVERNAME AS server,\n    s.session_id,\n    s.login_name,\n    s.host_name,\n    s.program_name,\n    DB_NAME(s.database_id) AS database_name,\n    t.transaction_id,\n    tat.transaction_begin_time,\n    DATEDIFF(SECOND, tat.transaction_begin_time, GETDATE()) AS duration_seconds,\n    tat.transaction_state,\n    SUBSTRING(st.text, 1, 4000) AS query_text\nFROM sys.dm_tran_active_transactions tat\nJOIN sys.dm_tran_session_transactions t ON t.transaction_id = tat.transaction_id\nJOIN sys.dm_exec_sessions s ON s.session_id = t.session_id\nLEFT JOIN sys.dm_exec_connections c ON c.session_id = s.session_id\nOUTER APPLY sys.dm_exec_sql_text(c.most_recent_sql_handle) st\nWHERE s.is_user_process = 1\n  AND s.login_name NOT IN (''dbd_mon_usr'',''dbdome_mon_usr'')\nORDER BY tat.transaction_begin_time"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Open user transactions are present (excluding the monitoring account)"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO NOTHING;

-- 3) DETECTION PATHS + RESOLUTION (per root cause x vendor) ----------------
DO $gen$
DECLARE
    v_step_id   bigint;
    v_path_id   bigint;
    v_res_step  bigint;
    v_res_path  bigint;
BEGIN
    -- SEC-SQL-ACC-011-RC02 / sqlserver
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'sqlserver' AND name = 'Detect SEC-SQL-ACC-011-RC02 (sqlserver)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-ACC-011-RC02' AND vendor_slug = 'sqlserver') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-ACC-011-RC02', 'sqlserver', 'Detect SEC-SQL-ACC-011-RC02 (sqlserver)', 'Active transactions (excluding monitoring user)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('sqlserver', 'recommendation', 'Resolve: Detect SEC-SQL-ACC-011-RC02 (sqlserver)', '{"action": "Review long-running or abandoned transactions: identify the session/login, database, duration and SQL text; chase blocking chains and transactions open beyond expected thresholds. Persistent open transactions from application logins may indicate a missing COMMIT/ROLLBACK."}'::jsonb, 'low', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-ACC-011-RC02', 'sqlserver', 'Resolve: Detect SEC-SQL-ACC-011-RC02 (sqlserver)', 'resolve-sec_sql_acc_011_rc02-sqlserver', 'Review long-running or abandoned transactions: identify the session/login, database, duration and SQL text; chase blocking chains and transactions open beyond expected thresholds. Persistent open transactions from application logins may indicate a missing COMMIT/ROLLBACK.', 'supervised', 'low', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
END
$gen$;

-- 4) MONITORING VIEW: defined in 1055_create_view_v_sec_sql_acc_011_rc02.sql
--    (kept as a single source so the runner's create_view file is authoritative).

-- 5) VERIFY ----------------------------------------------------------------
SELECT root_cause_id, name, vendors_applicable FROM rootcause.root_causes
 WHERE root_cause_id IN ('SEC-SQL-ACC-011-RC02');
