-- ============================================================
-- 6320  SEC-SQL-AUD-022-RC01  Unsuccessful (failed) database authentication attempts
--   Oracle (UNIFIED_AUDIT_TRAIL return_code<>0), SQL Server (xp_readerrorlog 'Login failed'),
--   MySQL/MariaDB (performance_schema.host_cache auth errors). Verify with an invalid password.
--   Postgres/Informix log failures to the OS log only (not SQL-queryable) - excluded.
--   Idempotent (rebuilds the RC cleanly).
-- ============================================================

-- ===========================================================================
-- Auto-generated by gen_rootcause_module.py from specs/failed_auth.json
-- Module: failed_auth   Root causes: 1   Vendors: oracle, sqlserver, mysql, mariadb
-- DO NOT hand-edit; edit the spec and regenerate.
-- ===========================================================================
BEGIN;

-- 0) ISSUE + cleanup (idempotent rebuild) ------------------------------
INSERT INTO rootcause.issues (issue_id, domain_code, database_type_code, area_code, name, slug, description, created_at, updated_at)
VALUES ('SEC-SQL-AUD-022','SEC','SQL','AUD','Unsuccessful database authentication attempts','failed-db-auth-attempts','Detect failed database login attempts (invalid password / brute force).',now(),now())
ON CONFLICT (issue_id) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
DELETE FROM rootcause.detection_path_steps WHERE detection_path_id IN (SELECT id FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-022-RC01');
DELETE FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-022-RC01';
DELETE FROM rootcause.detection_steps WHERE name LIKE 'Detect SEC-SQL-AUD-022-RC01 %';
DELETE FROM rootcause.resolution_path_steps WHERE resolution_path_id IN (SELECT id FROM rootcause.resolution_paths WHERE root_cause_id='SEC-SQL-AUD-022-RC01');
DELETE FROM rootcause.resolution_paths WHERE root_cause_id='SEC-SQL-AUD-022-RC01';
DELETE FROM rootcause.resolution_steps WHERE name LIKE 'Resolve: Detect SEC-SQL-AUD-022-RC01 %';


-- 1) ROOT CAUSES -----------------------------------------------------------
INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-AUD-022-RC01', 'SEC-SQL-AUD-022', 'Unsuccessful database authentication attempts detected',
    'failed-db-authentication', 'Detects failed (unsuccessful) database login attempts - e.g. an invalid password. Oracle: UNIFIED_AUDIT_TRAIL LOGON with return_code <> 0 (1017 = invalid credentials). SQL Server: xp_readerrorlog ''Login failed'' from the ERRORLOG (default failed-login auditing). MySQL/MariaDB: performance_schema.host_cache.COUNT_AUTHENTICATION_ERRORS. Verify by attempting a login with an invalid password.',
    ARRAY['audit', 'authentication', 'failed-login', 'brute-force', 'security'], ARRAY['oracle', 'sqlserver', 'mysql', 'mariadb']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

-- 2) DETECTION STEPS (per vendor) ------------------------------------------
INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('oracle', 'query', 'Detect SEC-SQL-AUD-022-RC01 (oracle)',
        '{"sql": "SELECT TO_CHAR(event_timestamp,''YYYY-MM-DD HH24:MI:SS'') AS event_time, dbusername AS login_name,\n       userhost AS host_name, os_username AS os_user,\n       ''ORA-''||LPAD(TO_CHAR(return_code),5,''0'') AS error_info, TO_CHAR(return_code) AS attempts\nFROM unified_audit_trail WHERE action_name=''LOGON'' AND return_code <> 0\n  AND event_timestamp > SYSTIMESTAMP - INTERVAL ''1'' DAY\nORDER BY event_timestamp DESC FETCH FIRST 500 ROWS ONLY"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Failed database authentication attempts are present"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('sqlserver', 'query', 'Detect SEC-SQL-AUD-022-RC01 (sqlserver)',
        '{"sql": "SET NOCOUNT ON;\nBEGIN TRY\n  DECLARE @el TABLE (LogDate datetime, ProcessInfo nvarchar(100), LogText nvarchar(4000));\n  INSERT INTO @el EXEC sys.xp_readerrorlog 0, 1, N''Login failed'';\n  SELECT TOP 500 CONVERT(varchar(19), LogDate, 120) AS event_time, CAST(NULL AS sysname) AS login_name,\n         CAST(NULL AS sysname) AS host_name, CAST(NULL AS sysname) AS os_user,\n         LogText AS error_info, ProcessInfo AS attempts\n  FROM @el WHERE LogDate > DATEADD(DAY,-1, GETDATE()) ORDER BY LogDate DESC;\nEND TRY\nBEGIN CATCH\n  SELECT CAST(NULL AS varchar(19)) AS event_time, CAST(NULL AS sysname) AS login_name,\n         CAST(NULL AS sysname) AS host_name, CAST(NULL AS sysname) AS os_user,\n         CAST(NULL AS nvarchar(4000)) AS error_info, CAST(NULL AS nvarchar(100)) AS attempts WHERE 1=0;\nEND CATCH"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Failed database authentication attempts are present"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('mysql', 'query', 'Detect SEC-SQL-AUD-022-RC01 (mysql)',
        '{"sql": "SELECT DATE_FORMAT(LAST_ERROR_SEEN,''%Y-%m-%d %H:%i:%s'') AS event_time, NULL AS login_name,\n       HOST AS host_name, IP AS os_user, CONCAT(''auth_errors='', COUNT_AUTHENTICATION_ERRORS) AS error_info,\n       COUNT_AUTHENTICATION_ERRORS AS attempts\nFROM performance_schema.host_cache WHERE COUNT_AUTHENTICATION_ERRORS > 0\nORDER BY LAST_ERROR_SEEN DESC LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Failed database authentication attempts are present"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('mariadb', 'query', 'Detect SEC-SQL-AUD-022-RC01 (mariadb)',
        '{"sql": "SELECT DATE_FORMAT(LAST_ERROR_SEEN,''%Y-%m-%d %H:%i:%s'') AS event_time, NULL AS login_name,\n       HOST AS host_name, IP AS os_user, CONCAT(''auth_errors='', COUNT_AUTHENTICATION_ERRORS) AS error_info,\n       COUNT_AUTHENTICATION_ERRORS AS attempts\nFROM performance_schema.host_cache WHERE COUNT_AUTHENTICATION_ERRORS > 0\nORDER BY LAST_ERROR_SEEN DESC LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Failed database authentication attempts are present"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

-- 3) DETECTION PATHS + RESOLUTION (per root cause x vendor) ----------------
DO $gen$
DECLARE
    v_step_id   bigint;
    v_path_id   bigint;
    v_res_step  bigint;
    v_res_path  bigint;
BEGIN
    -- SEC-SQL-AUD-022-RC01 / oracle
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'oracle' AND name = 'Detect SEC-SQL-AUD-022-RC01 (oracle)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-022-RC01' AND vendor_slug = 'oracle') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-022-RC01', 'oracle', 'Detect SEC-SQL-AUD-022-RC01 (oracle)', 'Unsuccessful database authentication attempts detected', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('oracle', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-022-RC01 (oracle)', '{"action": "Investigate the source host / login of the failed attempts. A burst from one host or against one account indicates password guessing / brute force - block the IP, lock the account, and review the authentication logs. Ensure failed-logon auditing is enabled."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-022-RC01', 'oracle', 'Resolve: Detect SEC-SQL-AUD-022-RC01 (oracle)', 'resolve-sec_sql_aud_022_rc01-oracle', 'Investigate the source host / login of the failed attempts. A burst from one host or against one account indicates password guessing / brute force - block the IP, lock the account, and review the authentication logs. Ensure failed-logon auditing is enabled.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-022-RC01 / sqlserver
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'sqlserver' AND name = 'Detect SEC-SQL-AUD-022-RC01 (sqlserver)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-022-RC01' AND vendor_slug = 'sqlserver') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-022-RC01', 'sqlserver', 'Detect SEC-SQL-AUD-022-RC01 (sqlserver)', 'Unsuccessful database authentication attempts detected', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('sqlserver', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-022-RC01 (sqlserver)', '{"action": "Investigate the source host / login of the failed attempts. A burst from one host or against one account indicates password guessing / brute force - block the IP, lock the account, and review the authentication logs. Ensure failed-logon auditing is enabled."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-022-RC01', 'sqlserver', 'Resolve: Detect SEC-SQL-AUD-022-RC01 (sqlserver)', 'resolve-sec_sql_aud_022_rc01-sqlserver', 'Investigate the source host / login of the failed attempts. A burst from one host or against one account indicates password guessing / brute force - block the IP, lock the account, and review the authentication logs. Ensure failed-logon auditing is enabled.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-022-RC01 / mysql
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'mysql' AND name = 'Detect SEC-SQL-AUD-022-RC01 (mysql)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-022-RC01' AND vendor_slug = 'mysql') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-022-RC01', 'mysql', 'Detect SEC-SQL-AUD-022-RC01 (mysql)', 'Unsuccessful database authentication attempts detected', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('mysql', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-022-RC01 (mysql)', '{"action": "Investigate the source host / login of the failed attempts. A burst from one host or against one account indicates password guessing / brute force - block the IP, lock the account, and review the authentication logs. Ensure failed-logon auditing is enabled."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-022-RC01', 'mysql', 'Resolve: Detect SEC-SQL-AUD-022-RC01 (mysql)', 'resolve-sec_sql_aud_022_rc01-mysql', 'Investigate the source host / login of the failed attempts. A burst from one host or against one account indicates password guessing / brute force - block the IP, lock the account, and review the authentication logs. Ensure failed-logon auditing is enabled.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-022-RC01 / mariadb
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'mariadb' AND name = 'Detect SEC-SQL-AUD-022-RC01 (mariadb)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-022-RC01' AND vendor_slug = 'mariadb') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-022-RC01', 'mariadb', 'Detect SEC-SQL-AUD-022-RC01 (mariadb)', 'Unsuccessful database authentication attempts detected', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('mariadb', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-022-RC01 (mariadb)', '{"action": "Investigate the source host / login of the failed attempts. A burst from one host or against one account indicates password guessing / brute force - block the IP, lock the account, and review the authentication logs. Ensure failed-logon auditing is enabled."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-022-RC01', 'mariadb', 'Resolve: Detect SEC-SQL-AUD-022-RC01 (mariadb)', 'resolve-sec_sql_aud_022_rc01-mariadb', 'Investigate the source host / login of the failed attempts. A burst from one host or against one account indicates password guessing / brute force - block the IP, lock the account, and review the authentication logs. Ensure failed-logon auditing is enabled.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
END
$gen$;

-- 4) MONITORING VIEWS (one per root cause) ---------------------------------
CREATE OR REPLACE VIEW monitoring.v_sec_sql_aud_022_rc01 AS
SELECT r.server,
    (j.value ->> 'event_time') AS event_time,
    (j.value ->> 'login_name') AS login_name,
    (j.value ->> 'host_name') AS host_name,
    (j.value ->> 'os_user') AS os_user,
    (j.value ->> 'error_info') AS error_info,
    (j.value ->> 'attempts') AS attempts,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-AUD-022-RC01';

-- 5) VERIFY ----------------------------------------------------------------
SELECT root_cause_id, name, vendors_applicable FROM rootcause.root_causes
 WHERE root_cause_id IN ('SEC-SQL-AUD-022-RC01');

COMMIT;
