-- ============================================================
-- 6330  SEC-SQL-AUD-023  DBA / administrator activity monitoring
--   RC01 create user, RC02 grant (excessive) privilege, RC03 drop user.
--   oracle (UNIFIED_AUDIT_TRAIL), sqlserver (dm_exec_query_stats plan cache),
--   mysql/mariadb (performance_schema.events_statements_summary_by_digest).
--   Verify by creating a user / granting a privilege / dropping a user.
--   Idempotent (rebuilds the RCs cleanly).
-- ============================================================

-- ===========================================================================
-- Auto-generated by gen_rootcause_module.py from specs/dba_activity.json
-- Module: dba_activity   Root causes: 3   Vendors: oracle, sqlserver, mysql, mariadb
-- DO NOT hand-edit; edit the spec and regenerate.
-- ===========================================================================
BEGIN;

-- 0) ISSUE + cleanup (idempotent rebuild) ------------------------------
INSERT INTO rootcause.issues (issue_id, domain_code, database_type_code, area_code, name, slug, description, created_at, updated_at)
VALUES ('SEC-SQL-AUD-023','SEC','SQL','AUD','DBA and administrator activity monitoring','dba-admin-activity-monitoring','Monitor privileged DBA/administrator actions: create user, grant/modify privileges, drop user.',now(),now())
ON CONFLICT (issue_id) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
DELETE FROM rootcause.detection_path_steps WHERE detection_path_id IN (SELECT id FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-023-RC01');
DELETE FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-023-RC01';
DELETE FROM rootcause.detection_steps WHERE name LIKE 'Detect SEC-SQL-AUD-023-RC01 %';
DELETE FROM rootcause.resolution_path_steps WHERE resolution_path_id IN (SELECT id FROM rootcause.resolution_paths WHERE root_cause_id='SEC-SQL-AUD-023-RC01');
DELETE FROM rootcause.resolution_paths WHERE root_cause_id='SEC-SQL-AUD-023-RC01';
DELETE FROM rootcause.resolution_steps WHERE name LIKE 'Resolve: Detect SEC-SQL-AUD-023-RC01 %';
DELETE FROM rootcause.detection_path_steps WHERE detection_path_id IN (SELECT id FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-023-RC02');
DELETE FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-023-RC02';
DELETE FROM rootcause.detection_steps WHERE name LIKE 'Detect SEC-SQL-AUD-023-RC02 %';
DELETE FROM rootcause.resolution_path_steps WHERE resolution_path_id IN (SELECT id FROM rootcause.resolution_paths WHERE root_cause_id='SEC-SQL-AUD-023-RC02');
DELETE FROM rootcause.resolution_paths WHERE root_cause_id='SEC-SQL-AUD-023-RC02';
DELETE FROM rootcause.resolution_steps WHERE name LIKE 'Resolve: Detect SEC-SQL-AUD-023-RC02 %';
DELETE FROM rootcause.detection_path_steps WHERE detection_path_id IN (SELECT id FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-023-RC03');
DELETE FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-023-RC03';
DELETE FROM rootcause.detection_steps WHERE name LIKE 'Detect SEC-SQL-AUD-023-RC03 %';
DELETE FROM rootcause.resolution_path_steps WHERE resolution_path_id IN (SELECT id FROM rootcause.resolution_paths WHERE root_cause_id='SEC-SQL-AUD-023-RC03');
DELETE FROM rootcause.resolution_paths WHERE root_cause_id='SEC-SQL-AUD-023-RC03';
DELETE FROM rootcause.resolution_steps WHERE name LIKE 'Resolve: Detect SEC-SQL-AUD-023-RC03 %';


-- 1) ROOT CAUSES -----------------------------------------------------------
INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-AUD-023-RC01', 'SEC-SQL-AUD-023', 'User account created (CREATE USER/LOGIN/ROLE)',
    'dba-activity-create-user', 'User account created (CREATE USER/LOGIN/ROLE). Part of DBA / administrator activity monitoring. Oracle reads UNIFIED_AUDIT_TRAIL; SQL Server reads the plan cache (dm_exec_query_stats); MySQL/MariaDB read performance_schema.events_statements_summary_by_digest. Verify by performing the action.',
    ARRAY['audit', 'dba-activity', 'privileged-operation', 'iam', 'security'], ARRAY['oracle', 'sqlserver', 'mysql', 'mariadb']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-AUD-023-RC02', 'SEC-SQL-AUD-023', 'Privileges granted (possible excessive grant)',
    'dba-activity-grant-privilege', 'Privileges granted (possible excessive grant). Part of DBA / administrator activity monitoring. Oracle reads UNIFIED_AUDIT_TRAIL; SQL Server reads the plan cache (dm_exec_query_stats); MySQL/MariaDB read performance_schema.events_statements_summary_by_digest. Verify by performing the action.',
    ARRAY['audit', 'dba-activity', 'privileged-operation', 'iam', 'security'], ARRAY['oracle', 'sqlserver', 'mysql', 'mariadb']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-AUD-023-RC03', 'SEC-SQL-AUD-023', 'User account dropped (DROP USER/LOGIN/ROLE)',
    'dba-activity-drop-user', 'User account dropped (DROP USER/LOGIN/ROLE). Part of DBA / administrator activity monitoring. Oracle reads UNIFIED_AUDIT_TRAIL; SQL Server reads the plan cache (dm_exec_query_stats); MySQL/MariaDB read performance_schema.events_statements_summary_by_digest. Verify by performing the action.',
    ARRAY['audit', 'dba-activity', 'privileged-operation', 'iam', 'security'], ARRAY['oracle', 'sqlserver', 'mysql', 'mariadb']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

-- 2) DETECTION STEPS (per vendor) ------------------------------------------
INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('oracle', 'query', 'Detect SEC-SQL-AUD-023-RC01 (oracle)',
        '{"sql": "SELECT TO_CHAR(event_timestamp,''YYYY-MM-DD HH24:MI:SS'') AS event_time, dbusername AS login_name,\n       userhost AS host_name, os_username AS os_user, action_name AS auth_info, sql_text AS statement\nFROM unified_audit_trail WHERE (action_name IN (''CREATE USER'',''CREATE ROLE''))\n  AND event_timestamp > SYSTIMESTAMP - INTERVAL ''1'' DAY\nORDER BY event_timestamp DESC FETCH FIRST 500 ROWS ONLY"}'::jsonb,
        '{"condition": "row_count > 0", "description": "User account created (CREATE USER/LOGIN/ROLE) detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('sqlserver', 'query', 'Detect SEC-SQL-AUD-023-RC01 (sqlserver)',
        '{"sql": "SELECT TOP 500 qs.last_execution_time AS event_time, CAST(NULL AS sysname) AS login_name,\n       DB_NAME(st.dbid) AS host_name, CAST(NULL AS sysname) AS os_user, ''plan cache'' AS auth_info,\n       CAST(st.text AS NVARCHAR(MAX)) AS statement\nFROM sys.dm_exec_query_stats qs WITH (NOLOCK) OUTER APPLY sys.dm_exec_sql_text(qs.sql_handle) st\nWHERE qs.last_execution_time >= DATEADD(DAY,-1, GETDATE()) AND st.text IS NOT NULL\n  AND st.text NOT LIKE ''%dm_exec_query_stats%'' AND (st.text LIKE ''%CREATE%USER%'' OR st.text LIKE ''%CREATE%LOGIN%'' OR st.text LIKE ''%CREATE%ROLE%'')\nORDER BY qs.last_execution_time DESC"}'::jsonb,
        '{"condition": "row_count > 0", "description": "User account created (CREATE USER/LOGIN/ROLE) detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('mysql', 'query', 'Detect SEC-SQL-AUD-023-RC01 (mysql)',
        '{"sql": "SELECT DATE_FORMAT(LAST_SEEN,''%Y-%m-%d %H:%i:%s'') AS event_time, CAST(NULL AS CHAR) AS login_name,\n       @@hostname AS host_name, CAST(NULL AS CHAR) AS os_user, CONCAT(''count='',COUNT_STAR) AS auth_info,\n       LEFT(DIGEST_TEXT,4000) AS statement\nFROM performance_schema.events_statements_summary_by_digest\nWHERE DIGEST_TEXT IS NOT NULL AND (DIGEST_TEXT LIKE ''%CREATE USER%'' OR DIGEST_TEXT LIKE ''%CREATE ROLE%'')\nORDER BY LAST_SEEN DESC LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "User account created (CREATE USER/LOGIN/ROLE) detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('mariadb', 'query', 'Detect SEC-SQL-AUD-023-RC01 (mariadb)',
        '{"sql": "SELECT DATE_FORMAT(LAST_SEEN,''%Y-%m-%d %H:%i:%s'') AS event_time, CAST(NULL AS CHAR) AS login_name,\n       @@hostname AS host_name, CAST(NULL AS CHAR) AS os_user, CONCAT(''count='',COUNT_STAR) AS auth_info,\n       LEFT(DIGEST_TEXT,4000) AS statement\nFROM performance_schema.events_statements_summary_by_digest\nWHERE DIGEST_TEXT IS NOT NULL AND (DIGEST_TEXT LIKE ''%CREATE USER%'' OR DIGEST_TEXT LIKE ''%CREATE ROLE%'')\nORDER BY LAST_SEEN DESC LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "User account created (CREATE USER/LOGIN/ROLE) detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('oracle', 'query', 'Detect SEC-SQL-AUD-023-RC02 (oracle)',
        '{"sql": "SELECT TO_CHAR(event_timestamp,''YYYY-MM-DD HH24:MI:SS'') AS event_time, dbusername AS login_name,\n       userhost AS host_name, os_username AS os_user, action_name AS auth_info, sql_text AS statement\nFROM unified_audit_trail WHERE (action_name LIKE ''%GRANT%'')\n  AND event_timestamp > SYSTIMESTAMP - INTERVAL ''1'' DAY\nORDER BY event_timestamp DESC FETCH FIRST 500 ROWS ONLY"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Privileges granted (possible excessive grant) detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('sqlserver', 'query', 'Detect SEC-SQL-AUD-023-RC02 (sqlserver)',
        '{"sql": "SELECT TOP 500 qs.last_execution_time AS event_time, CAST(NULL AS sysname) AS login_name,\n       DB_NAME(st.dbid) AS host_name, CAST(NULL AS sysname) AS os_user, ''plan cache'' AS auth_info,\n       CAST(st.text AS NVARCHAR(MAX)) AS statement\nFROM sys.dm_exec_query_stats qs WITH (NOLOCK) OUTER APPLY sys.dm_exec_sql_text(qs.sql_handle) st\nWHERE qs.last_execution_time >= DATEADD(DAY,-1, GETDATE()) AND st.text IS NOT NULL\n  AND st.text NOT LIKE ''%dm_exec_query_stats%'' AND (st.text LIKE ''%GRANT%'')\nORDER BY qs.last_execution_time DESC"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Privileges granted (possible excessive grant) detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('mysql', 'query', 'Detect SEC-SQL-AUD-023-RC02 (mysql)',
        '{"sql": "SELECT DATE_FORMAT(LAST_SEEN,''%Y-%m-%d %H:%i:%s'') AS event_time, CAST(NULL AS CHAR) AS login_name,\n       @@hostname AS host_name, CAST(NULL AS CHAR) AS os_user, CONCAT(''count='',COUNT_STAR) AS auth_info,\n       LEFT(DIGEST_TEXT,4000) AS statement\nFROM performance_schema.events_statements_summary_by_digest\nWHERE DIGEST_TEXT IS NOT NULL AND (DIGEST_TEXT LIKE ''%GRANT%'')\nORDER BY LAST_SEEN DESC LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Privileges granted (possible excessive grant) detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('mariadb', 'query', 'Detect SEC-SQL-AUD-023-RC02 (mariadb)',
        '{"sql": "SELECT DATE_FORMAT(LAST_SEEN,''%Y-%m-%d %H:%i:%s'') AS event_time, CAST(NULL AS CHAR) AS login_name,\n       @@hostname AS host_name, CAST(NULL AS CHAR) AS os_user, CONCAT(''count='',COUNT_STAR) AS auth_info,\n       LEFT(DIGEST_TEXT,4000) AS statement\nFROM performance_schema.events_statements_summary_by_digest\nWHERE DIGEST_TEXT IS NOT NULL AND (DIGEST_TEXT LIKE ''%GRANT%'')\nORDER BY LAST_SEEN DESC LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "Privileges granted (possible excessive grant) detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('oracle', 'query', 'Detect SEC-SQL-AUD-023-RC03 (oracle)',
        '{"sql": "SELECT TO_CHAR(event_timestamp,''YYYY-MM-DD HH24:MI:SS'') AS event_time, dbusername AS login_name,\n       userhost AS host_name, os_username AS os_user, action_name AS auth_info, sql_text AS statement\nFROM unified_audit_trail WHERE (action_name IN (''DROP USER'',''DROP ROLE''))\n  AND event_timestamp > SYSTIMESTAMP - INTERVAL ''1'' DAY\nORDER BY event_timestamp DESC FETCH FIRST 500 ROWS ONLY"}'::jsonb,
        '{"condition": "row_count > 0", "description": "User account dropped (DROP USER/LOGIN/ROLE) detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('sqlserver', 'query', 'Detect SEC-SQL-AUD-023-RC03 (sqlserver)',
        '{"sql": "SELECT TOP 500 qs.last_execution_time AS event_time, CAST(NULL AS sysname) AS login_name,\n       DB_NAME(st.dbid) AS host_name, CAST(NULL AS sysname) AS os_user, ''plan cache'' AS auth_info,\n       CAST(st.text AS NVARCHAR(MAX)) AS statement\nFROM sys.dm_exec_query_stats qs WITH (NOLOCK) OUTER APPLY sys.dm_exec_sql_text(qs.sql_handle) st\nWHERE qs.last_execution_time >= DATEADD(DAY,-1, GETDATE()) AND st.text IS NOT NULL\n  AND st.text NOT LIKE ''%dm_exec_query_stats%'' AND (st.text LIKE ''%DROP%USER%'' OR st.text LIKE ''%DROP%LOGIN%'' OR st.text LIKE ''%DROP%ROLE%'')\nORDER BY qs.last_execution_time DESC"}'::jsonb,
        '{"condition": "row_count > 0", "description": "User account dropped (DROP USER/LOGIN/ROLE) detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('mysql', 'query', 'Detect SEC-SQL-AUD-023-RC03 (mysql)',
        '{"sql": "SELECT DATE_FORMAT(LAST_SEEN,''%Y-%m-%d %H:%i:%s'') AS event_time, CAST(NULL AS CHAR) AS login_name,\n       @@hostname AS host_name, CAST(NULL AS CHAR) AS os_user, CONCAT(''count='',COUNT_STAR) AS auth_info,\n       LEFT(DIGEST_TEXT,4000) AS statement\nFROM performance_schema.events_statements_summary_by_digest\nWHERE DIGEST_TEXT IS NOT NULL AND (DIGEST_TEXT LIKE ''%DROP USER%'' OR DIGEST_TEXT LIKE ''%DROP ROLE%'')\nORDER BY LAST_SEEN DESC LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "User account dropped (DROP USER/LOGIN/ROLE) detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('mariadb', 'query', 'Detect SEC-SQL-AUD-023-RC03 (mariadb)',
        '{"sql": "SELECT DATE_FORMAT(LAST_SEEN,''%Y-%m-%d %H:%i:%s'') AS event_time, CAST(NULL AS CHAR) AS login_name,\n       @@hostname AS host_name, CAST(NULL AS CHAR) AS os_user, CONCAT(''count='',COUNT_STAR) AS auth_info,\n       LEFT(DIGEST_TEXT,4000) AS statement\nFROM performance_schema.events_statements_summary_by_digest\nWHERE DIGEST_TEXT IS NOT NULL AND (DIGEST_TEXT LIKE ''%DROP USER%'' OR DIGEST_TEXT LIKE ''%DROP ROLE%'')\nORDER BY LAST_SEEN DESC LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "User account dropped (DROP USER/LOGIN/ROLE) detected"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

-- 3) DETECTION PATHS + RESOLUTION (per root cause x vendor) ----------------
DO $gen$
DECLARE
    v_step_id   bigint;
    v_path_id   bigint;
    v_res_step  bigint;
    v_res_path  bigint;
BEGIN
    -- SEC-SQL-AUD-023-RC01 / oracle
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'oracle' AND name = 'Detect SEC-SQL-AUD-023-RC01 (oracle)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-023-RC01' AND vendor_slug = 'oracle') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-023-RC01', 'oracle', 'Detect SEC-SQL-AUD-023-RC01 (oracle)', 'User account created (CREATE USER/LOGIN/ROLE)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('oracle', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-023-RC01 (oracle)', '{"action": "A database user/login/role was created. Confirm it was an authorised provisioning action; verify least-privilege was applied and the account is owned/attributed."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-023-RC01', 'oracle', 'Resolve: Detect SEC-SQL-AUD-023-RC01 (oracle)', 'resolve-sec_sql_aud_023_rc01-oracle', 'A database user/login/role was created. Confirm it was an authorised provisioning action; verify least-privilege was applied and the account is owned/attributed.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-023-RC01 / sqlserver
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'sqlserver' AND name = 'Detect SEC-SQL-AUD-023-RC01 (sqlserver)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-023-RC01' AND vendor_slug = 'sqlserver') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-023-RC01', 'sqlserver', 'Detect SEC-SQL-AUD-023-RC01 (sqlserver)', 'User account created (CREATE USER/LOGIN/ROLE)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('sqlserver', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-023-RC01 (sqlserver)', '{"action": "A database user/login/role was created. Confirm it was an authorised provisioning action; verify least-privilege was applied and the account is owned/attributed."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-023-RC01', 'sqlserver', 'Resolve: Detect SEC-SQL-AUD-023-RC01 (sqlserver)', 'resolve-sec_sql_aud_023_rc01-sqlserver', 'A database user/login/role was created. Confirm it was an authorised provisioning action; verify least-privilege was applied and the account is owned/attributed.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-023-RC01 / mysql
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'mysql' AND name = 'Detect SEC-SQL-AUD-023-RC01 (mysql)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-023-RC01' AND vendor_slug = 'mysql') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-023-RC01', 'mysql', 'Detect SEC-SQL-AUD-023-RC01 (mysql)', 'User account created (CREATE USER/LOGIN/ROLE)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('mysql', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-023-RC01 (mysql)', '{"action": "A database user/login/role was created. Confirm it was an authorised provisioning action; verify least-privilege was applied and the account is owned/attributed."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-023-RC01', 'mysql', 'Resolve: Detect SEC-SQL-AUD-023-RC01 (mysql)', 'resolve-sec_sql_aud_023_rc01-mysql', 'A database user/login/role was created. Confirm it was an authorised provisioning action; verify least-privilege was applied and the account is owned/attributed.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-023-RC01 / mariadb
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'mariadb' AND name = 'Detect SEC-SQL-AUD-023-RC01 (mariadb)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-023-RC01' AND vendor_slug = 'mariadb') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-023-RC01', 'mariadb', 'Detect SEC-SQL-AUD-023-RC01 (mariadb)', 'User account created (CREATE USER/LOGIN/ROLE)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('mariadb', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-023-RC01 (mariadb)', '{"action": "A database user/login/role was created. Confirm it was an authorised provisioning action; verify least-privilege was applied and the account is owned/attributed."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-023-RC01', 'mariadb', 'Resolve: Detect SEC-SQL-AUD-023-RC01 (mariadb)', 'resolve-sec_sql_aud_023_rc01-mariadb', 'A database user/login/role was created. Confirm it was an authorised provisioning action; verify least-privilege was applied and the account is owned/attributed.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-023-RC02 / oracle
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'oracle' AND name = 'Detect SEC-SQL-AUD-023-RC02 (oracle)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-023-RC02' AND vendor_slug = 'oracle') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-023-RC02', 'oracle', 'Detect SEC-SQL-AUD-023-RC02 (oracle)', 'Privileges granted (possible excessive grant)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('oracle', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-023-RC02 (oracle)', '{"action": "Privileges were granted. Review for EXCESSIVE/administrative grants (DBA, SYSDBA, ALL PRIVILEGES, WITH ADMIN/GRANT OPTION, sysadmin, CONTROL SERVER, ALTER ANY). Revoke over-privilege; apply least privilege."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-023-RC02', 'oracle', 'Resolve: Detect SEC-SQL-AUD-023-RC02 (oracle)', 'resolve-sec_sql_aud_023_rc02-oracle', 'Privileges were granted. Review for EXCESSIVE/administrative grants (DBA, SYSDBA, ALL PRIVILEGES, WITH ADMIN/GRANT OPTION, sysadmin, CONTROL SERVER, ALTER ANY). Revoke over-privilege; apply least privilege.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-023-RC02 / sqlserver
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'sqlserver' AND name = 'Detect SEC-SQL-AUD-023-RC02 (sqlserver)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-023-RC02' AND vendor_slug = 'sqlserver') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-023-RC02', 'sqlserver', 'Detect SEC-SQL-AUD-023-RC02 (sqlserver)', 'Privileges granted (possible excessive grant)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('sqlserver', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-023-RC02 (sqlserver)', '{"action": "Privileges were granted. Review for EXCESSIVE/administrative grants (DBA, SYSDBA, ALL PRIVILEGES, WITH ADMIN/GRANT OPTION, sysadmin, CONTROL SERVER, ALTER ANY). Revoke over-privilege; apply least privilege."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-023-RC02', 'sqlserver', 'Resolve: Detect SEC-SQL-AUD-023-RC02 (sqlserver)', 'resolve-sec_sql_aud_023_rc02-sqlserver', 'Privileges were granted. Review for EXCESSIVE/administrative grants (DBA, SYSDBA, ALL PRIVILEGES, WITH ADMIN/GRANT OPTION, sysadmin, CONTROL SERVER, ALTER ANY). Revoke over-privilege; apply least privilege.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-023-RC02 / mysql
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'mysql' AND name = 'Detect SEC-SQL-AUD-023-RC02 (mysql)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-023-RC02' AND vendor_slug = 'mysql') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-023-RC02', 'mysql', 'Detect SEC-SQL-AUD-023-RC02 (mysql)', 'Privileges granted (possible excessive grant)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('mysql', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-023-RC02 (mysql)', '{"action": "Privileges were granted. Review for EXCESSIVE/administrative grants (DBA, SYSDBA, ALL PRIVILEGES, WITH ADMIN/GRANT OPTION, sysadmin, CONTROL SERVER, ALTER ANY). Revoke over-privilege; apply least privilege."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-023-RC02', 'mysql', 'Resolve: Detect SEC-SQL-AUD-023-RC02 (mysql)', 'resolve-sec_sql_aud_023_rc02-mysql', 'Privileges were granted. Review for EXCESSIVE/administrative grants (DBA, SYSDBA, ALL PRIVILEGES, WITH ADMIN/GRANT OPTION, sysadmin, CONTROL SERVER, ALTER ANY). Revoke over-privilege; apply least privilege.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-023-RC02 / mariadb
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'mariadb' AND name = 'Detect SEC-SQL-AUD-023-RC02 (mariadb)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-023-RC02' AND vendor_slug = 'mariadb') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-023-RC02', 'mariadb', 'Detect SEC-SQL-AUD-023-RC02 (mariadb)', 'Privileges granted (possible excessive grant)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('mariadb', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-023-RC02 (mariadb)', '{"action": "Privileges were granted. Review for EXCESSIVE/administrative grants (DBA, SYSDBA, ALL PRIVILEGES, WITH ADMIN/GRANT OPTION, sysadmin, CONTROL SERVER, ALTER ANY). Revoke over-privilege; apply least privilege."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-023-RC02', 'mariadb', 'Resolve: Detect SEC-SQL-AUD-023-RC02 (mariadb)', 'resolve-sec_sql_aud_023_rc02-mariadb', 'Privileges were granted. Review for EXCESSIVE/administrative grants (DBA, SYSDBA, ALL PRIVILEGES, WITH ADMIN/GRANT OPTION, sysadmin, CONTROL SERVER, ALTER ANY). Revoke over-privilege; apply least privilege.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-023-RC03 / oracle
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'oracle' AND name = 'Detect SEC-SQL-AUD-023-RC03 (oracle)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-023-RC03' AND vendor_slug = 'oracle') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-023-RC03', 'oracle', 'Detect SEC-SQL-AUD-023-RC03 (oracle)', 'User account dropped (DROP USER/LOGIN/ROLE)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('oracle', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-023-RC03 (oracle)', '{"action": "A database user/login/role was dropped. Confirm authorised de-provisioning; if not, restore the principal + grants from the IAM baseline and investigate."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-023-RC03', 'oracle', 'Resolve: Detect SEC-SQL-AUD-023-RC03 (oracle)', 'resolve-sec_sql_aud_023_rc03-oracle', 'A database user/login/role was dropped. Confirm authorised de-provisioning; if not, restore the principal + grants from the IAM baseline and investigate.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-023-RC03 / sqlserver
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'sqlserver' AND name = 'Detect SEC-SQL-AUD-023-RC03 (sqlserver)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-023-RC03' AND vendor_slug = 'sqlserver') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-023-RC03', 'sqlserver', 'Detect SEC-SQL-AUD-023-RC03 (sqlserver)', 'User account dropped (DROP USER/LOGIN/ROLE)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('sqlserver', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-023-RC03 (sqlserver)', '{"action": "A database user/login/role was dropped. Confirm authorised de-provisioning; if not, restore the principal + grants from the IAM baseline and investigate."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-023-RC03', 'sqlserver', 'Resolve: Detect SEC-SQL-AUD-023-RC03 (sqlserver)', 'resolve-sec_sql_aud_023_rc03-sqlserver', 'A database user/login/role was dropped. Confirm authorised de-provisioning; if not, restore the principal + grants from the IAM baseline and investigate.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-023-RC03 / mysql
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'mysql' AND name = 'Detect SEC-SQL-AUD-023-RC03 (mysql)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-023-RC03' AND vendor_slug = 'mysql') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-023-RC03', 'mysql', 'Detect SEC-SQL-AUD-023-RC03 (mysql)', 'User account dropped (DROP USER/LOGIN/ROLE)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('mysql', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-023-RC03 (mysql)', '{"action": "A database user/login/role was dropped. Confirm authorised de-provisioning; if not, restore the principal + grants from the IAM baseline and investigate."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-023-RC03', 'mysql', 'Resolve: Detect SEC-SQL-AUD-023-RC03 (mysql)', 'resolve-sec_sql_aud_023_rc03-mysql', 'A database user/login/role was dropped. Confirm authorised de-provisioning; if not, restore the principal + grants from the IAM baseline and investigate.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-023-RC03 / mariadb
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'mariadb' AND name = 'Detect SEC-SQL-AUD-023-RC03 (mariadb)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-023-RC03' AND vendor_slug = 'mariadb') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-023-RC03', 'mariadb', 'Detect SEC-SQL-AUD-023-RC03 (mariadb)', 'User account dropped (DROP USER/LOGIN/ROLE)', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('mariadb', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-023-RC03 (mariadb)', '{"action": "A database user/login/role was dropped. Confirm authorised de-provisioning; if not, restore the principal + grants from the IAM baseline and investigate."}'::jsonb, 'medium', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-023-RC03', 'mariadb', 'Resolve: Detect SEC-SQL-AUD-023-RC03 (mariadb)', 'resolve-sec_sql_aud_023_rc03-mariadb', 'A database user/login/role was dropped. Confirm authorised de-provisioning; if not, restore the principal + grants from the IAM baseline and investigate.', 'supervised', 'medium', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
END
$gen$;

-- 4) MONITORING VIEWS (one per root cause) ---------------------------------
CREATE OR REPLACE VIEW monitoring.v_sec_sql_aud_023_rc01 AS
SELECT r.server,
    (j.value ->> 'event_time') AS event_time,
    (j.value ->> 'login_name') AS login_name,
    (j.value ->> 'host_name') AS host_name,
    (j.value ->> 'os_user') AS os_user,
    (j.value ->> 'auth_info') AS auth_info,
    (j.value ->> 'statement') AS statement,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-AUD-023-RC01';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_aud_023_rc02 AS
SELECT r.server,
    (j.value ->> 'event_time') AS event_time,
    (j.value ->> 'login_name') AS login_name,
    (j.value ->> 'host_name') AS host_name,
    (j.value ->> 'os_user') AS os_user,
    (j.value ->> 'auth_info') AS auth_info,
    (j.value ->> 'statement') AS statement,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-AUD-023-RC02';

CREATE OR REPLACE VIEW monitoring.v_sec_sql_aud_023_rc03 AS
SELECT r.server,
    (j.value ->> 'event_time') AS event_time,
    (j.value ->> 'login_name') AS login_name,
    (j.value ->> 'host_name') AS host_name,
    (j.value ->> 'os_user') AS os_user,
    (j.value ->> 'auth_info') AS auth_info,
    (j.value ->> 'statement') AS statement,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-AUD-023-RC03';

-- 5) VERIFY ----------------------------------------------------------------
SELECT root_cause_id, name, vendors_applicable FROM rootcause.root_causes
 WHERE root_cause_id IN ('SEC-SQL-AUD-023-RC01', 'SEC-SQL-AUD-023-RC02', 'SEC-SQL-AUD-023-RC03');

COMMIT;
