-- ============================================================
-- 6370  SEC-SQL-AUD-026-RC01  Unauthorized privilege escalation (elevated privilege/role held)
--   STATE-based: lists non-baseline accounts that HOLD elevated privileges/roles.
--   oracle DBA_ROLE_PRIVS + DBA_SYS_PRIVS, sqlserver sys.server_role_members,
--   mysql/mariadb mysql.user global privileges. Reliable without audit config; self-clears on revoke.
--   Edit the baseline exclusion list / elevated set in the rule SQL to whitelist approved admins.
--   Verify: GRANT DBA TO test_user  (the account then appears until revoked).
--   Idempotent (rebuilds the RC cleanly).
-- ============================================================

-- ===========================================================================
-- Auto-generated by gen_rootcause_module.py from specs/priv_escalation.json
-- Module: priv_escalation   Root causes: 1   Vendors: oracle, sqlserver, mysql, mariadb
-- DO NOT hand-edit; edit the spec and regenerate.
-- ===========================================================================
BEGIN;

-- 0) ISSUE + cleanup (idempotent rebuild) ------------------------------
INSERT INTO rootcause.issues (issue_id, domain_code, database_type_code, area_code, name, slug, description, created_at, updated_at)
VALUES ('SEC-SQL-AUD-026','SEC','SQL','AUD','Unauthorized privilege escalation monitoring','privilege-escalation-monitoring','Detect accounts holding elevated/administrative privileges and roles (privilege escalation).',now(),now())
ON CONFLICT (issue_id) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;
DELETE FROM rootcause.detection_path_steps WHERE detection_path_id IN (SELECT id FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-026-RC01');
DELETE FROM rootcause.detection_paths WHERE root_cause_id='SEC-SQL-AUD-026-RC01';
DELETE FROM rootcause.detection_steps WHERE name LIKE 'Detect SEC-SQL-AUD-026-RC01 %';
DELETE FROM rootcause.resolution_path_steps WHERE resolution_path_id IN (SELECT id FROM rootcause.resolution_paths WHERE root_cause_id='SEC-SQL-AUD-026-RC01');
DELETE FROM rootcause.resolution_paths WHERE root_cause_id='SEC-SQL-AUD-026-RC01';
DELETE FROM rootcause.resolution_steps WHERE name LIKE 'Resolve: Detect SEC-SQL-AUD-026-RC01 %';


-- 1) ROOT CAUSES -----------------------------------------------------------
INSERT INTO rootcause.root_causes (root_cause_id, issue_id, name, slug, description, topics, vendors_applicable)
VALUES (
    'SEC-SQL-AUD-026-RC01', 'SEC-SQL-AUD-026', 'Unauthorized privilege escalation - account holds elevated/administrative privileges',
    'privilege-escalation', 'Detects privilege escalation by STATE: lists accounts (excluding the DBMS-maintained baseline) that currently HOLD elevated / administrative roles or privileges. Oracle reads DBA_ROLE_PRIVS + DBA_SYS_PRIVS (DBA, *_FULL_DATABASE, ALTER SYSTEM, GRANT ANY, ANY-object privileges, CREATE/ALTER/DROP USER); SQL Server reads sys.server_role_members (sysadmin/securityadmin/serveradmin/...); MySQL/MariaDB read mysql.user global privileges (SUPER, GRANT OPTION, CREATE USER, SHUTDOWN, RELOAD). State-based detection is reliable without any audit configuration and self-clears when the grant is revoked. The baseline exclusion list and elevated-privilege set are embedded in the rule SQL - edit them to whitelist approved admin accounts. Verify by granting an elevated privilege (e.g. GRANT DBA TO test_user), then logging in with that account and performing administrative actions.',
    ARRAY['audit', 'privilege-escalation', 'iam', 'least-privilege', 'insider-threat', 'entitlements', 'security'], ARRAY['oracle', 'sqlserver', 'mysql', 'mariadb']
) ON CONFLICT (root_cause_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description,
    topics = EXCLUDED.topics, vendors_applicable = EXCLUDED.vendors_applicable;

-- 2) DETECTION STEPS (per vendor) ------------------------------------------
INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('oracle', 'query', 'Detect SEC-SQL-AUD-026-RC01 (oracle)',
        '{"sql": "SELECT * FROM (\n  SELECT TO_CHAR(SYSTIMESTAMP,''YYYY-MM-DD HH24:MI:SS'') AS event_time, grantee AS login_name,\n         SYS_CONTEXT(''USERENV'',''DB_NAME'') AS host_name, CAST(NULL AS VARCHAR2(30)) AS os_user,\n         ''ROLE ''||granted_role AS auth_info,\n         ''Account ''||grantee||'' holds elevated role ''||granted_role||\n           CASE WHEN admin_option=''YES'' THEN '' (WITH ADMIN OPTION)'' ELSE '''' END AS statement\n  FROM dba_role_privs\n  WHERE granted_role IN (''DBA'',''PDB_DBA'',''IMP_FULL_DATABASE'',''EXP_FULL_DATABASE'',\n        ''DATAPUMP_IMP_FULL_DATABASE'',''DATAPUMP_EXP_FULL_DATABASE'',''AUDIT_ADMIN'')\n  UNION ALL\n  SELECT TO_CHAR(SYSTIMESTAMP,''YYYY-MM-DD HH24:MI:SS''), grantee,\n         SYS_CONTEXT(''USERENV'',''DB_NAME''), CAST(NULL AS VARCHAR2(30)), ''PRIV ''||privilege,\n         ''Account ''||grantee||'' holds elevated privilege ''||privilege||\n           CASE WHEN admin_option=''YES'' THEN '' (WITH ADMIN OPTION)'' ELSE '''' END\n  FROM dba_sys_privs\n  WHERE privilege IN (''ALTER SYSTEM'',''ALTER DATABASE'',''BECOME USER'',''GRANT ANY PRIVILEGE'',\n        ''GRANT ANY ROLE'',''GRANT ANY OBJECT PRIVILEGE'',''CREATE ANY TABLE'',''DROP ANY TABLE'',\n        ''SELECT ANY TABLE'',''INSERT ANY TABLE'',''UPDATE ANY TABLE'',''DELETE ANY TABLE'',''CREATE USER'',\n        ''ALTER USER'',''DROP USER'',''CREATE ANY PROCEDURE'',''ALTER ANY TABLE'',''AUDIT SYSTEM'',''ALTER PROFILE'')\n) t\nWHERE login_name IN (SELECT username FROM dba_users WHERE oracle_maintained=''N'')\nORDER BY login_name, auth_info\nFETCH FIRST 500 ROWS ONLY"}'::jsonb,
        '{"condition": "row_count > 0", "description": "A non-baseline account holds elevated/administrative privileges (possible unauthorized privilege assignment)"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('sqlserver', 'query', 'Detect SEC-SQL-AUD-026-RC01 (sqlserver)',
        '{"sql": "SELECT TOP 500 CONVERT(varchar(19),GETDATE(),120) AS event_time, sp.name AS login_name,\n       CAST(@@SERVERNAME AS sysname) AS host_name, CAST(NULL AS sysname) AS os_user,\n       ''SERVER ROLE ''+rp.name AS auth_info,\n       ''Login ''+sp.name+'' is a member of elevated server role ''+rp.name AS statement\nFROM sys.server_role_members srm\nJOIN sys.server_principals rp ON rp.principal_id = srm.role_principal_id\nJOIN sys.server_principals sp ON sp.principal_id = srm.member_principal_id\nWHERE rp.name IN (''sysadmin'',''securityadmin'',''serveradmin'',''setupadmin'',''processadmin'',''diskadmin'',''dbcreator'')\n  AND sp.name NOT IN (''sa'',''dbo'') AND sp.name NOT LIKE ''##MS%'' AND sp.name NOT LIKE ''NT SERVICE\\%''\nORDER BY sp.name"}'::jsonb,
        '{"condition": "row_count > 0", "description": "A non-baseline account holds elevated/administrative privileges (possible unauthorized privilege assignment)"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('mysql', 'query', 'Detect SEC-SQL-AUD-026-RC01 (mysql)',
        '{"sql": "SELECT NOW() AS event_time, CONCAT(u.User,''@'',u.Host) AS login_name, @@hostname AS host_name,\n       CAST(NULL AS CHAR) AS os_user, ''GLOBAL PRIV'' AS auth_info,\n       CONCAT(CONCAT(u.User,''@'',u.Host),'' holds elevated global privileges: '',\n         TRIM(BOTH '','' FROM CONCAT(\n           IF(u.Super_priv=''Y'',''SUPER,'',''''), IF(u.Grant_priv=''Y'',''GRANT_OPTION,'',''''),\n           IF(u.Create_user_priv=''Y'',''CREATE_USER,'',''''), IF(u.Shutdown_priv=''Y'',''SHUTDOWN,'',''''),\n           IF(u.Reload_priv=''Y'',''RELOAD,'','''')))) AS statement\nFROM mysql.user u\nWHERE (u.Super_priv=''Y'' OR u.Grant_priv=''Y'' OR u.Create_user_priv=''Y'' OR u.Shutdown_priv=''Y'')\n  AND u.User NOT IN (''root'',''mysql.sys'',''mysql.session'',''mysql.infoschema'',''debian-sys-maint'',\n        ''mariadb.sys'',''healthcheck'')\nORDER BY u.User LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "A non-baseline account holds elevated/administrative privileges (possible unauthorized privilege assignment)"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

INSERT INTO rootcause.detection_steps (vendor_slug, step_type, name, content, expected)
VALUES ('mariadb', 'query', 'Detect SEC-SQL-AUD-026-RC01 (mariadb)',
        '{"sql": "SELECT NOW() AS event_time, CONCAT(u.User,''@'',u.Host) AS login_name, @@hostname AS host_name,\n       CAST(NULL AS CHAR) AS os_user, ''GLOBAL PRIV'' AS auth_info,\n       CONCAT(CONCAT(u.User,''@'',u.Host),'' holds elevated global privileges: '',\n         TRIM(BOTH '','' FROM CONCAT(\n           IF(u.Super_priv=''Y'',''SUPER,'',''''), IF(u.Grant_priv=''Y'',''GRANT_OPTION,'',''''),\n           IF(u.Create_user_priv=''Y'',''CREATE_USER,'',''''), IF(u.Shutdown_priv=''Y'',''SHUTDOWN,'',''''),\n           IF(u.Reload_priv=''Y'',''RELOAD,'','''')))) AS statement\nFROM mysql.user u\nWHERE (u.Super_priv=''Y'' OR u.Grant_priv=''Y'' OR u.Create_user_priv=''Y'' OR u.Shutdown_priv=''Y'')\n  AND u.User NOT IN (''root'',''mysql.sys'',''mysql.session'',''mysql.infoschema'',''debian-sys-maint'',\n        ''mariadb.sys'',''healthcheck'')\nORDER BY u.User LIMIT 500"}'::jsonb,
        '{"condition": "row_count > 0", "description": "A non-baseline account holds elevated/administrative privileges (possible unauthorized privilege assignment)"}'::jsonb)
ON CONFLICT (vendor_slug, name) DO UPDATE SET
    content = EXCLUDED.content, expected = EXCLUDED.expected;

-- 3) DETECTION PATHS + RESOLUTION (per root cause x vendor) ----------------
DO $gen$
DECLARE
    v_step_id   bigint;
    v_path_id   bigint;
    v_res_step  bigint;
    v_res_path  bigint;
BEGIN
    -- SEC-SQL-AUD-026-RC01 / oracle
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'oracle' AND name = 'Detect SEC-SQL-AUD-026-RC01 (oracle)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-026-RC01' AND vendor_slug = 'oracle') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-026-RC01', 'oracle', 'Detect SEC-SQL-AUD-026-RC01 (oracle)', 'Unauthorized privilege escalation - account holds elevated/administrative privileges', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('oracle', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-026-RC01 (oracle)', '{"action": "For each flagged account confirm the elevated grant was authorised (change ticket / approved provisioning). If NOT: REVOKE the excessive role/privilege, disable or investigate the grantee, review what the account did (correlate with authentication, DBA-activity and sensitive-data/-change events), and restore least-privilege. If the account is a legitimate admin, add it to the baseline exclusion list in the rule SQL. Unexpected DBA/sysadmin membership is a common attack step - treat it as a potential compromise."}'::jsonb, 'high', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-026-RC01', 'oracle', 'Resolve: Detect SEC-SQL-AUD-026-RC01 (oracle)', 'resolve-sec_sql_aud_026_rc01-oracle', 'For each flagged account confirm the elevated grant was authorised (change ticket / approved provisioning). If NOT: REVOKE the excessive role/privilege, disable or investigate the grantee, review what the account did (correlate with authentication, DBA-activity and sensitive-data/-change events), and restore least-privilege. If the account is a legitimate admin, add it to the baseline exclusion list in the rule SQL. Unexpected DBA/sysadmin membership is a common attack step - treat it as a potential compromise.', 'supervised', 'high', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-026-RC01 / sqlserver
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'sqlserver' AND name = 'Detect SEC-SQL-AUD-026-RC01 (sqlserver)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-026-RC01' AND vendor_slug = 'sqlserver') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-026-RC01', 'sqlserver', 'Detect SEC-SQL-AUD-026-RC01 (sqlserver)', 'Unauthorized privilege escalation - account holds elevated/administrative privileges', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('sqlserver', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-026-RC01 (sqlserver)', '{"action": "For each flagged account confirm the elevated grant was authorised (change ticket / approved provisioning). If NOT: REVOKE the excessive role/privilege, disable or investigate the grantee, review what the account did (correlate with authentication, DBA-activity and sensitive-data/-change events), and restore least-privilege. If the account is a legitimate admin, add it to the baseline exclusion list in the rule SQL. Unexpected DBA/sysadmin membership is a common attack step - treat it as a potential compromise."}'::jsonb, 'high', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-026-RC01', 'sqlserver', 'Resolve: Detect SEC-SQL-AUD-026-RC01 (sqlserver)', 'resolve-sec_sql_aud_026_rc01-sqlserver', 'For each flagged account confirm the elevated grant was authorised (change ticket / approved provisioning). If NOT: REVOKE the excessive role/privilege, disable or investigate the grantee, review what the account did (correlate with authentication, DBA-activity and sensitive-data/-change events), and restore least-privilege. If the account is a legitimate admin, add it to the baseline exclusion list in the rule SQL. Unexpected DBA/sysadmin membership is a common attack step - treat it as a potential compromise.', 'supervised', 'high', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-026-RC01 / mysql
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'mysql' AND name = 'Detect SEC-SQL-AUD-026-RC01 (mysql)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-026-RC01' AND vendor_slug = 'mysql') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-026-RC01', 'mysql', 'Detect SEC-SQL-AUD-026-RC01 (mysql)', 'Unauthorized privilege escalation - account holds elevated/administrative privileges', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('mysql', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-026-RC01 (mysql)', '{"action": "For each flagged account confirm the elevated grant was authorised (change ticket / approved provisioning). If NOT: REVOKE the excessive role/privilege, disable or investigate the grantee, review what the account did (correlate with authentication, DBA-activity and sensitive-data/-change events), and restore least-privilege. If the account is a legitimate admin, add it to the baseline exclusion list in the rule SQL. Unexpected DBA/sysadmin membership is a common attack step - treat it as a potential compromise."}'::jsonb, 'high', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-026-RC01', 'mysql', 'Resolve: Detect SEC-SQL-AUD-026-RC01 (mysql)', 'resolve-sec_sql_aud_026_rc01-mysql', 'For each flagged account confirm the elevated grant was authorised (change ticket / approved provisioning). If NOT: REVOKE the excessive role/privilege, disable or investigate the grantee, review what the account did (correlate with authentication, DBA-activity and sensitive-data/-change events), and restore least-privilege. If the account is a legitimate admin, add it to the baseline exclusion list in the rule SQL. Unexpected DBA/sysadmin membership is a common attack step - treat it as a potential compromise.', 'supervised', 'high', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
    -- SEC-SQL-AUD-026-RC01 / mariadb
    SELECT id INTO v_step_id FROM rootcause.detection_steps
     WHERE vendor_slug = 'mariadb' AND name = 'Detect SEC-SQL-AUD-026-RC01 (mariadb)' ORDER BY id DESC LIMIT 1;
    IF v_step_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM rootcause.detection_paths
       WHERE root_cause_id = 'SEC-SQL-AUD-026-RC01' AND vendor_slug = 'mariadb') THEN
        INSERT INTO rootcause.detection_paths (root_cause_id, vendor_slug, name, description, path_type, is_active)
        VALUES ('SEC-SQL-AUD-026-RC01', 'mariadb', 'Detect SEC-SQL-AUD-026-RC01 (mariadb)', 'Unauthorized privilege escalation - account holds elevated/administrative privileges', 'diagnostic', true) RETURNING id INTO v_path_id;
        INSERT INTO rootcause.detection_path_steps (detection_path_id, detection_step_id, sequence, on_match_action, on_no_match_action)
        VALUES (v_path_id, v_step_id, 1, 'confirmed', 'ruled_out');
        INSERT INTO rootcause.resolution_steps (vendor_slug, step_type, name, content, risk_level, requires_confirmation, is_reversible)
        VALUES ('mariadb', 'recommendation', 'Resolve: Detect SEC-SQL-AUD-026-RC01 (mariadb)', '{"action": "For each flagged account confirm the elevated grant was authorised (change ticket / approved provisioning). If NOT: REVOKE the excessive role/privilege, disable or investigate the grantee, review what the account did (correlate with authentication, DBA-activity and sensitive-data/-change events), and restore least-privilege. If the account is a legitimate admin, add it to the baseline exclusion list in the rule SQL. Unexpected DBA/sysadmin membership is a common attack step - treat it as a potential compromise."}'::jsonb, 'high', false, true) RETURNING id INTO v_res_step;
        INSERT INTO rootcause.resolution_paths (root_cause_id, vendor_slug, name, slug, description, execution_mode, risk_level, is_active)
        VALUES ('SEC-SQL-AUD-026-RC01', 'mariadb', 'Resolve: Detect SEC-SQL-AUD-026-RC01 (mariadb)', 'resolve-sec_sql_aud_026_rc01-mariadb', 'For each flagged account confirm the elevated grant was authorised (change ticket / approved provisioning). If NOT: REVOKE the excessive role/privilege, disable or investigate the grantee, review what the account did (correlate with authentication, DBA-activity and sensitive-data/-change events), and restore least-privilege. If the account is a legitimate admin, add it to the baseline exclusion list in the rule SQL. Unexpected DBA/sysadmin membership is a common attack step - treat it as a potential compromise.', 'supervised', 'high', true) RETURNING id INTO v_res_path;
        INSERT INTO rootcause.resolution_path_steps (resolution_path_id, resolution_step_id, step_order) VALUES (v_res_path, v_res_step, 1);
    END IF;
END
$gen$;

-- 4) MONITORING VIEWS (one per root cause) ---------------------------------
CREATE OR REPLACE VIEW monitoring.v_sec_sql_aud_026_rc01 AS
SELECT r.server,
    (j.value ->> 'event_time') AS event_time,
    (j.value ->> 'login_name') AS login_name,
    (j.value ->> 'host_name') AS host_name,
    (j.value ->> 'os_user') AS os_user,
    (j.value ->> 'auth_info') AS auth_info,
    (j.value ->> 'statement') AS statement,
    r.entry_date
FROM monitoring.general_metric_metadata_results r
  CROSS JOIN LATERAL jsonb_array_elements(r.metric_metadata) j(value)
 WHERE r.metric_name = 'SEC-SQL-AUD-026-RC01';

-- 5) VERIFY ----------------------------------------------------------------
SELECT root_cause_id, name, vendors_applicable FROM rootcause.root_causes
 WHERE root_cause_id IN ('SEC-SQL-AUD-026-RC01');

COMMIT;
