-- Idempotent install for metrics.custom_metrics
-- Auto-generated from dbanalytics_install.backup. Safe to re-run (psql -f).

CREATE SCHEMA IF NOT EXISTS metrics;

CREATE SEQUENCE IF NOT EXISTS metrics.custom_metrics_row_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE IF NOT EXISTS metrics.custom_metrics (
    row_id integer NOT NULL,
    category_id integer NOT NULL,
    metric_name character varying(255) NOT NULL,
    query text NOT NULL,
    description text NOT NULL,
    entry_date timestamp without time zone DEFAULT now() NOT NULL,
    is_active boolean,
    db_vendor character varying(50) DEFAULT 'MSSQL'::character varying NOT NULL,
    metrics_type public.metric_type DEFAULT 'collect'::public.metric_type NOT NULL
);

ALTER TABLE metrics.custom_metrics ALTER COLUMN row_id SET DEFAULT nextval('metrics.custom_metrics_row_id_seq'::regclass);
ALTER SEQUENCE metrics.custom_metrics_row_id_seq OWNED BY metrics.custom_metrics.row_id;

-- data: load only into a freshly-created (empty) table
DROP TABLE IF EXISTS _stg_load;
CREATE TEMP TABLE _stg_load (LIKE metrics.custom_metrics);
COPY _stg_load (row_id, category_id, metric_name, query, description, entry_date, is_active, db_vendor, metrics_type) FROM stdin;
6	1	Roles with superuser privileges 	SELECT rolname, rolsuper, rolcreaterole, rolcreatedb, rolcanlogin FROM pg_roles WHERE rolsuper = true;	Roles with superuser privileges 	2025-08-09 15:36:13.317091	t	PostgreSQL	collect
7	-1	Roles with REPLICATION privilege	SELECT rolname FROM pg_roles WHERE rolreplication = true	Roles with REPLICATION privilege	2025-08-13 00:30:06.580494	t	POSTGRES	collect
9	-1	roles without passwords	SELECT rolname FROM pg_authid WHERE rolcanlogin = true   AND (rolpassword IS NULL OR rolpassword = 'md5')	roles without passwords	2025-08-13 00:32:09.472167	t	POSTGRES	collect
10	-1	roles without passwords	SELECT grantee, privilege_type, table_schema, table_name FROM information_schema.role_table_grants WHERE grantee = 'PUBLIC'	roles without passwords	2025-08-13 00:37:44.697814	t	POSTGRES	collect
5	-1	Active long-running queries / top resource consumers	SELECT pid, usename, application_name, client_addr, client_hostname, backend_start,\n       state, now() - query_start AS runtime, wait_event_type, wait_event, query\nFROM pg_stat_activity\nWHERE state <> 'idle'\nORDER BY runtime DESC;	Active long-running queries / top resource consumers	2025-08-11 11:41:00.547019	t	POSTGRES	collect
15	-1	Secured connection	SELECT pid, ssl, client_addr FROM pg_stat_ssl	Secured connection	2025-08-13 01:23:50.683038	t	POSTGRES	collect
16	-1	Look for orphaned or unused roles	SELECT rolname FROM pg_roles WHERE rolname NOT IN ( SELECT DISTINCT grantee FROM information_schema.role_table_grants   UNION     SELECT DISTINCT role_name FROM information_schema.applicable_roles )	Look for orphaned or unused roles	2025-08-13 01:26:48.088389	t	POSTGRES	collect
17	-1	active transactions	SELECT pid,\n       usename,\n       datname,\n       client_addr,\n       state,\n       query,\n       xact_start,\n       now() - xact_start AS transaction_duration\nFROM pg_stat_activity\nWHERE state IN ('active', 'idle in transaction')\nORDER BY transaction_duration DESC	active transactions	2025-08-13 01:28:39.751119	t	postgres	collect
18	-1	active transactions	SELECT pid,\n       usename,\n       datname,\n       client_addr,\n       state,\n       query,\n       xact_start,\n       now() - xact_start AS transaction_duration\nFROM pg_stat_activity\nWHERE state IN ('active', 'idle in transaction')\nORDER BY transaction_duration DESC	active transactions	2025-08-13 01:30:00.300026	t	postgres	collect
19	-1	Blocking transactions	SELECT bl.pid     AS blocked_pid,\n       a.usename  AS blocked_user,\n       ka.query   AS blocking_query,\n       now() - ka.query_start AS blocking_duration,\n       kl.pid     AS blocking_pid\nFROM pg_locks bl\nJOIN pg_stat_activity a  ON bl.pid = a.pid\nJOIN pg_locks kl         ON bl.locktype = kl.locktype\n                         AND bl.database IS NOT DISTINCT FROM kl.database\n                         AND bl.relation IS NOT DISTINCT FROM kl.relation\n                         AND bl.page IS NOT DISTINCT FROM kl.page\n                         AND bl.tuple IS NOT DISTINCT FROM kl.tuple\n                         AND bl.virtualxid IS NOT DISTINCT FROM kl.virtualxid\n                         AND bl.transactionid IS NOT DISTINCT FROM kl.transactionid\n                         AND bl.classid IS NOT DISTINCT FROM kl.classid\n                         AND bl.objid IS NOT DISTINCT FROM kl.objid\n                         AND bl.objsubid IS NOT DISTINCT FROM kl.objsubid\nJOIN pg_stat_activity ka ON kl.pid = ka.pid\nWHERE NOT bl.granted	Blocking transactions	2025-08-13 01:30:21.624127	t	POSTGRES	collect
20	-1	Active connections 	SELECT pid,\n       usename,\n       datname,\n       client_addr,\n       application_name,\n       state,\n       query,\n       query_start\nFROM pg_stat_activity\nWHERE state = 'active'\nORDER BY query_start	Active connections 	2025-08-13 01:31:45.083774	t	POSTGRES	collect
21	-1	All Connections 	\nSELECT pid,\n       usename,\n       datname,\n       client_addr,\n       application_name,\n       state,\n       backend_start,\n       xact_start,\n       query_start,\n       state_change,\n       query\nFROM pg_stat_activity\nORDER BY state, query_start	All Connections 	2025-08-13 01:41:40.959903	t	POSTGRES	collect
22	-1	Connection per user	SELECT usename, COUNT(*) AS connections\nFROM pg_stat_activity\nGROUP BY usename\nORDER BY connections DESC	Connection per user	2025-08-13 01:43:03.743383	t	POSTGRES	collect
24	1	Roles with LOGIN privilege	\nSELECT 'Login Roles' AS check_type, rolname\nFROM pg_roles\nWHERE rolcanlogin = true	Roles with LOGIN privilege	2025-08-13 01:50:27.095572	t	POSTGRES	collect
25	1	Roles without passwords (or NULL)	\nSELECT 'Login Roles without Password' AS check_type, rolname\nFROM pg_authid\nWHERE rolcanlogin = true\n  AND (rolpassword IS NULL OR rolpassword = ')	Roles without passwords (or NULL)	2025-08-13 01:51:28.786545	t	POSTGRES	collect
26	1	Roles without passwords (or NULL)	\nSELECT 'Login Roles without Password' AS check_type, rolname\nFROM pg_authid\nWHERE rolcanlogin = true\n  AND (rolpassword IS NULL OR rolpassword = ')	Roles without passwords (or NULL)	2025-08-13 01:51:30.631354	t	POSTGRES	collect
27	1	Public access to tables	SELECT 'Public Table Access' AS check_type, grantee || ' - ' || table_schema || '.' || table_name\nFROM information_schema.role_table_grants\nWHERE grantee = 'PUBLIC'	Public access to tables	2025-08-13 01:52:45.012635	t	POSTGRES	collect
28	1	Functions with SECURITY DEFINER	SELECT 'SECURITY DEFINER Functions' AS check_type, n.nspname || '.' || p.proname\nFROM pg_proc p\nJOIN pg_namespace n ON p.pronamespace = n.oid\nWHERE prosecdef = true	Functions with SECURITY DEFINER	2025-08-13 05:25:54.173203	t	POSTGRES	collect
29	1	Non-SSL connections (active sessions)	\nSELECT 'Non-SSL Connections' AS check_type, pid || ' - ' || client_addr\nFROM pg_stat_ssl\nWHERE ssl = false	Non-SSL connections (active sessions)	2025-08-13 05:27:29.765601	t	POSTGRES	collect
30	1	Logins with sysadmin (superuser) privileges	SELECT sp.name AS login_name\nFROM sys.server_principals sp\nJOIN sys.server_role_members srm ON sp.principal_id = srm.member_principal_id\nJOIN sys.server_principals rp ON srm.role_principal_id = rp.principal_id\nWHERE rp.name = 'sysadmin'	Logins with sysadmin (superuser) privileges	2025-08-13 05:46:44.641031	t	MSSQL	collect
31	1	Logins with CONNECT privilege (LOGIN rights)	\nSELECT name AS login_name\nFROM sys.server_principals\nWHERE type IN ('S', 'U', 'G') -- SQL login, Windows login, Windows group\n  AND name NOT LIKE '##%'	Logins with CONNECT privilege (LOGIN rights)	2025-08-13 05:48:05.451107	t	MSSQL	collect
32	1	SQL Logins without password policy enforcement	\nSELECT name, is_policy_checked, is_expiration_checked\nFROM sys.sql_logins\nWHERE is_policy_checked = 0	SQL Logins without password policy enforcement	2025-08-13 05:49:03.883885	t	MSSQL	collect
12	-1	functions with SECURITY DEFINER	SELECT table_schema, table_name, column_name, data_type	functions with SECURITY DEFINER	2025-08-13 00:41:20.550206	f	MSSQL	collect
13	-1	functions with SECURITY DEFINER	SELECT table_schema, table_name, column_name, data_type	functions with SECURITY DEFINER	2025-08-13 00:41:23.689581	f	MSSQL	collect
23	1	Superuser accounts	SELECT 'Superuser Roles' AS check_type, rolname\n                   FROM pg_roles\n                  WHERE rolsuper = true	Superuser accounts	2025-08-13 01:45:38.894378	t	postgres	collect
33	1	Public access to tables	\nSELECT \n    pr.name AS grantee,\n    o.name AS object_name,\n    p.permission_name\nFROM sys.database_permissions p\nJOIN sys.objects o ON p.major_id = o.object_id\nJOIN sys.database_principals pr ON p.grantee_principal_id = pr.principal_id\nWHERE pr.name = 'public'	Public access to tables	2025-08-13 05:50:21.41164	t	MSSQL	collect
34	1	Functions with elevated privileges (Analogous to SECURITY DEFINER)	 \nSELECT \n    name, \n    type_desc, \n    execute_as_principal_id\nFROM sys.sql_modules m\nJOIN sys.objects o ON m.object_id = o.object_id\nWHERE execute_as_principal_id IS NOT NULL	Functions with elevated privileges (Analogous to SECURITY DEFINER)	2025-08-13 06:02:50.6608	t	MSSQL	collect
37	1	Blocking sessions	\nSELECT \n    blocking_session_id,\n    session_id,\n    wait_type,\n    wait_time,\n    wait_resource\nFROM sys.dm_exec_requests\nWHERE blocking_session_id <> 0	Blocking sessions	2025-08-13 06:05:27.805139	t	MSSQL	collect
39	1	Connection count per user	SELECT login_name, COUNT(*) AS connection_count\nFROM sys.dm_exec_sessions\nWHERE is_user_process = 1\nGROUP BY login_name\nORDER BY connection_count DESC	Connection count per user	2025-08-13 06:09:54.859269	t	MSSQL	collect
40	1	Database restored	\nSELECT \n    r.destination_database_name,\n    r.user_name,\n    r.restore_date,\n    b.backup_start_date,\n    b.backup_finish_date,\n    b.database_name AS source_database_name,\n    mf.physical_device_name AS backup_file\nFROM msdb.dbo.restorehistory r\nLEFT JOIN msdb.dbo.backupset b \n    ON r.backup_set_id = b.backup_set_id\nLEFT JOIN msdb.dbo.backupmediafamily mf\n    ON b.media_set_id = mf.media_set_id\nwhere     b.backup_finish_date > dateadd(day , -1 , getdate())	Database restored	2025-08-13 06:11:47.82837	t	MSSQL	collect
11	-1	Find tables with public access	SELECT n.nspname AS schema,p.proname AS function,r.rolname AS owner FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid JOIN pg_roles r ON p.proowner = r.oid WHERE prosecdef = true	Find tables with public access	2025-08-13 00:38:45.423059	t	POSTGRES	collect
42	-1	long_locks	 SELECT\nder.session_id session_id,\nder.blocking_session_id blocking_session_id,\nDATEDIFF(second, der.start_time, GETDATE()) AS duration_secs,\nDB_NAME(der.database_id) AS database_name,\nder.start_time ,\nses.last_request_end_time,\nses.open_transaction_count,\nses.cpu_time,\nder.command,\nder.logical_reads,\nder.reads,\nder.writes,\nder.wait_type,\nder.last_wait_type,\nses.login_name,\nses.program_name AS program_name,\nses.host_name,\nt.text query\nFROM sys.dm_exec_requests der\nINNER JOIN sys.dm_exec_sessions ses ON der.session_id = ses.session_id\nCROSS APPLY sys.dm_exec_sql_text(der.sql_handle) t\nCROSS APPLY sys.dm_exec_query_plan(der.plan_handle) cp\nWHERE blocking_session_id >0	long duration  locks	2025-10-18 17:36:11.876534	t	MSSQL	collect
43	-1	long_locks_blocker	 ;WITH BlockingHierarchy AS (\n    -- Anchor: get all sessions that are being blocked\n    SELECT\n        der.session_id,\n        der.blocking_session_id\n    FROM sys.dm_exec_requests der\n    WHERE der.blocking_session_id > 0\n\n    UNION ALL\n\n    -- Recursive part: follow the chain upwards\n    SELECT\n        bh.session_id,\n        der.blocking_session_id\n    FROM BlockingHierarchy bh\n    JOIN sys.dm_exec_requests der\n        ON bh.blocking_session_id = der.session_id\n    WHERE der.blocking_session_id > 0\n)\n, RootBlocker AS (\n    SELECT\n        bh.session_id,\n        -- The topmost blocker is the last blocking_session_id that doesn't appear as a session_id\n        COALESCE(MAX(der.blocking_session_id), bh.blocking_session_id) AS possible_root\n    FROM BlockingHierarchy bh\n    LEFT JOIN sys.dm_exec_requests der\n        ON bh.blocking_session_id = der.session_id\n    GROUP BY bh.session_id, bh.blocking_session_id\n)\nSELECT\n    der.session_id,\n    der.blocking_session_id,\n    rb.possible_root AS root_blocker_id,\n    DATEDIFF(second, der.start_time, GETDATE()) AS duration_secs,\n    DB_NAME(der.database_id) AS database_name,\n    der.start_time,\n    ses.last_request_end_time,\n    ses.open_transaction_count,\n    ses.cpu_time,\n    der.command,\n    der.logical_reads,\n    der.reads,\n    der.writes,\n    der.wait_type,\n    der.last_wait_type,\n    ses.login_name,\n    ses.program_name,\n    ses.host_name,\n    t.text AS query_text\nFROM sys.dm_exec_requests der\nINNER JOIN sys.dm_exec_sessions ses ON der.session_id = ses.session_id\nLEFT JOIN RootBlocker rb ON der.session_id = rb.session_id\nCROSS APPLY sys.dm_exec_sql_text(der.sql_handle) t\nCROSS APPLY sys.dm_exec_query_plan(der.plan_handle) cp\nWHERE blocking_session_id > 0\nORDER BY COALESCE(rb.possible_root, der.blocking_session_id, der.session_id);	long locks blocker	2025-10-19 06:13:30.468874	t	MSSQL	collect
45	-1	expensive_queries	SELECT qs.execution_count AS [Execution Count],\n(qs.total_logical_reads)*8/1024.0 AS [Total Logical Reads (MB)],\n(qs.total_logical_reads/qs.execution_count)*8/1024.0 AS [Avg Logical Reads (MB)],\n(qs.total_worker_time)/1000.0 AS [Total Worker Time (ms)],\n(qs.total_worker_time/qs.execution_count)/1000.0 AS [Avg Worker Time (ms)],\n(qs.total_elapsed_time)/1000.0 AS [Total Elapsed Time (ms)],\n(qs.total_elapsed_time/qs.execution_count)/1000.0 AS [Avg Elapsed Time (ms)],\nqs.creation_time AS [Creation Time]\n,t.text AS [Complete Query Text]\nFROM sys.dm_exec_query_stats AS qs WITH (NOLOCK)\nCROSS APPLY sys.dm_exec_sql_text(plan_handle) AS t\n	expensive_queries	2026-01-24 08:50:16.756707	t	MSSQL	collect
4	-1	mssql_server_databases	SELECT SERVER\n      ,program_name\n      ,Query\n  FROM dbdome.dbo.v_Active_transacrion\n	Databases per server	2025-07-01 21:18:32.954017	f	MSSQL	collect
14	-1	functions with SECURITY DEFINER	SELECT table_schema, table_name, column_name, data_type	functions with SECURITY DEFINER	2025-08-13 00:48:22.851984	f	POSTGRES	collect
35	1	SSL/TLS connections	\nSELECT name, protocol_desc, type_desc, is_encryption_enabled\nFROM sys.endpoints\nWHERE type_desc = 'TSQL'	SSL/TLS connections	2025-08-13 06:03:45.905342	f	MSSQL	collect
41	-1	long_block_transactions	\nSELECT\n    s.session_id,\n    s.login_name,\n    s.host_name,\n    r.status,\n    r.start_time,\n    r.command,\n    r.cpu_time,\n    r.blocking_session_id,\n    r.total_elapsed_time,\n    transaction_id    \nFROM sys.dm_exec_sessions s\nJOIN sys.dm_exec_requests r ON s.session_id = r.session_id	blocked transactions	2025-10-15 09:51:24.30787	t	MSSQL	collect
38	-1	Active connections	 SELECT\n      s.session_id AS sid,\n      s.login_name,\n      s.host_name,\n      s.program_name,\n      s.login_time,\n      DATEDIFF(SECOND, s.login_time, GETDATE()) AS connected_seconds,\n      s.status,\n      DB_NAME(s.database_id) AS database_name,\n      r.command,\n      r.wait_type,\n      r.blocking_session_id,\n      t.text AS current_query\n  FROM sys.dm_exec_sessions s\n  LEFT JOIN sys.dm_exec_requests r ON r.session_id = s.session_id\n  OUTER APPLY sys.dm_exec_sql_text(r.sql_handle) t\n  WHERE s.session_id > 50\n    AND s.login_name IS NOT NULL\n    AND s.login_name <> ''\n  ORDER BY s.login_time	Active connections	2025-08-13 06:09:03.787716	t	MSSQL	collect
47	-1	Active connections	SELECT\n    s.sid,\n    s.username AS login_name,\n    s.uid,\n    s.hostname AS host_name,\n    s.progname AS program_name,\n    s.connected AS login_time,\n    s.pid AS client_pid,\n    DBINFO('utc_current') - DBINFO('utc_to_datetime', s.connected) AS connected_seconds\nFROM sysmaster:syssessions s\nWHERE s.sid > 0\n  AND s.username IS NOT NULL\n  AND s.username <> ''\nORDER BY s.connected	Active connections on Informix — shows session ID, user, host, program, connection time and duration from sysmaster:syssessions	2026-04-10 05:36:56.713501	t	informix	collect
48	-1	Connection count per user	SELECT\n    s.username AS login_name,\n    COUNT(*) AS connection_count,\n    COUNT(DISTINCT s.hostname) AS distinct_hosts,\n    COUNT(DISTINCT s.progname) AS distinct_programs\nFROM sysmaster:syssessions s\nWHERE s.sid > 0\n  AND s.username IS NOT NULL\n  AND s.username <> ''\nGROUP BY s.username\nORDER BY connection_count DESC	Connection count per user on Informix — grouped by username with distinct host and program counts	2026-04-10 05:37:11.34972	t	informix	collect
49	-1	Active transactions	SELECT\n    t.tx_id,\n    t.tx_owner AS sid,\n    s.username AS login_name,\n    s.hostname AS host_name,\n    s.progname AS program_name,\n    t.tx_logbeg,\n    t.tx_loguniq,\n    t.tx_flags,\n    DBINFO('utc_current') - t.tx_begtime AS duration_seconds,\n    CASE t.tx_flags\n        WHEN 0 THEN 'inactive'\n        WHEN 1 THEN 'active'\n        WHEN 2 THEN 'committed'\n        WHEN 4 THEN 'rolled back'\n        ELSE 'other (' || t.tx_flags || ')'\n    END AS tx_status\nFROM sysmaster:systrans t\nJOIN sysmaster:syssessions s ON s.sid = t.tx_owner\nORDER BY duration_seconds DESC	Active transactions on Informix — shows transaction ID, owning session, user, host, program, duration, and log usage from sysmaster:systrans	2026-04-10 05:37:59.844959	t	informix	collect
36	-1	Active transactions	 SELECT\n      s.session_id,\n      s.login_name,\n      s.host_name,\n      r.status,\n      r.start_time,\n      r.command,\n      r.cpu_time,\n      r.total_elapsed_time,\n      at.transaction_id,\n      at.name AS transaction_name,\n      LEFT(REPLACE(REPLACE(REPLACE(t.text, NCHAR(0), N''), CHAR(13), N' '), CHAR(10), N' '), 4000) AS query_text\n  FROM sys.dm_exec_sessions s\n  JOIN sys.dm_exec_requests r              ON r.session_id = s.session_id\n  JOIN sys.dm_tran_session_transactions st ON st.session_id = s.session_id\n  JOIN sys.dm_tran_active_transactions at  ON at.transaction_id = st.transaction_id\n  CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) AS t\n  WHERE s.is_user_process = 1\n    AND t.text IS NOT NULL;	Active transactions	2025-08-13 06:04:41.399166	t	MSSQL	collect
50	-1	Active transactions	SELECT\n    sys_context('USERENV','SERVER_HOST')              AS server,\n    sys_context('USERENV','DB_NAME')                  AS database_name,\n    s.sid                                                 AS session_id,\n    s.blocking_session                                    AS blocking_session,\n    ROUND((SYSDATE - TO_DATE(t.start_time,'MM/DD/RR HH24:MI:SS')) * 86400) AS duration_secs,\n    TO_DATE(t.start_time,'MM/DD/RR HH24:MI:SS')         AS start_time,\n    s.username                                            AS login_name,\n    s.program                                             AS program,\n    s.machine                                             AS host_name,\n    s.command                                             AS command,\n    s.last_call_et                                        AS last_call_et,\n    ROUND(NVL(q.cpu_time, 0) / 1000)                      AS cpu_time,\n    (t.xidusn || '.' || t.xidslot || '.' || t.xidsqn) AS transaction_id,\n    REPLACE(REPLACE(REPLACE(\n        DBMS_LOB.SUBSTR(q.sql_fulltext, 4000, 1),\n        CHR(0), ''), CHR(13), ' '), CHR(10), ' ')   AS query_text\nFROM v$transaction t\nJOIN v$session s   ON s.taddr = t.addr\nLEFT JOIN v$sql q  ON q.sql_id = s.sql_id AND q.child_number = s.sql_child_number\nWHERE s.type = 'USER'	Active (open) transactions on Oracle - joins v$transaction to v$session to surface session, login, host, program, duration, CPU, XID and SQL text.	2026-06-07 05:53:21.1043	t	oracle	collect
51	-1	Active transactions	SELECT usename AS login_name, datname AS database_name, pid AS session_id,\n    client_addr AS host_name, application_name AS program_name, xact_start AS start_time,\n    EXTRACT(EPOCH FROM (now() - xact_start))::int AS duration_secs,\n    state, wait_event_type, wait_event, LEFT(query, 4000) AS query\nFROM pg_stat_activity\nWHERE xact_start IS NOT NULL AND pid <> pg_backend_pid()\nORDER BY xact_start	Active (open) transactions on PostgreSQL - rows from pg_stat_activity with a non-null xact_start, showing login, database, host, program, transaction start, duration, wait state and SQL text.	2026-06-07 05:53:21.1043	t	postgresql	collect
52	-1	Active transactions	SELECT trx.trx_id AS transaction_id, trx.trx_mysql_thread_id AS session_id,\n    p.user AS login_name, p.host AS host_name, p.db AS database_name,\n    trx.trx_started AS start_time,\n    TIMESTAMPDIFF(SECOND, trx.trx_started, NOW()) AS duration_secs,\n    trx.trx_state, trx.trx_rows_locked, trx.trx_rows_modified,\n    LEFT(trx.trx_query, 4000) AS query\nFROM information_schema.innodb_trx trx\nLEFT JOIN information_schema.processlist p ON trx.trx_mysql_thread_id = p.id\nORDER BY trx.trx_started	Active (open) transactions on MySQL/MariaDB - rows from information_schema.innodb_trx joined to processlist, showing transaction id, session, login, host, database, start time, duration, locked/modified rows and SQL text.	2026-06-07 05:53:21.1043	t	mysql	collect
\.
INSERT INTO metrics.custom_metrics (row_id, category_id, metric_name, query, description, entry_date, is_active, db_vendor, metrics_type)
SELECT row_id, category_id, metric_name, query, description, entry_date, is_active, db_vendor, metrics_type FROM _stg_load
WHERE NOT EXISTS (SELECT 1 FROM metrics.custom_metrics);
DROP TABLE _stg_load;

SELECT setval('metrics.custom_metrics_row_id_seq', GREATEST((SELECT COALESCE(max(row_id),0) FROM metrics.custom_metrics),1), (SELECT count(*) FROM metrics.custom_metrics) > 0);

DO $do$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint con
        JOIN pg_class c ON c.oid = con.conrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'metrics' AND c.relname = 'custom_metrics'
          AND con.conname = 'custom_metrics_pkey') THEN
        ALTER TABLE ONLY metrics.custom_metrics
    ADD CONSTRAINT custom_metrics_pkey PRIMARY KEY (row_id);
    END IF;
END $do$;
