-- Idempotent install for public.clientdetails
-- Auto-generated from dbanalytics_install.backup. Safe to re-run (psql -f).

CREATE SCHEMA IF NOT EXISTS public;

CREATE SEQUENCE IF NOT EXISTS public.clientdetails_row_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE IF NOT EXISTS public.clientdetails (
    row_id integer NOT NULL,
    osekid character varying(50),
    lname character varying(100),
    fname character varying(100),
    nameview character varying(200),
    meaaged character varying(50),
    toaarid smallint,
    sochenid integer,
    kind1id integer,
    kind2id integer,
    company character varying(50),
    jobid smallint,
    idcard character varying(15),
    street character varying(100),
    cityid integer,
    zip character varying(10),
    mailbox character varying(20),
    phone1 character varying(20),
    phone2 character varying(20),
    phone3 character varying(20),
    fax character varying(20),
    email character varying(100),
    emailinbox character varying(50),
    emailsent character varying(50),
    archive boolean,
    password character varying(20),
    comments character varying(254),
    details text,
    personimage character varying(100),
    mainkind smallint,
    website character varying(100),
    kod character varying(20),
    groupkod integer,
    maham boolean,
    harshahmanager boolean,
    bankid smallint,
    cardkindid smallint,
    paylimitid smallint,
    account character varying(20),
    snif character varying(50),
    cardnum character varying(50),
    carddate character varying(10),
    goremmafneid integer,
    maxashray numeric(19,4) DEFAULT 0,
    hachnasafolder integer,
    pernikuymakor real,
    datenikuymakor timestamp without time zone,
    averagelateness integer,
    gender smallint,
    familystatus smallint,
    childs smallint,
    englishname character varying(30),
    userid integer,
    birthday timestamp without time zone,
    birthcountryid integer,
    fathername character varying(25),
    kupaid smallint,
    bituahid smallint,
    aliayear character varying(4),
    languageid smallint,
    ismabar boolean,
    mothername text,
    kupadoctor character varying(25),
    optniman smallint,
    kabaladate timestamp without time zone,
    ismasav boolean,
    nimanname character varying(50),
    nimanaddress character varying(100),
    notcharged boolean,
    tnuahid integer,
    automirsham boolean,
    harshah character varying(254),
    isuser boolean,
    roomid integer,
    bednum smallint,
    mylistusers character varying(254),
    dayarphone character varying(10),
    interkum integer,
    sidurptira character varying(254),
    tsavah character varying(254),
    idnum integer,
    ext character varying(4),
    kupasnifid integer,
    properties text,
    bsakeret boolean,
    relatedclient integer,
    priceenter numeric(19,4),
    priceback numeric(19,4),
    dateneedenter timestamp without time zone,
    maincontactmanid integer,
    arnonaproperties character varying(50),
    arnonaperdiscount real,
    locationid smallint,
    datefirst timestamp without time zone,
    workerjobper smallint,
    workerjobstart timestamp without time zone,
    languages character varying(254),
    carnum character varying(15),
    cardetails character varying(50),
    bmwebusername character varying(30),
    bmwebpassword character varying(30),
    bmwebkupa character varying(30),
    workerhourprice numeric(19,4),
    workernesiotprice numeric(19,4),
    kodhilut character varying(12),
    iscontactmenshared boolean,
    masavday smallint,
    b2bcity character varying(100),
    city character varying(100),
    transferalcomments text,
    workerjobend timestamp without time zone,
    medicalgroupid smallint,
    userpassport character varying(25),
    relatedname character varying(25),
    masavidcard integer,
    marketingsponserid integer,
    marketingtifkudstatusid integer,
    relatednameidcard character varying(14),
    relatednamebday timestamp without time zone,
    relatednameworkjob character varying(20),
    relatednamebcountry character varying(20),
    armylevel character varying(12),
    armyid character varying(12),
    sponserid integer,
    hospital character varying(50),
    licenseid character varying(50),
    responsibleid integer,
    medmemo character varying(300),
    medprop character varying(300),
    writelastdate timestamp without time zone,
    transferaladdings character varying(200),
    nconv integer,
    hospitaltransferid smallint,
    workerusername character varying(50),
    userprofileid integer,
    guardianname character varying(20),
    guardianfield character varying(20),
    workerroomid character varying(300),
    workerroomjobid character varying(300),
    kupasnif character varying(300),
    bpassport boolean,
    exitforecast timestamp without time zone,
    sapakdiscount integer,
    byoman boolean NOT NULL,
    uniqid integer,
    kvura character varying(30),
    orgid integer NOT NULL,
    currentstatus character varying(20) NOT NULL,
    isshotefpay boolean,
    shotefdays integer,
    clientkod2 character varying(30),
    phone4 character varying(30),
    barchivegroup boolean,
    electricitycredit character varying(20) NOT NULL,
    religionid integer,
    mailtohesh character varying(255) NOT NULL,
    watergardencredit double precision NOT NULL,
    waterhomecredit double precision NOT NULL,
    docfile integer NOT NULL,
    electricitycreditprice character varying(20) NOT NULL,
    watercredit character varying(20) NOT NULL,
    watercreditprice character varying(20) NOT NULL,
    typeheshcollectby integer NOT NULL,
    educationf text,
    yearsofeducation character varying(2),
    sponserkod text NOT NULL,
    lastupdatepassword timestamp without time zone,
    bblockeduser boolean NOT NULL,
    bcompany boolean,
    fnameeng text NOT NULL,
    lnameeng text NOT NULL,
    atdid integer NOT NULL,
    idcardimage text,
    sconvidtobalev integer NOT NULL,
    convidtobalev integer NOT NULL,
    convid integer NOT NULL,
    tstampcreateclient timestamp without time zone NOT NULL,
    password_hashed bytea,
    password_salt character(16),
    validfrom timestamp without time zone,
    validto timestamp without time zone,
    passwordcountryid integer
);

ALTER TABLE public.clientdetails ALTER COLUMN row_id SET DEFAULT nextval('public.clientdetails_row_id_seq'::regclass);
ALTER SEQUENCE public.clientdetails_row_id_seq OWNED BY public.clientdetails.row_id;

SELECT setval('public.clientdetails_row_id_seq', GREATEST((SELECT COALESCE(max(row_id),0) FROM public.clientdetails),1), (SELECT count(*) FROM public.clientdetails) > 0);

DO $do$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint con
        JOIN pg_class c ON c.oid = con.conrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relname = 'clientdetails'
          AND con.conname = 'clientdetails_pkey') THEN
        ALTER TABLE ONLY public.clientdetails
    ADD CONSTRAINT clientdetails_pkey PRIMARY KEY (row_id);
    END IF;
END $do$;
